// Code generated by fdb-go-layer-plugin. DO NOT EDIT.
// Source: github.com/romannikov/fdb-go-layer-plugin/tests/store

package store

import (
	"encoding/binary"
	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	"google.golang.org/protobuf/proto"
)

var _ = binary.LittleEndian

// ProductPaginationOptions represents options for paginated queries
type ProductPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// ProductPaginatedResult represents a paginated result set
type ProductPaginatedResult struct {
	Items   []*Product
	NextKey tuple.Tuple
	HasMore bool
}

func (s *RecordStore) getProductTypeID() (int64, error) {
	if s.metadata == nil {
		return 0, fmt.Errorf("metadata not initialized, call SyncMetadata first")
	}
	typeID, ok := s.metadata["Product"]
	if !ok {
		return 0, fmt.Errorf("type Product not found in metadata")
	}
	return typeID, nil
}

// CreateProduct creates a new Product entity in the database.
func (s *RecordStore) CreateProduct(tr Transaction, dir directory.DirectorySubspace, entity *Product) error {
	typeID, err := s.getProductTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Save atomic fields and zero them out for marshaling

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{

		// Standard index
		indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Category",
			entity.Category,
			entity.Id,
		})
		tr.Set(indexKey, []byte{})

	}

	return nil
}

// GetProduct retrieves a Product entity by its primary key.
func (s *RecordStore) GetProduct(tr fdb.ReadTransaction, dir directory.DirectorySubspace, Id string) (*Product, error) {
	typeID, err := s.getProductTypeID()
	if err != nil {
		return nil, err
	}

	key := dir.Pack(tuple.Tuple{typeID, Id})
	value := tr.Get(key).MustGet()
	if value == nil {
		return nil, fmt.Errorf("product not found")
	}
	entity := &Product{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}

	// Read atomic fields

	return entity, nil
}

// SetProduct updates an existing Product entity in the database.
func (s *RecordStore) SetProduct(tr Transaction, dir directory.DirectorySubspace, entity *Product) error {
	typeID, err := s.getProductTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Clear stale index entries from the old version of the entity
	oldValue := tr.Get(key).MustGet()
	if oldValue != nil {
		old := &Product{}
		if unmarshalErr := proto.Unmarshal(oldValue, old); unmarshalErr == nil {

			{

				// Standard index
				oldIndexKey := dir.Pack(tuple.Tuple{typeID, "index", "Category",
					old.Category,
					old.Id,
				})
				tr.Clear(oldIndexKey)

			}

		}
	}

	// Save atomic fields and zero them out for marshaling

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{

		// Standard index
		indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Category",
			entity.Category,
			entity.Id,
		})
		tr.Set(indexKey, []byte{})

	}

	return nil
}

// DeleteProduct removes a Product entity from the database.
func (s *RecordStore) DeleteProduct(tr Transaction, dir directory.DirectorySubspace, Id string) error {
	typeID, err := s.getProductTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, Id})
	value := tr.Get(key).MustGet()
	if value != nil {
		entity := &Product{}
		err := proto.Unmarshal(value, entity)
		if err == nil {

			{

				// Standard index
				indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Category",
					entity.Category,
					entity.Id,
				})
				tr.Clear(indexKey)

			}

		}
	}
	tr.Clear(key)
	// Clear atomic fields

	return nil
}

// GetProductByCategory retrieves Product entities by their Category index.
func (s *RecordStore) GetProductByCategory(tr fdb.ReadTransaction, dir directory.DirectorySubspace, Category string) ([]*Product, error) {
	typeID, err := s.getProductTypeID()
	if err != nil {
		return nil, err
	}

	entities := []*Product{}
	indexKeyPrefix := dir.Pack(tuple.Tuple{typeID, "index", "Category", Category})
	indexRange, err := fdb.PrefixRange(indexKeyPrefix)
	if err != nil {
		return nil, err
	}
	kvs := tr.GetRange(indexRange, fdb.RangeOptions{}).GetSliceOrPanic()
	for _, kv := range kvs {
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, err
		}
		pkIndexStart := 3 + 1
		pkTuple := tpl[pkIndexStart:]
		keyTpl := append(tuple.Tuple{typeID}, pkTuple...)
		key := dir.Pack(keyTpl)
		value := tr.Get(key).MustGet()
		if value == nil {
			continue
		}
		entity := &Product{}
		err = proto.Unmarshal(value, entity)
		if err != nil {
			return nil, err
		}
		entities = append(entities, entity)
	}
	return entities, nil
}

// BatchGetProduct retrieves multiple Product entities by their primary keys.
func (s *RecordStore) BatchGetProduct(tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Product, error) {
	typeID, err := s.getProductTypeID()
	if err != nil {
		return nil, err
	}

	result := make(map[string]*Product)
	futures := make([]fdb.FutureByteSlice, len(ids))

	for i, id := range ids {
		keyTpl := append(tuple.Tuple{typeID}, id...)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}

	for i, future := range futures {
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Product{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		result[ids[i].String()] = entity
	}

	return result, nil
}

// ListProduct retrieves a list of Product entities starting from the given key.
func (s *RecordStore) ListProduct(tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts ProductPaginationOptions) (*ProductPaginatedResult, error) {
	typeID, err := s.getProductTypeID()
	if err != nil {
		return nil, err
	}

	result := &ProductPaginatedResult{
		Items: make([]*Product, 0),
	}

	beginTpl := append(tuple.Tuple{typeID}, opts.Begin...)
	begin := dir.Pack(beginTpl)

	// Scan all keys under typeID. We request extra rows to account for
	// index entries that will be filtered out.
	typePrefix := dir.Pack(tuple.Tuple{typeID})
	typePrefixRange, err := fdb.PrefixRange(typePrefix)
	if err != nil {
		return nil, err
	}

	iter := tr.GetRange(fdb.KeyRange{
		Begin: begin,
		End:   typePrefixRange.End,
	}, fdb.RangeOptions{
		Reverse: false,
	}).Iterator()

	var nextKey fdb.Key
	for iter.Advance() {
		kv := iter.MustGet()

		// Skip index entries: their second tuple element is the string "index".
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack key: %w", err)
		}
		if len(tpl) >= 2 {
			if s, ok := tpl[1].(string); ok && s == "index" {
				continue
			}
		}

		entity := &Product{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID to return just the PK tuple
		result.NextKey = tpl[1:]
		result.Items = result.Items[:opts.Limit]
	}

	return result, nil
}

type ProductRepository struct {
	store *RecordStore
}

func NewProductRepository(store *RecordStore) *ProductRepository {
	return &ProductRepository{store: store}
}

func (r *ProductRepository) Create(tr Transaction, dir directory.DirectorySubspace, entity *Product) error {
	return r.store.CreateProduct(tr, dir, entity)
}

func (r *ProductRepository) Get(tr fdb.ReadTransaction, dir directory.DirectorySubspace, key tuple.Tuple) (*Product, error) {
	return r.store.GetProduct(tr, dir, key[0].(string))
}

func (r *ProductRepository) Set(tr Transaction, dir directory.DirectorySubspace, entity *Product) error {
	return r.store.SetProduct(tr, dir, entity)
}

func (r *ProductRepository) Delete(tr Transaction, dir directory.DirectorySubspace, key tuple.Tuple) error {
	return r.store.DeleteProduct(tr, dir, key[0].(string))
}

func (r *ProductRepository) BatchGet(tr fdb.ReadTransaction, dir directory.DirectorySubspace, keys []tuple.Tuple) (map[string]*Product, error) {
	return r.store.BatchGetProduct(tr, dir, keys)
}

func (r *ProductRepository) List(tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts PaginationOptions) (*PaginatedResult[Product], error) {
	specificOpts := ProductPaginationOptions{Begin: opts.Begin, Limit: opts.Limit}
	res, err := r.store.ListProduct(tr, dir, specificOpts)
	if err != nil {
		return nil, err
	}
	return &PaginatedResult[Product]{Items: res.Items, NextKey: res.NextKey, HasMore: res.HasMore}, nil
}
