// Code generated by fdb-go-layer-plugin. DO NOT EDIT.
// Source: github.com/romannikov/fdb-go-layer-plugin/tests/store

package store

import (
	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	"google.golang.org/protobuf/proto"
)

// UserPaginationOptions represents options for paginated queries
type UserPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// UserPaginatedResult represents a paginated result set
type UserPaginatedResult struct {
	Items   []*User
	NextKey tuple.Tuple
	HasMore bool
}

func (s *RecordStore) getUserTypeID() (int64, error) {
	if s.metadata == nil {
		return 0, fmt.Errorf("metadata not initialized, call SyncMetadata first")
	}
	typeID, ok := s.metadata["User"]
	if !ok {
		return 0, fmt.Errorf("type User not found in metadata")
	}
	return typeID, nil
}

// CreateUser creates a new User entity in the database.
func (s *RecordStore) CreateUser(tr Transaction, dir directory.DirectorySubspace, entity *User) error {
	typeID, err := s.getUserTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Save atomic fields and zero them out for marshaling

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{

		// Standard index
		indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Email",
			entity.Email,
			entity.Id,
		})
		tr.Set(indexKey, []byte{})

	}

	return nil
}

// GetUser retrieves a User entity by its primary key.
func (s *RecordStore) GetUser(tr fdb.ReadTransaction, dir directory.DirectorySubspace, Id string) (*User, error) {
	typeID, err := s.getUserTypeID()
	if err != nil {
		return nil, err
	}

	key := dir.Pack(tuple.Tuple{typeID, Id})
	value := tr.Get(key).MustGet()
	if value == nil {
		return nil, fmt.Errorf("user not found")
	}
	entity := &User{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}

	// Read atomic fields

	return entity, nil
}

// SetUser updates an existing User entity in the database.
func (s *RecordStore) SetUser(tr Transaction, dir directory.DirectorySubspace, entity *User) error {
	typeID, err := s.getUserTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Clear stale index entries from the old version of the entity
	oldValue := tr.Get(key).MustGet()
	if oldValue != nil {
		old := &User{}
		if unmarshalErr := proto.Unmarshal(oldValue, old); unmarshalErr == nil {

			{

				// Standard index
				oldIndexKey := dir.Pack(tuple.Tuple{typeID, "index", "Email",
					old.Email,
					old.Id,
				})
				tr.Clear(oldIndexKey)

			}

		}
	}

	// Save atomic fields and zero them out for marshaling

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{

		// Standard index
		indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Email",
			entity.Email,
			entity.Id,
		})
		tr.Set(indexKey, []byte{})

	}

	return nil
}

// DeleteUser removes a User entity from the database.
func (s *RecordStore) DeleteUser(tr Transaction, dir directory.DirectorySubspace, Id string) error {
	typeID, err := s.getUserTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, Id})
	value := tr.Get(key).MustGet()
	if value != nil {
		entity := &User{}
		err := proto.Unmarshal(value, entity)
		if err == nil {

			{

				// Standard index
				indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Email",
					entity.Email,
					entity.Id,
				})
				tr.Clear(indexKey)

			}

		}
	}
	tr.Clear(key)
	// Clear atomic fields

	return nil
}

// GetUserByEmail retrieves User entities by their Email index.
func (s *RecordStore) GetUserByEmail(tr fdb.ReadTransaction, dir directory.DirectorySubspace, Email string) ([]*User, error) {
	typeID, err := s.getUserTypeID()
	if err != nil {
		return nil, err
	}

	entities := []*User{}
	indexKeyPrefix := dir.Pack(tuple.Tuple{typeID, "index", "Email", Email})
	indexRange, err := fdb.PrefixRange(indexKeyPrefix)
	if err != nil {
		return nil, err
	}
	kvs := tr.GetRange(indexRange, fdb.RangeOptions{}).GetSliceOrPanic()
	for _, kv := range kvs {
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, err
		}
		pkIndexStart := 3 + 1
		pkTuple := tpl[pkIndexStart:]
		keyTpl := append(tuple.Tuple{typeID}, pkTuple...)
		key := dir.Pack(keyTpl)
		value := tr.Get(key).MustGet()
		if value == nil {
			continue
		}
		entity := &User{}
		err = proto.Unmarshal(value, entity)
		if err != nil {
			return nil, err
		}
		entities = append(entities, entity)
	}
	return entities, nil
}

// BatchGetUser retrieves multiple User entities by their primary keys.
func (s *RecordStore) BatchGetUser(tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*User, error) {
	typeID, err := s.getUserTypeID()
	if err != nil {
		return nil, err
	}

	result := make(map[string]*User)
	futures := make([]fdb.FutureByteSlice, len(ids))

	for i, id := range ids {
		keyTpl := append(tuple.Tuple{typeID}, id...)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}

	for i, future := range futures {
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &User{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		result[ids[i].String()] = entity
	}

	return result, nil
}

// ListUser retrieves a list of User entities starting from the given key.
func (s *RecordStore) ListUser(tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts UserPaginationOptions) (*UserPaginatedResult, error) {
	typeID, err := s.getUserTypeID()
	if err != nil {
		return nil, err
	}

	result := &UserPaginatedResult{
		Items: make([]*User, 0),
	}

	beginTpl := append(tuple.Tuple{typeID}, opts.Begin...)
	begin := dir.Pack(beginTpl)

	// Scan all keys under typeID. We request extra rows to account for
	// index entries that will be filtered out.
	typePrefix := dir.Pack(tuple.Tuple{typeID})
	typePrefixRange, err := fdb.PrefixRange(typePrefix)
	if err != nil {
		return nil, err
	}

	iter := tr.GetRange(fdb.KeyRange{
		Begin: begin,
		End:   typePrefixRange.End,
	}, fdb.RangeOptions{
		Reverse: false,
	}).Iterator()

	var nextKey fdb.Key
	for iter.Advance() {
		kv := iter.MustGet()

		// Skip index entries: their second tuple element is the string "index".
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack key: %w", err)
		}
		if len(tpl) >= 2 {
			if s, ok := tpl[1].(string); ok && s == "index" {
				continue
			}
		}

		entity := &User{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID to return just the PK tuple
		result.NextKey = tpl[1:]
		result.Items = result.Items[:opts.Limit]
	}

	return result, nil
}

// UserRepository defines the repository interface for User.
type UserRepository interface {
	GenericRepository[*User, string]

	BatchGetUser(tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*User, error)
	ListUser(tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts UserPaginationOptions) (*UserPaginatedResult, error)

	GetUserByEmail(tr fdb.ReadTransaction, dir directory.DirectorySubspace, Email string) ([]*User, error)
}

type userRepository struct {
	store *RecordStore
}

// NewUserRepository creates a new UserRepository instance.
func NewUserRepository(store *RecordStore) UserRepository {
	return &userRepository{store: store}
}

func (r *userRepository) Create(tr Transaction, dir directory.DirectorySubspace, entity *User) error {
	return r.store.CreateUser(tr, dir, entity)
}

func (r *userRepository) Get(tr fdb.ReadTransaction, dir directory.DirectorySubspace, pk string) (*User, error) {
	return r.store.GetUser(tr, dir, pk)
}

func (r *userRepository) Set(tr Transaction, dir directory.DirectorySubspace, entity *User) error {
	return r.store.SetUser(tr, dir, entity)
}

func (r *userRepository) Delete(tr Transaction, dir directory.DirectorySubspace, pk string) error {
	return r.store.DeleteUser(tr, dir, pk)
}

func (r *userRepository) BatchGetUser(tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*User, error) {
	return r.store.BatchGetUser(tr, dir, ids)
}

func (r *userRepository) ListUser(tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts UserPaginationOptions) (*UserPaginatedResult, error) {
	return r.store.ListUser(tr, dir, opts)
}

func (r *userRepository) GetUserByEmail(tr fdb.ReadTransaction, dir directory.DirectorySubspace, Email string) ([]*User, error) {
	return r.store.GetUserByEmail(tr, dir, Email)
}
