// Code generated by fdb-go-layer-plugin. DO NOT EDIT.
// Source: github.com/romannikov/fdb-go-layer-plugin/tests/store

package store

import (
	"encoding/binary"
	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	"google.golang.org/protobuf/proto"
)

var _ = binary.LittleEndian

// PostPaginationOptions represents options for paginated queries
type PostPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// PostPaginatedResult represents a paginated result set
type PostPaginatedResult struct {
	Items   []*Post
	NextKey tuple.Tuple
	HasMore bool
}

func (s *RecordStore) getPostTypeID() (int64, error) {
	if s.metadata == nil {
		return 0, fmt.Errorf("metadata not initialized, call SyncMetadata first")
	}
	typeID, ok := s.metadata["Post"]
	if !ok {
		return 0, fmt.Errorf("type Post not found in metadata")
	}
	return typeID, nil
}

type PostRepository struct {
	store *RecordStore
}

func NewPostRepository(store *RecordStore) *PostRepository {
	return &PostRepository{store: store}
}

// Create creates a new Post entity in the database.
func (r *PostRepository) Create(tr Transaction, dir directory.DirectorySubspace, entity *Post) error {
	typeID, err := r.store.getPostTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Save atomic fields and zero them out for marshaling

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{

		// Fan-out index

		for _, item := range entity.Tags {
			indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Tags",

				item,

				entity.Id,
			})
			tr.Set(indexKey, []byte{})
		}

	}

	return nil
}

// Get retrieves a Post entity by its primary key.
func (r *PostRepository) Get(tr fdb.ReadTransaction, dir directory.DirectorySubspace, key tuple.Tuple) (*Post, error) {
	typeID, err := r.store.getPostTypeID()
	if err != nil {
		return nil, err
	}

	Id := key[0].(string)

	fdbKey := dir.Pack(tuple.Tuple{typeID, Id})
	value := tr.Get(fdbKey).MustGet()
	if value == nil {
		return nil, fmt.Errorf("post not found")
	}
	entity := &Post{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}

	// Read atomic fields

	return entity, nil
}

// Set updates an existing Post entity in the database.
func (r *PostRepository) Set(tr Transaction, dir directory.DirectorySubspace, entity *Post) error {
	typeID, err := r.store.getPostTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Clear stale index entries from the old version of the entity
	oldValue := tr.Get(key).MustGet()
	if oldValue != nil {
		old := &Post{}
		if unmarshalErr := proto.Unmarshal(oldValue, old); unmarshalErr == nil {

			{

				// Fan-out index

				for _, item := range old.Tags {
					oldIndexKey := dir.Pack(tuple.Tuple{typeID, "index", "Tags",

						item,

						old.Id,
					})
					tr.Clear(oldIndexKey)
				}

			}

		}
	}

	// Save atomic fields and zero them out for marshaling

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{

		// Fan-out index

		for _, item := range entity.Tags {
			indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Tags",

				item,

				entity.Id,
			})
			tr.Set(indexKey, []byte{})
		}

	}

	return nil
}

// Delete removes a Post entity from the database.
func (r *PostRepository) Delete(tr Transaction, dir directory.DirectorySubspace, key tuple.Tuple) error {
	typeID, err := r.store.getPostTypeID()
	if err != nil {
		return err
	}

	Id := key[0].(string)

	fdbKey := dir.Pack(tuple.Tuple{typeID, Id})
	value := tr.Get(fdbKey).MustGet()
	if value != nil {
		entity := &Post{}
		err := proto.Unmarshal(value, entity)
		if err == nil {

			{

				// Fan-out index

				for _, item := range entity.Tags {
					indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Tags",

						item,

						entity.Id,
					})
					tr.Clear(indexKey)
				}

			}

		}
	}
	tr.Clear(fdbKey)
	// Clear atomic fields

	return nil
}

// GetByTags retrieves Post entities by their Tags index.
func (r *PostRepository) GetByTags(tr fdb.ReadTransaction, dir directory.DirectorySubspace, Tags string) ([]*Post, error) {
	typeID, err := r.store.getPostTypeID()
	if err != nil {
		return nil, err
	}

	entities := []*Post{}
	indexKeyPrefix := dir.Pack(tuple.Tuple{typeID, "index", "Tags", Tags})
	indexRange, err := fdb.PrefixRange(indexKeyPrefix)
	if err != nil {
		return nil, err
	}
	kvs := tr.GetRange(indexRange, fdb.RangeOptions{}).GetSliceOrPanic()
	for _, kv := range kvs {
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, err
		}
		pkIndexStart := 3 + 1
		pkTuple := tpl[pkIndexStart:]
		keyTpl := append(tuple.Tuple{typeID}, pkTuple...)
		key := dir.Pack(keyTpl)
		value := tr.Get(key).MustGet()
		if value == nil {
			continue
		}
		entity := &Post{}
		err = proto.Unmarshal(value, entity)
		if err != nil {
			return nil, err
		}
		entities = append(entities, entity)
	}
	return entities, nil
}

// BatchGet retrieves multiple Post entities by their primary keys.
func (r *PostRepository) BatchGet(tr fdb.ReadTransaction, dir directory.DirectorySubspace, keys []tuple.Tuple) (map[string]*Post, error) {
	typeID, err := r.store.getPostTypeID()
	if err != nil {
		return nil, err
	}

	result := make(map[string]*Post)
	futures := make([]fdb.FutureByteSlice, len(keys))

	for i, id := range keys {
		keyTpl := append(tuple.Tuple{typeID}, id...)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}

	for i, future := range futures {
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Post{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		result[keys[i].String()] = entity
	}

	return result, nil
}

// List retrieves a list of Post entities starting from the given key.
func (r *PostRepository) List(tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts PaginationOptions) (*PaginatedResult[Post], error) {
	typeID, err := r.store.getPostTypeID()
	if err != nil {
		return nil, err
	}

	result := &PaginatedResult[Post]{
		Items: make([]*Post, 0),
	}

	beginTpl := append(tuple.Tuple{typeID}, opts.Begin...)
	begin := dir.Pack(beginTpl)

	// Scan all keys under typeID. We request extra rows to account for
	// index entries that will be filtered out.
	typePrefix := dir.Pack(tuple.Tuple{typeID})
	typePrefixRange, err := fdb.PrefixRange(typePrefix)
	if err != nil {
		return nil, err
	}

	iter := tr.GetRange(fdb.KeyRange{
		Begin: begin,
		End:   typePrefixRange.End,
	}, fdb.RangeOptions{
		Reverse: false,
	}).Iterator()

	var nextKey fdb.Key
	for iter.Advance() {
		kv := iter.MustGet()

		// Skip index entries: their second tuple element is the string "index".
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack key: %w", err)
		}
		if len(tpl) >= 2 {
			if s, ok := tpl[1].(string); ok && s == "index" {
				continue
			}
		}

		entity := &Post{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID to return just the PK tuple
		result.NextKey = tpl[1:]
		result.Items = result.Items[:opts.Limit]
	}

	return result, nil
}
