// Code generated by fdb-go-layer-plugin. DO NOT EDIT.
// Source: github.com/romannikov/fdb-go-layer-plugin/tests/store

package store

import (
	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
)

// Transaction is a mockable interface that abstracts fdb.Transaction
type Transaction interface {
	fdb.ReadTransaction
	Set(key fdb.KeyConvertible, value []byte)
	Clear(key fdb.KeyConvertible)
}

// RecordStore holds metadata mapping between message names and their integer type IDs.
type RecordStore struct {
	metadata map[string]int64
}

// NewRecordStore creates a new RecordStore instance.
func NewRecordStore() *RecordStore {
	return &RecordStore{
		metadata: make(map[string]int64),
	}
}

// Metadata returns a read-only copy of the metadata mapping.
func (s *RecordStore) Metadata() map[string]int64 {
	copy := make(map[string]int64, len(s.metadata))
	for k, v := range s.metadata {
		copy[k] = v
	}
	return copy
}

// SyncMetadata reads the existing metadata from FDB and assigns new IDs to any unmapped messages.
func (s *RecordStore) SyncMetadata(tr Transaction, metaDir directory.DirectorySubspace) error {
	kvs := tr.GetRange(metaDir, fdb.RangeOptions{}).GetSliceOrPanic()

	maxID := int64(0)
	for _, kv := range kvs {
		tpl, err := metaDir.Unpack(kv.Key)
		if err != nil {
			return err
		}
		valTpl, err := tuple.Unpack(kv.Value)
		if err != nil {
			return err
		}
		msgName := tpl[0].(string)
		id := valTpl[0].(int64)
		s.metadata[msgName] = id
		if id > maxID {
			maxID = id
		}
	}

	messages := []string{
		"User",
		"Product",
		"Post",
	}

	for _, msg := range messages {
		if _, exists := s.metadata[msg]; !exists {
			maxID++
			s.metadata[msg] = maxID
			key := metaDir.Pack(tuple.Tuple{msg})
			val := tuple.Tuple{int64(maxID)}.Pack()
			tr.Set(key, val)
		}
	}
	return nil
}
