// Code generated by fdb-go-layer-plugin. DO NOT EDIT.
// Source: github.com/romannikov/fdb-go-layer-plugin/tests/store

package store

import (
	"encoding/binary"
	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	"google.golang.org/protobuf/proto"
)

// DocumentPaginationOptions represents options for paginated queries
type DocumentPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// DocumentPaginatedResult represents a paginated result set
type DocumentPaginatedResult struct {
	Items   []*Document
	NextKey tuple.Tuple
	HasMore bool
}

func (s *RecordStore) getDocumentTypeID() (int64, error) {
	if s.metadata == nil {
		return 0, fmt.Errorf("metadata not initialized, call SyncMetadata first")
	}
	typeID, ok := s.metadata["Document"]
	if !ok {
		return 0, fmt.Errorf("type Document not found in metadata")
	}
	return typeID, nil
}

// CreateDocument creates a new Document entity in the database.
func (s *RecordStore) CreateDocument(tr Transaction, dir directory.DirectorySubspace, entity *Document) error {
	typeID, err := s.getDocumentTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})
	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}
	tr.Set(key, value)

	{

		// Versionstamp index
		prefixTpl := tuple.Tuple{typeID, "index", "versionstamp"}
		prefixBytes := dir.Pack(prefixTpl)
		offset := uint16(len(prefixBytes))

		pkTpl := tuple.Tuple{entity.Id}
		pkBytes := pkTpl.Pack()

		keyBytes := append(prefixBytes, make([]byte, 10)...)
		keyBytes = append(keyBytes, pkBytes...)

		offsetBytes := make([]byte, 2)
		binary.LittleEndian.PutUint16(offsetBytes, offset)
		keyBytes = append(keyBytes, offsetBytes...)

		tr.SetVersionstampedKey(fdb.Key(keyBytes), []byte{})

	}

	return nil
}

// GetDocument retrieves a Document entity by its primary key.
func (s *RecordStore) GetDocument(tr fdb.ReadTransaction, dir directory.DirectorySubspace, Id string) (*Document, error) {
	typeID, err := s.getDocumentTypeID()
	if err != nil {
		return nil, err
	}

	key := dir.Pack(tuple.Tuple{typeID, Id})
	value := tr.Get(key).MustGet()
	if value == nil {
		return nil, fmt.Errorf("document not found")
	}
	entity := &Document{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}
	return entity, nil
}

// SetDocument updates an existing Document entity in the database.
func (s *RecordStore) SetDocument(tr Transaction, dir directory.DirectorySubspace, entity *Document) error {
	typeID, err := s.getDocumentTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Clear stale index entries from the old version of the entity
	oldValue := tr.Get(key).MustGet()
	if oldValue != nil {
		old := &Document{}
		if unmarshalErr := proto.Unmarshal(oldValue, old); unmarshalErr == nil {

			{

				// For versionstamp index, we cannot easily clear the old entry
				// without knowing the old versionstamp.

			}

		}
	}

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}
	tr.Set(key, value)

	{

		// Versionstamp index
		prefixTpl := tuple.Tuple{typeID, "index", "versionstamp"}
		prefixBytes := dir.Pack(prefixTpl)
		offset := uint16(len(prefixBytes))

		pkTpl := tuple.Tuple{entity.Id}
		pkBytes := pkTpl.Pack()

		keyBytes := append(prefixBytes, make([]byte, 10)...)
		keyBytes = append(keyBytes, pkBytes...)

		offsetBytes := make([]byte, 2)
		binary.LittleEndian.PutUint16(offsetBytes, offset)
		keyBytes = append(keyBytes, offsetBytes...)

		tr.SetVersionstampedKey(fdb.Key(keyBytes), []byte{})

	}

	return nil
}

// DeleteDocument removes a Document entity from the database.
func (s *RecordStore) DeleteDocument(tr Transaction, dir directory.DirectorySubspace, Id string) error {
	typeID, err := s.getDocumentTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, Id})
	value := tr.Get(key).MustGet()
	if value != nil {
		entity := &Document{}
		err := proto.Unmarshal(value, entity)
		if err == nil {

			{

				// For versionstamp index, we cannot easily clear the old entry
				// without knowing the old versionstamp.

			}

		}
	}
	tr.Clear(key)
	return nil
}

// GetDocumentByVersionstamp retrieves Document entities ordered by versionstamp.
func (s *RecordStore) GetDocumentByVersionstamp(tr fdb.ReadTransaction, dir directory.DirectorySubspace, beginVersionstamp []byte, endVersionstamp []byte) ([]*Document, error) {
	typeID, err := s.getDocumentTypeID()
	if err != nil {
		return nil, err
	}
	entities := []*Document{}

	var begin, end fdb.Key
	if len(beginVersionstamp) > 0 {
		begin = dir.Pack(tuple.Tuple{typeID, "index", "versionstamp", beginVersionstamp})
	} else {
		beginRange, _ := fdb.PrefixRange(dir.Pack(tuple.Tuple{typeID, "index", "versionstamp"}))
		begin = beginRange.Begin.FDBKey()
	}

	if len(endVersionstamp) > 0 {
		end = dir.Pack(tuple.Tuple{typeID, "index", "versionstamp", endVersionstamp})
	} else {
		endRange, _ := fdb.PrefixRange(dir.Pack(tuple.Tuple{typeID, "index", "versionstamp"}))
		end = endRange.End.FDBKey()
	}

	kvs := tr.GetRange(fdb.KeyRange{Begin: begin, End: end}, fdb.RangeOptions{}).GetSliceOrPanic()
	for _, kv := range kvs {
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, err
		}
		pkTuple := tpl[4:]
		keyTpl := append(tuple.Tuple{typeID}, pkTuple...)
		key := dir.Pack(keyTpl)
		value := tr.Get(key).MustGet()
		if value == nil {
			continue
		}
		entity := &Document{}
		err = proto.Unmarshal(value, entity)
		if err != nil {
			return nil, err
		}
		entities = append(entities, entity)
	}
	return entities, nil
}

// BatchGetDocument retrieves multiple Document entities by their primary keys.
func (s *RecordStore) BatchGetDocument(tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Document, error) {
	typeID, err := s.getDocumentTypeID()
	if err != nil {
		return nil, err
	}

	result := make(map[string]*Document)
	futures := make([]fdb.FutureByteSlice, len(ids))

	for i, id := range ids {
		keyTpl := append(tuple.Tuple{typeID}, id...)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}

	for i, future := range futures {
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Document{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		result[ids[i].String()] = entity
	}

	return result, nil
}

// ListDocument retrieves a list of Document entities starting from the given key.
func (s *RecordStore) ListDocument(tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts DocumentPaginationOptions) (*DocumentPaginatedResult, error) {
	typeID, err := s.getDocumentTypeID()
	if err != nil {
		return nil, err
	}

	result := &DocumentPaginatedResult{
		Items: make([]*Document, 0),
	}

	beginTpl := append(tuple.Tuple{typeID}, opts.Begin...)
	begin := dir.Pack(beginTpl)

	// Scan all keys under typeID. We request extra rows to account for
	// index entries that will be filtered out.
	typePrefix := dir.Pack(tuple.Tuple{typeID})
	typePrefixRange, err := fdb.PrefixRange(typePrefix)
	if err != nil {
		return nil, err
	}

	iter := tr.GetRange(fdb.KeyRange{
		Begin: begin,
		End:   typePrefixRange.End,
	}, fdb.RangeOptions{
		Reverse: false,
	}).Iterator()

	var nextKey fdb.Key
	for iter.Advance() {
		kv := iter.MustGet()

		// Skip index entries: their second tuple element is the string "index".
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack key: %w", err)
		}
		if len(tpl) >= 2 {
			if s, ok := tpl[1].(string); ok && s == "index" {
				continue
			}
		}

		entity := &Document{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID to return just the PK tuple
		result.NextKey = tpl[1:]
		result.Items = result.Items[:opts.Limit]
	}

	return result, nil
}
