package rust

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/romannikov/fdb-layer/compiler/ir"
)

// Printer is a minimal line-oriented code emitter (compatible with protogen.GeneratedFile.P).
type Printer interface {
	P(v ...any)
}

// BufferPrinter collects emitted lines into a strings.Builder.
type BufferPrinter struct {
	sb strings.Builder
}

// P writes a line to the buffer.
func (b *BufferPrinter) P(v ...any) {
	for _, x := range v {
		fmt.Fprint(&b.sb, x)
	}
	b.sb.WriteByte('\n')
}

// String returns the accumulated Rust source code.
func (b *BufferPrinter) String() string {
	return b.sb.String()
}

// FieldSnake returns the snake_case field name for a FieldSpec.
func FieldSnake(f ir.FieldSpec) string {
	if f.ProtoName != "" {
		return SnakeCase(f.ProtoName)
	}
	if f.RustName != "" {
		return strings.TrimPrefix(f.RustName, "r#")
	}
	return SnakeCase(f.GoName)
}

// FieldIdent returns the Rust identifier for a FieldSpec (escaping keywords with r#).
func FieldIdent(f ir.FieldSpec) string {
	if f.RustName != "" {
		return f.RustName
	}
	return RustIdent(FieldSnake(f))
}

// GenerateOptions configures Rust code generation.
type GenerateOptions struct {
	GenerateMessages bool
}

// GenerateFile emits the complete Rust repository file (*.fdb.rs) for all annotated
// messages in a Protobuf file.
func GenerateFile(g Printer, sourceName string, messages []ir.MessageSpec) {
	GenerateFileWithOptions(g, sourceName, messages, GenerateOptions{})
}

// GenerateFileWithOptions emits the complete Rust repository file (*.fdb.rs) with configurable options.
func GenerateFileWithOptions(g Printer, sourceName string, messages []ir.MessageSpec, opts GenerateOptions) {
	g.P("// Code generated by protoc-gen-fdb-rust. DO NOT EDIT.")
	g.P("// Source: ", sourceName)
	g.P()
	for i, msg := range messages {
		if i > 0 {
			g.P()
		}
		if opts.GenerateMessages {
			GenerateProstMessage(g, msg)
			g.P()
		}
		GenerateMessage(g, msg)
	}
}

// GenerateProstMessage emits a prost::Message struct definition for msg.
func GenerateProstMessage(g Printer, msg ir.MessageSpec) {
	g.P("#[allow(dead_code, clippy::all)]")
	g.P("#[derive(Clone, PartialEq, ::prost::Message)]")
	g.P("pub struct ", msg.Name, " {")
	for _, f := range msg.Fields {
		g.P("    #[prost(", fieldProstAttr(f), ")]")
		g.P("    pub ", FieldIdent(f), ": ", fieldProstStructType(f), ",")
	}
	g.P("}")
}

func fieldProstAttr(f ir.FieldSpec) string {
	var kindAttr string
	switch f.Kind {
	case ir.KindInt32, ir.KindEnum:
		kindAttr = "int32"
	case ir.KindSint32:
		kindAttr = "sint32"
	case ir.KindSfixed32:
		kindAttr = "sfixed32"
	case ir.KindInt64:
		kindAttr = "int64"
	case ir.KindSint64:
		kindAttr = "sint64"
	case ir.KindSfixed64:
		kindAttr = "sfixed64"
	case ir.KindUint32:
		kindAttr = "uint32"
	case ir.KindFixed32:
		kindAttr = "fixed32"
	case ir.KindUint64:
		kindAttr = "uint64"
	case ir.KindFixed64:
		kindAttr = "fixed64"
	case ir.KindFloat:
		kindAttr = "float"
	case ir.KindDouble:
		kindAttr = "double"
	case ir.KindString:
		kindAttr = "string"
	case ir.KindBool:
		kindAttr = "bool"
	case ir.KindBytes:
		kindAttr = `bytes = "vec"`
	default:
		kindAttr = `bytes = "vec"`
	}
	if f.IsRepeated {
		return fmt.Sprintf(`%s, repeated, tag = "%d"`, kindAttr, f.Number)
	}
	return fmt.Sprintf(`%s, tag = "%d"`, kindAttr, f.Number)
}

func fieldProstStructType(f ir.FieldSpec) string {
	base := FieldRustType(f)
	if f.IsRepeated {
		return fmt.Sprintf("Vec<%s>", base)
	}
	return base
}

// GenerateMessage emits the Rust repository code for a single ir.MessageSpec.
func GenerateMessage(g Printer, msg ir.MessageSpec) {
	if msg.IsQueue {
		generateQueueRepository(g, msg)
	} else {
		generateEntityRepository(g, msg)
	}
}

func generateQueueRepository(g Printer, msg ir.MessageSpec) {
	firstPK := msg.PrimaryKeyFields[0]
	firstPKSnake := FieldIdent(firstPK)
	hasVS := ir.MsgHasVersionstampPK(msg)

	g.P("/// Repository for the `", msg.Name, "` FIFO queue.")
	g.P("#[allow(dead_code, clippy::all)]")
	g.P("#[derive(Clone)]")
	g.P("pub struct ", msg.Name, "Repository {")
	g.P("    store: std::sync::Arc<fdb_layer::RecordStore>,")
	g.P("}")
	g.P()
	g.P("#[allow(dead_code, clippy::all)]")
	g.P("impl ", msg.Name, "Repository {")
	g.P("    pub fn new(store: std::sync::Arc<fdb_layer::RecordStore>) -> Self {")
	g.P("        Self { store }")
	g.P("    }")
	g.P()
	g.P("    /// Enqueues a `", msg.Name, "` into the queue.")
	g.P("    pub async fn enqueue(")
	g.P("        &self,")
	g.P("        tr: &fdb_layer::Transaction,")
	g.P("        dir: &fdb_layer::Subspace,")
	g.P("        entity: &", msg.Name, ",")
	g.P("    ) -> Result<(), fdb_layer::FdbLayerError> {")
	g.P(`        let type_id = self.store.get_type_id("`, msg.Name, `")?;`)
	if hasVS {
		g.P("        let key = dir.pack_with_versionstamp(&(type_id, fdb_layer::DATA_NAMESPACE, ", versionstampedPKTupleArgs(msg), "));")
	} else {
		g.P("        let key = dir.pack(&(type_id, fdb_layer::DATA_NAMESPACE, ", pkTupleArgsFromEntity(msg, "entity"), "));")
	}
	g.P("        let value = fdb_layer::prost::Message::encode_to_vec(entity);")
	if hasVS {
		g.P("        tr.atomic_op(&key, &value, fdb_layer::MutationType::SetVersionstampedKey);")
	} else {
		g.P("        tr.set(&key, &value);")
	}
	g.P("        Ok(())")
	g.P("    }")
	g.P()
	g.P("    /// Dequeues and removes the single oldest `", msg.Name, "` from the queue.")
	g.P("    pub async fn dequeue(")
	g.P("        &self,")
	g.P("        tr: &fdb_layer::Transaction,")
	g.P("        dir: &fdb_layer::Subspace,")
	g.P("        ", firstPKSnake, ": ", FieldRustParamType(firstPK), ",")
	g.P("    ) -> Result<Option<", msg.Name, ">, fdb_layer::FdbLayerError> {")
	g.P("        use fdb_layer::futures::TryStreamExt;")
	g.P(`        let type_id = self.store.get_type_id("`, msg.Name, `")?;`)
	g.P("        let prefix = dir.pack(&(type_id, fdb_layer::DATA_NAMESPACE, ", PackField(firstPKSnake, firstPK), "));")
	g.P("        let range_opt = fdb_layer::prefix_range_option(&prefix, Some(1));")
	g.P("        let rows: Vec<_> = tr.get_ranges_keyvalues(range_opt, false).try_collect().await?;")
	g.P("        let first_item = match rows.first() {")
	g.P("            Some(item) => item,")
	g.P("            None => return Ok(None),")
	g.P("        };")
	g.P("        let key_to_delete = first_item.key();")
	g.P("        let payload = first_item.value();")
	g.P("        tr.clear(key_to_delete);")
	g.P("        let mut entity = <", msg.Name, " as fdb_layer::prost::Message>::decode(payload)?;")
	if hasVS {
		g.P("        let tpl = dir.unpack::<Vec<fdb_layer::Element<'_>>>(key_to_delete)?;")
		for i, f := range msg.PrimaryKeyFields {
			if f.IsVersionstamp {
				g.P("        if let Some(vs) = tpl.get(", i+2, ").and_then(|e| e.as_versionstamp()) {")
				g.P("            entity.", FieldIdent(f), " = vs.as_bytes().to_vec();")
				g.P("        }")
			}
		}
	}
	g.P("        Ok(Some(entity))")
	g.P("    }")
	g.P("}")
}

func generateEntityRepository(g Printer, msg ir.MessageSpec) {
	pkType := pkRustTypeExpr(msg)

	g.P("#[allow(dead_code)]")
	g.P("pub type ", msg.Name, "PaginationOptions = fdb_layer::PaginationOptions;")
	g.P("#[allow(dead_code)]")
	g.P("pub type ", msg.Name, "PaginatedResult = fdb_layer::PaginatedResult<", msg.Name, ">;")
	g.P()

	if len(msg.PrimaryKeyFields) > 1 {
		g.P("/// Compound primary key for `", msg.Name, "`.")
		g.P("#[allow(dead_code, clippy::all)]")
		g.P("#[derive(Debug, Clone, PartialEq)]")
		g.P("pub struct ", msg.Name, "PrimaryKey {")
		for _, f := range msg.PrimaryKeyFields {
			g.P("    pub ", FieldIdent(f), ": ", FieldRustType(f), ",")
		}
		g.P("}")
		g.P()
	}

	g.P("/// Repository for `", msg.Name, "` entities.")
	g.P("#[allow(dead_code, clippy::all)]")
	g.P("#[derive(Clone)]")
	g.P("pub struct ", msg.Name, "Repository {")
	g.P("    store: std::sync::Arc<fdb_layer::RecordStore>,")
	g.P("}")
	g.P()
	g.P("#[allow(dead_code, clippy::all)]")
	g.P("impl ", msg.Name, "Repository {")
	g.P("    pub fn new(store: std::sync::Arc<fdb_layer::RecordStore>) -> Self {")
	g.P("        Self { store }")
	g.P("    }")
	g.P()

	generateCreate(g, msg)
	generateGet(g, msg)
	generateSet(g, msg)
	generateDelete(g, msg)
	generateBatchGet(g, msg)
	generateList(g, msg)
	for _, idx := range msg.SecondaryIndexes {
		generateGetByIndex(g, msg, idx)
	}
	generateAtomicMutators(g, msg)

	g.P("}")
	g.P()

	if len(msg.PrimaryKeyFields) == 1 && (msg.PrimaryKeyFields[0].Kind == ir.KindString || msg.PrimaryKeyFields[0].Kind == ir.KindBytes) {
		ownedPK := FieldRustType(msg.PrimaryKeyFields[0])
		g.P("#[fdb_layer::async_trait]")
		g.P("impl fdb_layer::GenericRepository<", msg.Name, ", ", ownedPK, "> for ", msg.Name, "Repository {")
		g.P("    async fn create(")
		g.P("        &self,")
		g.P("        tr: &fdb_layer::Transaction,")
		g.P("        dir: &fdb_layer::Subspace,")
		g.P("        entity: &", msg.Name, ",")
		g.P("    ) -> Result<(), fdb_layer::FdbLayerError> {")
		g.P("        Self::create(self, tr, dir, entity).await")
		g.P("    }")
		g.P()
		g.P("    async fn get(")
		g.P("        &self,")
		g.P("        tr: &fdb_layer::Transaction,")
		g.P("        dir: &fdb_layer::Subspace,")
		g.P("        pk: ", ownedPK, ",")
		g.P("    ) -> Result<", msg.Name, ", fdb_layer::FdbLayerError> {")
		g.P("        Self::get(self, tr, dir, &pk).await")
		g.P("    }")
		g.P()
		g.P("    async fn set(")
		g.P("        &self,")
		g.P("        tr: &fdb_layer::Transaction,")
		g.P("        dir: &fdb_layer::Subspace,")
		g.P("        entity: &", msg.Name, ",")
		g.P("    ) -> Result<(), fdb_layer::FdbLayerError> {")
		g.P("        Self::set(self, tr, dir, entity).await")
		g.P("    }")
		g.P()
		g.P("    async fn delete(")
		g.P("        &self,")
		g.P("        tr: &fdb_layer::Transaction,")
		g.P("        dir: &fdb_layer::Subspace,")
		g.P("        pk: ", ownedPK, ",")
		g.P("    ) -> Result<(), fdb_layer::FdbLayerError> {")
		g.P("        Self::delete(self, tr, dir, &pk).await")
		g.P("    }")
		g.P("}")
	} else {
		g.P("#[fdb_layer::async_trait]")
		g.P("impl fdb_layer::GenericRepository<", msg.Name, ", ", pkType, "> for ", msg.Name, "Repository {")
		g.P("    async fn create(")
		g.P("        &self,")
		g.P("        tr: &fdb_layer::Transaction,")
		g.P("        dir: &fdb_layer::Subspace,")
		g.P("        entity: &", msg.Name, ",")
		g.P("    ) -> Result<(), fdb_layer::FdbLayerError> {")
		g.P("        Self::create(self, tr, dir, entity).await")
		g.P("    }")
		g.P()
		g.P("    async fn get(")
		g.P("        &self,")
		g.P("        tr: &fdb_layer::Transaction,")
		g.P("        dir: &fdb_layer::Subspace,")
		g.P("        pk: ", pkType, ",")
		g.P("    ) -> Result<", msg.Name, ", fdb_layer::FdbLayerError> {")
		g.P("        Self::get(self, tr, dir, pk).await")
		g.P("    }")
		g.P()
		g.P("    async fn set(")
		g.P("        &self,")
		g.P("        tr: &fdb_layer::Transaction,")
		g.P("        dir: &fdb_layer::Subspace,")
		g.P("        entity: &", msg.Name, ",")
		g.P("    ) -> Result<(), fdb_layer::FdbLayerError> {")
		g.P("        Self::set(self, tr, dir, entity).await")
		g.P("    }")
		g.P()
		g.P("    async fn delete(")
		g.P("        &self,")
		g.P("        tr: &fdb_layer::Transaction,")
		g.P("        dir: &fdb_layer::Subspace,")
		g.P("        pk: ", pkType, ",")
		g.P("    ) -> Result<(), fdb_layer::FdbLayerError> {")
		g.P("        Self::delete(self, tr, dir, pk).await")
		g.P("    }")
		g.P("}")
	}
}

func generateCreate(g Printer, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	hasVS := ir.MsgHasVersionstampPK(msg)
	hasMut := ir.HasMutationFields(msg)
	pkArgs := pkTupleArgsFromEntity(msg, "entity")

	g.P("    pub async fn create(")
	g.P("        &self,")
	g.P("        tr: &fdb_layer::Transaction,")
	g.P("        dir: &fdb_layer::Subspace,")
	g.P("        entity: &", msg.Name, ",")
	g.P("    ) -> Result<(), fdb_layer::FdbLayerError> {")
	g.P(`        let type_id = self.store.get_type_id("`, msg.Name, `")?;`)
	if hasVS {
		g.P("        let key = dir.pack_with_versionstamp(&(type_id, fdb_layer::DATA_NAMESPACE, ", versionstampedPKTupleArgs(msg), "));")
	} else {
		g.P("        let key = dir.pack(&(type_id, fdb_layer::DATA_NAMESPACE, ", pkArgs, "));")
		g.P("        if tr.get(&key, false).await?.is_some() {")
		g.P(`            return Err(fdb_layer::FdbLayerError::AlreadyExists("`, lowerName, `"));`)
		g.P("        }")
	}

	generateEncodeWithZeroedAtomics(g, msg, "        ")

	if hasVS {
		g.P("        tr.atomic_op(&key, &value, fdb_layer::MutationType::SetVersionstampedKey);")
	} else {
		g.P("        tr.set(&key, &value);")
	}

	if hasMut {
		for _, f := range msg.Fields {
			if f.Mutation != ir.MutationNone {
				ident := FieldIdent(f)
				g.P("        if entity.", ident, " != 0 {")
				g.P("            let field_key = dir.pack(&(type_id, fdb_layer::FIELD_NAMESPACE, ", pkArgs, ", ", f.Number, "i64));")
				g.P("            let buf = ", encodeAtomicRustExpr("entity."+ident, f), ".to_le_bytes();")
				g.P("            tr.atomic_op(&field_key, &buf, fdb_layer::MutationType::", MutationEnumVariant(f.Mutation), ");")
				g.P("        }")
			}
		}
	}

	for _, idx := range msg.SecondaryIndexes {
		if idx.IsFanOut {
			for i, f := range idx.Fields {
				if f.IsRepeated {
					g.P("        for item in &entity.", FieldIdent(f), " {")
					emitFanOutIndexWrite(g, msg, idx, i, "entity", true, "            ")
					g.P("        }")
				}
			}
		} else {
			g.P("        tr.set(&dir.pack(&(type_id, fdb_layer::INDEX_NAMESPACE, ", idx.IndexID, "i64, ", indexFieldTupleArgs(idx.Fields, "entity"), ", ", pkArgs, ")), &[]);")
		}
	}

	g.P("        Ok(())")
	g.P("    }")
	g.P()
}

func generateGet(g Printer, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	pkType := pkRustTypeExpr(msg)
	pkArgs := pkTupleArgsFromParam(msg)
	hasMut := ir.HasMutationFields(msg)

	g.P("    pub async fn get(")
	g.P("        &self,")
	g.P("        tr: &fdb_layer::Transaction,")
	g.P("        dir: &fdb_layer::Subspace,")
	g.P("        pk: ", pkType, ",")
	g.P("    ) -> Result<", msg.Name, ", fdb_layer::FdbLayerError> {")
	if hasMut {
		g.P("        use fdb_layer::futures::TryStreamExt;")
	}
	g.P(`        let type_id = self.store.get_type_id("`, msg.Name, `")?;`)
	g.P("        let key = dir.pack(&(type_id, fdb_layer::DATA_NAMESPACE, ", pkArgs, "));")
	if hasMut {
		g.P("        let field_prefix = dir.pack(&(type_id, fdb_layer::FIELD_NAMESPACE, ", pkArgs, "));")
		g.P("        let field_range = fdb_layer::prefix_range_option(&field_prefix, None);")
		g.P("        let val_fut = tr.get(&key, false);")
		g.P("        let field_fut = tr.get_ranges_keyvalues(field_range, false).try_collect::<Vec<_>>();")
		g.P("        let (value_opt, field_kvs) = fdb_layer::futures::future::try_join(val_fut, field_fut).await?;")
	} else {
		g.P("        let value_opt = tr.get(&key, false).await?;")
	}
	g.P("        let value = value_opt.ok_or(fdb_layer::FdbLayerError::NotFound(\"", lowerName, "\"))?;")
	if hasMut {
		g.P("        let mut entity = <", msg.Name, " as fdb_layer::prost::Message>::decode(value.as_ref())?;")
		generateUnmarshalAtomicFields(g, msg, "&field_kvs", "        ")
	} else {
		g.P("        let entity = <", msg.Name, " as fdb_layer::prost::Message>::decode(value.as_ref())?;")
	}
	g.P("        Ok(entity)")
	g.P("    }")
	g.P()
}

func generateSet(g Printer, msg ir.MessageSpec) {
	hasVS := ir.MsgHasVersionstampPK(msg)
	pkArgsEntity := pkTupleArgsFromEntity(msg, "entity")
	pkArgsOld := pkTupleArgsFromEntity(msg, "old")

	g.P("    pub async fn set(")
	g.P("        &self,")
	g.P("        tr: &fdb_layer::Transaction,")
	g.P("        dir: &fdb_layer::Subspace,")
	g.P("        entity: &", msg.Name, ",")
	g.P("    ) -> Result<(), fdb_layer::FdbLayerError> {")
	g.P(`        let type_id = self.store.get_type_id("`, msg.Name, `")?;`)

	if len(msg.SecondaryIndexes) > 0 {
		g.P("        let mut old: Option<", msg.Name, "> = None;")
	}

	if hasVS {
		var vsFieldIdent string
		for _, f := range msg.PrimaryKeyFields {
			if f.IsVersionstamp {
				vsFieldIdent = FieldIdent(f)
				break
			}
		}
		g.P("        if entity.", vsFieldIdent, ".iter().any(|&b| b != 0) {")
		g.P("            let old_key = dir.pack(&(type_id, fdb_layer::DATA_NAMESPACE, ", pkArgsEntity, "));")
		g.P("            tr.clear(&old_key);")
		g.P("        }")
		g.P("        let key = dir.pack_with_versionstamp(&(type_id, fdb_layer::DATA_NAMESPACE, ", versionstampedPKTupleArgs(msg), "));")
	} else {
		g.P("        let key = dir.pack(&(type_id, fdb_layer::DATA_NAMESPACE, ", pkArgsEntity, "));")
		if len(msg.SecondaryIndexes) > 0 {
			g.P("        if let Some(old_val) = tr.get(&key, false).await? {")
			g.P("            old = Some(<", msg.Name, " as fdb_layer::prost::Message>::decode(old_val.as_ref())?);")
			g.P("        }")
		}
	}

	generateEncodeWithZeroedAtomics(g, msg, "        ")

	if hasVS {
		g.P("        tr.atomic_op(&key, &value, fdb_layer::MutationType::SetVersionstampedKey);")
	} else {
		g.P("        tr.set(&key, &value);")
	}

	for _, idx := range msg.SecondaryIndexes {
		if idx.IsFanOut {
			for i, f := range idx.Fields {
				if f.IsRepeated {
					ident := FieldIdent(f)
					g.P("        if let Some(ref old) = old {")
					if HasNonRepeatedFields(idx.Fields) {
						g.P("            if ", NonRepeatedFieldsEqual(idx.Fields), " {")
						g.P("                let old_set: std::collections::HashSet<_> = old.", ident, ".iter().collect();")
						g.P("                let new_set: std::collections::HashSet<_> = entity.", ident, ".iter().collect();")
						g.P("                for item in &old.", ident, " {")
						g.P("                    if !new_set.contains(item) {")
						emitFanOutIndexWrite(g, msg, idx, i, "old", false, "                        ")
						g.P("                    }")
						g.P("                }")
						g.P("                for item in &entity.", ident, " {")
						g.P("                    if !old_set.contains(item) {")
						emitFanOutIndexWrite(g, msg, idx, i, "entity", true, "                        ")
						g.P("                    }")
						g.P("                }")
						g.P("            } else {")
						g.P("                for item in &old.", ident, " {")
						emitFanOutIndexWrite(g, msg, idx, i, "old", false, "                    ")
						g.P("                }")
						g.P("                for item in &entity.", ident, " {")
						emitFanOutIndexWrite(g, msg, idx, i, "entity", true, "                    ")
						g.P("                }")
						g.P("            }")
					} else {
						g.P("            let old_set: std::collections::HashSet<_> = old.", ident, ".iter().collect();")
						g.P("            let new_set: std::collections::HashSet<_> = entity.", ident, ".iter().collect();")
						g.P("            for item in &old.", ident, " {")
						g.P("                if !new_set.contains(item) {")
						emitFanOutIndexWrite(g, msg, idx, i, "old", false, "                    ")
						g.P("                }")
						g.P("            }")
						g.P("            for item in &entity.", ident, " {")
						g.P("                if !old_set.contains(item) {")
						emitFanOutIndexWrite(g, msg, idx, i, "entity", true, "                    ")
						g.P("                }")
						g.P("            }")
					}
					g.P("        } else {")
					g.P("            for item in &entity.", ident, " {")
					emitFanOutIndexWrite(g, msg, idx, i, "entity", true, "                ")
					g.P("            }")
					g.P("        }")
				}
			}
		} else {
			var diffParts []string
			for _, f := range idx.Fields {
				ident := FieldIdent(f)
				diffParts = append(diffParts, fmt.Sprintf("old.%s != entity.%s", ident, ident))
			}
			g.P("        let idx_changed = match old {")
			g.P("            Some(ref old) => ", strings.Join(diffParts, " || "), ",")
			g.P("            None => true,")
			g.P("        };")
			g.P("        if idx_changed {")
			g.P("            if let Some(ref old) = old {")
			g.P("                tr.clear(&dir.pack(&(type_id, fdb_layer::INDEX_NAMESPACE, ", idx.IndexID, "i64, ", indexFieldTupleArgs(idx.Fields, "old"), ", ", pkArgsOld, ")));")
			g.P("            }")
			g.P("            tr.set(&dir.pack(&(type_id, fdb_layer::INDEX_NAMESPACE, ", idx.IndexID, "i64, ", indexFieldTupleArgs(idx.Fields, "entity"), ", ", pkArgsEntity, ")), &[]);")
			g.P("        }")
		}
	}

	g.P("        Ok(())")
	g.P("    }")
	g.P()
}

func generateDelete(g Printer, msg ir.MessageSpec) {
	pkType := pkRustTypeExpr(msg)
	pkArgs := pkTupleArgsFromParam(msg)
	pkArgsEntity := pkTupleArgsFromEntity(msg, "entity")

	g.P("    pub async fn delete(")
	g.P("        &self,")
	g.P("        tr: &fdb_layer::Transaction,")
	g.P("        dir: &fdb_layer::Subspace,")
	g.P("        pk: ", pkType, ",")
	g.P("    ) -> Result<(), fdb_layer::FdbLayerError> {")
	g.P(`        let type_id = self.store.get_type_id("`, msg.Name, `")?;`)
	g.P("        let key = dir.pack(&(type_id, fdb_layer::DATA_NAMESPACE, ", pkArgs, "));")
	if len(msg.SecondaryIndexes) > 0 {
		g.P("        if let Some(value) = tr.get(&key, false).await? {")
		g.P("            let entity = <", msg.Name, " as fdb_layer::prost::Message>::decode(value.as_ref())?;")
		for _, idx := range msg.SecondaryIndexes {
			if idx.IsFanOut {
				for i, f := range idx.Fields {
					if f.IsRepeated {
						g.P("            for item in &entity.", FieldIdent(f), " {")
						emitFanOutIndexWrite(g, msg, idx, i, "entity", false, "                ")
						g.P("            }")
					}
				}
			} else {
				g.P("            tr.clear(&dir.pack(&(type_id, fdb_layer::INDEX_NAMESPACE, ", idx.IndexID, "i64, ", indexFieldTupleArgs(idx.Fields, "entity"), ", ", pkArgsEntity, ")));")
			}
		}
		g.P("        }")
	}
	g.P("        tr.clear(&key);")
	if ir.HasMutationFields(msg) {
		for _, f := range msg.Fields {
			if f.Mutation != ir.MutationNone {
				g.P("        {")
				g.P("            let field_key = dir.pack(&(type_id, fdb_layer::FIELD_NAMESPACE, ", pkArgs, ", ", f.Number, "i64));")
				g.P("            tr.clear(&field_key);")
				g.P("        }")
			}
		}
	}
	g.P("        Ok(())")
	g.P("    }")
	g.P()
}

func generateBatchGet(g Printer, msg ir.MessageSpec) {
	snakeName := SnakeCase(msg.Name)
	hasMut := ir.HasMutationFields(msg)

	g.P("    pub async fn batch_get_", snakeName, "(")
	g.P("        &self,")
	g.P("        tr: &fdb_layer::Transaction,")
	g.P("        dir: &fdb_layer::Subspace,")
	g.P("        ids: &[Vec<fdb_layer::Element<'_>>],")
	g.P("    ) -> Result<std::collections::HashMap<String, ", msg.Name, ">, fdb_layer::FdbLayerError> {")
	if hasMut {
		g.P("        use fdb_layer::futures::TryStreamExt;")
	}
	g.P(`        let type_id = self.store.get_type_id("`, msg.Name, `")?;`)
	g.P("        let mut result = std::collections::HashMap::new();")
	g.P("        let mut val_futures = Vec::with_capacity(ids.len());")
	if hasMut {
		g.P("        let mut field_futures = Vec::with_capacity(ids.len());")
	}
	g.P("        for id in ids {")
	g.P("            let mut key_tpl = Vec::with_capacity(2 + id.len());")
	g.P("            key_tpl.push(fdb_layer::Element::Int(type_id));")
	g.P("            key_tpl.push(fdb_layer::Element::Int(fdb_layer::DATA_NAMESPACE));")
	g.P("            key_tpl.extend(id.iter().cloned());")
	g.P("            let key = dir.pack(&key_tpl);")
	g.P("            val_futures.push(tr.get(&key, false));")
	if hasMut {
		g.P("            let mut field_tpl = Vec::with_capacity(2 + id.len());")
		g.P("            field_tpl.push(fdb_layer::Element::Int(type_id));")
		g.P("            field_tpl.push(fdb_layer::Element::Int(fdb_layer::FIELD_NAMESPACE));")
		g.P("            field_tpl.extend(id.iter().cloned());")
		g.P("            let field_prefix = dir.pack(&field_tpl);")
		g.P("            let field_range = fdb_layer::prefix_range_option(&field_prefix, None);")
		g.P("            field_futures.push(tr.get_ranges_keyvalues(field_range, false).try_collect::<Vec<_>>());")
	}
	g.P("        }")
	g.P("        let values = fdb_layer::futures::future::try_join_all(val_futures).await?;")
	if hasMut {
		g.P("        let field_slices = fdb_layer::futures::future::try_join_all(field_futures).await?;")
	}
	g.P("        for (i, value_opt) in values.into_iter().enumerate() {")
	g.P("            let value = match value_opt {")
	g.P("                Some(v) => v,")
	g.P("                None => continue,")
	g.P("            };")
	if hasMut {
		g.P("            let mut entity = <", msg.Name, " as fdb_layer::prost::Message>::decode(value.as_ref())?;")
		generateUnmarshalAtomicFields(g, msg, "&field_slices[i]", "            ")
	} else {
		g.P("            let entity = <", msg.Name, " as fdb_layer::prost::Message>::decode(value.as_ref())?;")
	}
	g.P("            result.insert(fdb_layer::format_tuple(&ids[i]), entity);")
	g.P("        }")
	g.P("        Ok(result)")
	g.P("    }")
	g.P()
}

func generateList(g Printer, msg ir.MessageSpec) {
	snakeName := SnakeCase(msg.Name)
	hasMut := ir.HasMutationFields(msg)

	g.P("    pub async fn list_", snakeName, "(")
	g.P("        &self,")
	g.P("        tr: &fdb_layer::Transaction,")
	g.P("        dir: &fdb_layer::Subspace,")
	g.P("        opts: ", msg.Name, "PaginationOptions,")
	g.P("    ) -> Result<", msg.Name, "PaginatedResult, fdb_layer::FdbLayerError> {")
	g.P("        use fdb_layer::futures::TryStreamExt;")
	g.P(`        let type_id = self.store.get_type_id("`, msg.Name, `")?;`)
	g.P("        let mut result = ", msg.Name, "PaginatedResult::default();")
	g.P("        let mut begin_tpl = Vec::with_capacity(2 + opts.begin.len());")
	g.P("        begin_tpl.push(fdb_layer::Element::Int(type_id));")
	g.P("        begin_tpl.push(fdb_layer::Element::Int(fdb_layer::DATA_NAMESPACE));")
	g.P("        begin_tpl.extend(opts.begin.iter().cloned());")
	g.P("        let begin = dir.pack(&begin_tpl);")
	g.P("        let data_prefix = dir.pack(&(type_id, fdb_layer::DATA_NAMESPACE));")
	g.P("        let (_, end) = fdb_layer::prefix_range(&data_prefix);")
	g.P("        let limit = if opts.limit > 0 { Some(opts.limit + 1) } else { None };")
	g.P("        let range_opt = fdb_layer::RangeOption {")
	g.P("            begin: fdb_layer::KeySelector::first_greater_or_equal(begin),")
	g.P("            end: fdb_layer::KeySelector::first_greater_or_equal(end),")
	g.P("            limit,")
	g.P("            reverse: false,")
	g.P("            ..fdb_layer::RangeOption::default()")
	g.P("        };")
	g.P("        let kvs: Vec<_> = tr.get_ranges_keyvalues(range_opt, false).try_collect().await?;")
	g.P("        let mut next_key_raw: Option<Vec<u8>> = None;")
	g.P("        for kv in &kvs {")
	g.P("            let entity = <", msg.Name, " as fdb_layer::prost::Message>::decode(kv.value())?;")
	g.P("            result.items.push(entity);")
	g.P("            next_key_raw = Some(kv.key().to_vec());")
	g.P("            if opts.limit > 0 && result.items.len() > opts.limit {")
	g.P("                break;")
	g.P("            }")
	g.P("        }")
	g.P("        result.has_more = opts.limit > 0 && result.items.len() > opts.limit;")
	g.P("        if result.has_more {")
	g.P("            if let Some(ref nk) = next_key_raw {")
	g.P("                let tpl: Vec<fdb_layer::Element<'_>> = dir.unpack(nk)?;")
	g.P("                result.next_key = tpl.into_iter().skip(2).map(|e| e.into_owned()).collect();")
	g.P("            }")
	g.P("            result.items.truncate(opts.limit);")
	g.P("        }")
	if hasMut {
		firstPKArgs := pkTupleArgsFromEntity(msg, "first")
		lastPKArgs := pkTupleArgsFromEntity(msg, "last")
		entityPKArgs := pkTupleArgsFromEntity(msg, "entity")

		g.P("        if !result.items.is_empty() {")
		g.P("            let first = &result.items[0];")
		g.P("            let last = &result.items[result.items.len() - 1];")
		g.P("            let field_begin = dir.pack(&(type_id, fdb_layer::FIELD_NAMESPACE, ", firstPKArgs, "));")
		g.P("            let field_end_prefix = dir.pack(&(type_id, fdb_layer::FIELD_NAMESPACE, ", lastPKArgs, "));")
		g.P("            let (_, field_end) = fdb_layer::prefix_range(&field_end_prefix);")
		g.P("            let mut idx_by_pk = std::collections::HashMap::with_capacity(result.items.len());")
		g.P("            for (idx, entity) in result.items.iter_mut().enumerate() {")
		for _, f := range msg.Fields {
			if f.Mutation != ir.MutationNone {
				g.P("                entity.", FieldIdent(f), " = 0;")
			}
		}
		g.P("                let pk_bytes = fdb_layer::foundationdb_tuple::pack(&(", entityPKArgs, ",));")
		g.P("                idx_by_pk.insert(pk_bytes, idx);")
		g.P("            }")
		g.P("            let field_range = fdb_layer::RangeOption {")
		g.P("                begin: fdb_layer::KeySelector::first_greater_or_equal(field_begin),")
		g.P("                end: fdb_layer::KeySelector::first_greater_or_equal(field_end),")
		g.P("                ..fdb_layer::RangeOption::default()")
		g.P("            };")
		g.P("            let field_kvs: Vec<_> = tr.get_ranges_keyvalues(field_range, false).try_collect().await?;")
		g.P("            let pk_len = ", len(msg.PrimaryKeyFields), "usize;")
		g.P("            for fkv in &field_kvs {")
		g.P("                if fkv.value().len() < 8 {")
		g.P("                    continue;")
		g.P("                }")
		g.P("                let ftpl = match dir.unpack::<Vec<fdb_layer::Element<'_>>>(fkv.key()) {")
		g.P("                    Ok(t) if t.len() >= 3 + pk_len => t,")
		g.P("                    _ => continue,")
		g.P("                };")
		g.P("                let pk_slice = &ftpl[2..2 + pk_len];")
		g.P("                let pk_bytes = fdb_layer::foundationdb_tuple::pack(&pk_slice);")
		g.P("                let item_idx = match idx_by_pk.get(&pk_bytes) {")
		g.P("                    Some(&i) => i,")
		g.P("                    None => continue,")
		g.P("                };")
		g.P("                let field_num = match ftpl[2 + pk_len].as_i64() {")
		g.P("                    Some(n) => n,")
		g.P("                    None => continue,")
		g.P("                };")
		g.P("                let mut raw_bytes = [0u8; 8];")
		g.P("                raw_bytes.copy_from_slice(&fkv.value()[..8]);")
		g.P("                let raw_u64 = u64::from_le_bytes(raw_bytes);")
		g.P("                let entity = &mut result.items[item_idx];")
		g.P("                match field_num {")
		for _, f := range msg.Fields {
			if f.Mutation != ir.MutationNone {
				g.P("                    ", f.Number, " => entity.", FieldIdent(f), " = ", decodeAtomicRustExpr("raw_u64", f), ",")
			}
		}
		g.P("                    _ => {}")
		g.P("                }")
		g.P("            }")
		g.P("        }")
	}
	g.P("        Ok(result)")
	g.P("    }")
	g.P()
}

func generateGetByIndex(g Printer, msg ir.MessageSpec, idx ir.SecondaryIndexSpec) {
	snakeMsg := SnakeCase(msg.Name)
	joinedSnake := JoinFieldNamesSnake(idx.Fields)
	hasMut := ir.HasMutationFields(msg)

	var idxPackArgs []string
	for _, f := range idx.Fields {
		idxPackArgs = append(idxPackArgs, PackField(FieldIdent(f), f))
	}

	g.P("    pub async fn get_", snakeMsg, "_by_", joinedSnake, "(")
	g.P("        &self,")
	g.P("        tr: &fdb_layer::Transaction,")
	g.P("        dir: &fdb_layer::Subspace,")
	g.P("        ", fieldRustParamDecls(idx.Fields), ",")
	g.P("    ) -> Result<Vec<", msg.Name, ">, fdb_layer::FdbLayerError> {")
	g.P("        use fdb_layer::futures::TryStreamExt;")
	g.P(`        let type_id = self.store.get_type_id("`, msg.Name, `")?;`)
	g.P("        let index_key_prefix = dir.pack(&(type_id, fdb_layer::INDEX_NAMESPACE, ", idx.IndexID, "i64, ", strings.Join(idxPackArgs, ", "), "));")
	g.P("        let index_range = fdb_layer::prefix_range_option(&index_key_prefix, None);")
	g.P("        let kvs: Vec<_> = tr.get_ranges_keyvalues(index_range, false).try_collect().await?;")
	g.P("        let mut val_futures = Vec::with_capacity(kvs.len());")
	if hasMut {
		g.P("        let mut field_futures = Vec::with_capacity(kvs.len());")
	}
	g.P("        for kv in &kvs {")
	g.P("            let tpl: Vec<fdb_layer::Element<'_>> = dir.unpack(kv.key())?;")
	g.P("            let pk_index_start = 3 + ", len(idx.Fields), "usize;")
	g.P("            if tpl.len() <= pk_index_start {")
	g.P("                continue;")
	g.P("            }")
	g.P("            let pk_tuple = &tpl[pk_index_start..];")
	g.P("            let mut key_tpl = Vec::with_capacity(2 + pk_tuple.len());")
	g.P("            key_tpl.push(fdb_layer::Element::Int(type_id));")
	g.P("            key_tpl.push(fdb_layer::Element::Int(fdb_layer::DATA_NAMESPACE));")
	g.P("            key_tpl.extend_from_slice(pk_tuple);")
	g.P("            let key = dir.pack(&key_tpl);")
	g.P("            val_futures.push(tr.get(&key, false));")
	if hasMut {
		g.P("            let mut field_tpl = Vec::with_capacity(2 + pk_tuple.len());")
		g.P("            field_tpl.push(fdb_layer::Element::Int(type_id));")
		g.P("            field_tpl.push(fdb_layer::Element::Int(fdb_layer::FIELD_NAMESPACE));")
		g.P("            field_tpl.extend_from_slice(pk_tuple);")
		g.P("            let field_prefix = dir.pack(&field_tpl);")
		g.P("            let field_range = fdb_layer::prefix_range_option(&field_prefix, None);")
		g.P("            field_futures.push(tr.get_ranges_keyvalues(field_range, false).try_collect::<Vec<_>>());")
	}
	g.P("        }")
	g.P("        let values = fdb_layer::futures::future::try_join_all(val_futures).await?;")
	if hasMut {
		g.P("        let field_slices = fdb_layer::futures::future::try_join_all(field_futures).await?;")
	}
	g.P("        let mut entities = Vec::with_capacity(values.len());")
	iterPattern := "(_i, value_opt)"
	if hasMut {
		iterPattern = "(i, value_opt)"
	}
	g.P("        for ", iterPattern, " in values.into_iter().enumerate() {")
	g.P("            let value = match value_opt {")
	g.P("                Some(v) => v,")
	g.P("                None => continue,")
	g.P("            };")
	if hasMut {
		g.P("            let mut entity = <", msg.Name, " as fdb_layer::prost::Message>::decode(value.as_ref())?;")
		generateUnmarshalAtomicFields(g, msg, "&field_slices[i]", "            ")
	} else {
		g.P("            let entity = <", msg.Name, " as fdb_layer::prost::Message>::decode(value.as_ref())?;")
	}
	g.P("            entities.push(entity);")
	g.P("        }")
	g.P("        Ok(entities)")
	g.P("    }")
	g.P()
}

func generateAtomicMutators(g Printer, msg ir.MessageSpec) {
	snakeMsg := SnakeCase(msg.Name)
	var pkPackArgs []string
	for _, f := range msg.PrimaryKeyFields {
		pkPackArgs = append(pkPackArgs, PackField(FieldIdent(f), f))
	}
	pkArgsStr := strings.Join(pkPackArgs, ", ")

	for _, f := range msg.Fields {
		if f.Mutation == ir.MutationNone {
			continue
		}
		verb := strings.ToLower(MutationEnumVariant(f.Mutation))
		fieldSnake := FieldSnake(f)
		g.P("    pub async fn ", verb, "_", snakeMsg, "_", fieldSnake, "(")
		g.P("        &self,")
		g.P("        tr: &fdb_layer::Transaction,")
		g.P("        dir: &fdb_layer::Subspace,")
		g.P("        ", fieldRustParamDecls(msg.PrimaryKeyFields), ",")
		g.P("        val: ", FieldRustType(f), ",")
		g.P("    ) -> Result<(), fdb_layer::FdbLayerError> {")
		g.P(`        let type_id = self.store.get_type_id("`, msg.Name, `")?;`)
		g.P("        let key = dir.pack(&(type_id, fdb_layer::FIELD_NAMESPACE, ", pkArgsStr, ", ", f.Number, "i64));")
		g.P("        let buf = ", encodeAtomicRustExpr("val", f), ".to_le_bytes();")
		g.P("        tr.atomic_op(&key, &buf, fdb_layer::MutationType::", MutationEnumVariant(f.Mutation), ");")
		g.P("        Ok(())")
		g.P("    }")
		g.P()
	}
}

func encodeAtomicRustExpr(expr string, f ir.FieldSpec) string {
	if !f.IsUnsigned && (f.Mutation == ir.MutationMax || f.Mutation == ir.MutationMin) {
		if FieldRustType(f) == "i64" {
			return fmt.Sprintf("((%s as u64) ^ (1u64 << 63))", expr)
		}
		return fmt.Sprintf("((%s as i64 as u64) ^ (1u64 << 63))", expr)
	}
	return fmt.Sprintf("(%s as u64)", expr)
}

func decodeAtomicRustExpr(rawVar string, f ir.FieldSpec) string {
	if !f.IsUnsigned && (f.Mutation == ir.MutationMax || f.Mutation == ir.MutationMin) {
		if FieldRustType(f) == "i64" {
			return fmt.Sprintf("(%s ^ (1u64 << 63)) as i64", rawVar)
		}
		return fmt.Sprintf("((%s ^ (1u64 << 63)) as i64) as %s", rawVar, FieldRustType(f))
	}
	return fmt.Sprintf("%s as %s", rawVar, FieldRustType(f))
}

func generateEncodeWithZeroedAtomics(g Printer, msg ir.MessageSpec, indent string) {
	if ir.HasMutationFields(msg) {
		var nonZeroChecks []string
		for _, f := range msg.Fields {
			if f.Mutation != ir.MutationNone {
				nonZeroChecks = append(nonZeroChecks, fmt.Sprintf("entity.%s != 0", FieldIdent(f)))
			}
		}
		g.P(indent, "let value = if ", strings.Join(nonZeroChecks, " || "), " {")
		g.P(indent, "    let mut clean_entity = entity.clone();")
		for _, f := range msg.Fields {
			if f.Mutation != ir.MutationNone {
				g.P(indent, "    clean_entity.", FieldIdent(f), " = 0;")
			}
		}
		g.P(indent, "    fdb_layer::prost::Message::encode_to_vec(&clean_entity)")
		g.P(indent, "} else {")
		g.P(indent, "    fdb_layer::prost::Message::encode_to_vec(entity)")
		g.P(indent, "};")
	} else {
		g.P(indent, "let value = fdb_layer::prost::Message::encode_to_vec(entity);")
	}
}

func generateUnmarshalAtomicFields(g Printer, msg ir.MessageSpec, sliceExpr string, indent string) {
	for _, f := range msg.Fields {
		if f.Mutation != ir.MutationNone {
			g.P(indent, "entity.", FieldIdent(f), " = 0;")
		}
	}
	g.P(indent, "for fkv in ", sliceExpr, " {")
	g.P(indent, "    if fkv.value().len() < 8 {")
	g.P(indent, "        continue;")
	g.P(indent, "    }")
	g.P(indent, "    let ftpl = match dir.unpack::<Vec<fdb_layer::Element<'_>>>(fkv.key()) {")
	g.P(indent, "        Ok(t) if !t.is_empty() => t,")
	g.P(indent, "        _ => continue,")
	g.P(indent, "    };")
	g.P(indent, "    let field_num = match ftpl.last().and_then(|e| e.as_i64()) {")
	g.P(indent, "        Some(n) => n,")
	g.P(indent, "        None => continue,")
	g.P(indent, "    };")
	g.P(indent, "    let mut raw_bytes = [0u8; 8];")
	g.P(indent, "    raw_bytes.copy_from_slice(&fkv.value()[..8]);")
	g.P(indent, "    let raw_u64 = u64::from_le_bytes(raw_bytes);")
	g.P(indent, "    match field_num {")
	for _, f := range msg.Fields {
		if f.Mutation != ir.MutationNone {
			g.P(indent, "        ", f.Number, " => entity.", FieldIdent(f), " = ", decodeAtomicRustExpr("raw_u64", f), ",")
		}
	}
	g.P(indent, "        _ => {}")
	g.P(indent, "    }")
	g.P(indent, "}")
}

// FieldRustType returns the owned Rust field type emitted by prost for a Protobuf field.
func FieldRustType(f ir.FieldSpec) string {
	switch f.Kind {
	case ir.KindInt32, ir.KindSint32, ir.KindSfixed32, ir.KindEnum:
		return "i32"
	case ir.KindUint32, ir.KindFixed32:
		return "u32"
	case ir.KindInt64, ir.KindSint64, ir.KindSfixed64:
		return "i64"
	case ir.KindUint64, ir.KindFixed64:
		return "u64"
	case ir.KindFloat:
		return "f32"
	case ir.KindDouble:
		return "f64"
	case ir.KindString:
		return "String"
	case ir.KindBool:
		return "bool"
	case ir.KindBytes:
		return "Vec<u8>"
	default:
		return "Vec<u8>"
	}
}

// FieldRustParamType returns the parameter Rust type for method signatures.
func FieldRustParamType(f ir.FieldSpec) string {
	if f.Kind == ir.KindString {
		return "&str"
	}
	if f.Kind == ir.KindBytes {
		return "&[u8]"
	}
	return FieldRustType(f)
}

// PackField normalizes a Rust expression for FDB tuple packing to ensure 100% binary
// compatibility with Go's PackField (signed ints/enums -> i64, unsigned ints -> u64,
// bytes -> fdb_layer::Bytes (0x01 byte string)).
func PackField(expr string, f ir.FieldSpec) string {
	if f.IsUnsigned || f.Kind == ir.KindUint32 || f.Kind == ir.KindFixed32 || f.Kind == ir.KindUint64 || f.Kind == ir.KindFixed64 {
		return fmt.Sprintf("(%s as u64)", expr)
	}
	if f.IsEnum || f.Kind == ir.KindEnum || f.Kind == ir.KindInt32 || f.Kind == ir.KindSint32 || f.Kind == ir.KindSfixed32 || f.Kind == ir.KindInt64 || f.Kind == ir.KindSint64 || f.Kind == ir.KindSfixed64 {
		return fmt.Sprintf("(%s as i64)", expr)
	}
	if f.Kind == ir.KindBytes {
		clean := strings.TrimPrefix(expr, "&")
		return fmt.Sprintf("fdb_layer::Bytes::from(&%s[..])", clean)
	}
	if f.Kind == ir.KindString {
		if strings.HasPrefix(expr, "&") {
			return expr
		}
		return "&" + expr
	}
	return expr
}

// MutationEnumVariant returns the foundationdb::options::MutationType variant name.
func MutationEnumVariant(m ir.MutationType) string {
	switch m {
	case ir.MutationAdd:
		return "Add"
	case ir.MutationMax:
		return "Max"
	case ir.MutationMin:
		return "Min"
	default:
		return "Add"
	}
}

// HasNonRepeatedFields returns true if any field in fields is non-repeated.
func HasNonRepeatedFields(fields []ir.FieldSpec) bool {
	for _, f := range fields {
		if !f.IsRepeated {
			return true
		}
	}
	return false
}

// NonRepeatedFieldsEqual returns a Rust boolean expression comparing all non-repeated fields.
func NonRepeatedFieldsEqual(fields []ir.FieldSpec) string {
	var parts []string
	for _, f := range fields {
		if !f.IsRepeated {
			ident := FieldIdent(f)
			parts = append(parts, fmt.Sprintf("old.%s == entity.%s", ident, ident))
		}
	}
	return strings.Join(parts, " && ")
}

func pkRustTypeExpr(msg ir.MessageSpec) string {
	if len(msg.PrimaryKeyFields) == 1 {
		return FieldRustParamType(msg.PrimaryKeyFields[0])
	}
	if len(msg.PrimaryKeyFields) > 1 {
		return msg.Name + "PrimaryKey"
	}
	return "()"
}

func pkTupleArgsFromEntity(msg ir.MessageSpec, varName string) string {
	parts := make([]string, 0, len(msg.PrimaryKeyFields))
	for _, f := range msg.PrimaryKeyFields {
		ident := FieldIdent(f)
		parts = append(parts, PackField(fmt.Sprintf("%s.%s", varName, ident), f))
	}
	return strings.Join(parts, ", ")
}

func pkTupleArgsFromParam(msg ir.MessageSpec) string {
	if len(msg.PrimaryKeyFields) == 1 {
		f := msg.PrimaryKeyFields[0]
		if f.Kind == ir.KindString {
			return "pk"
		}
		return PackField("pk", f)
	}
	parts := make([]string, 0, len(msg.PrimaryKeyFields))
	for _, f := range msg.PrimaryKeyFields {
		ident := FieldIdent(f)
		parts = append(parts, PackField("pk."+ident, f))
	}
	return strings.Join(parts, ", ")
}

func versionstampedPKTupleArgs(msg ir.MessageSpec) string {
	parts := make([]string, 0, len(msg.PrimaryKeyFields))
	for _, f := range msg.PrimaryKeyFields {
		if f.IsVersionstamp {
			parts = append(parts, "fdb_layer::Versionstamp::incomplete(self.store.next_user_version())")
		} else {
			ident := FieldIdent(f)
			parts = append(parts, PackField("entity."+ident, f))
		}
	}
	return strings.Join(parts, ", ")
}

func indexFieldTupleArgs(fields []ir.FieldSpec, varName string) string {
	parts := make([]string, 0, len(fields))
	for _, f := range fields {
		ident := FieldIdent(f)
		parts = append(parts, PackField(fmt.Sprintf("%s.%s", varName, ident), f))
	}
	return strings.Join(parts, ", ")
}

func fieldRustParamDecls(fields []ir.FieldSpec) string {
	parts := make([]string, 0, len(fields))
	for _, f := range fields {
		ident := FieldIdent(f)
		parts = append(parts, fmt.Sprintf("%s: %s", ident, FieldRustParamType(f)))
	}
	return strings.Join(parts, ", ")
}

func emitFanOutIndexWrite(g Printer, msg ir.MessageSpec, idx ir.SecondaryIndexSpec, repeatedIdx int, varName string, isSet bool, indent string) {
	var args []string
	args = append(args, "type_id", "fdb_layer::INDEX_NAMESPACE", fmt.Sprintf("%di64", idx.IndexID))
	for j, sf := range idx.Fields {
		if j == repeatedIdx {
			if sf.Kind == ir.KindString {
				args = append(args, "item")
			} else if sf.Kind == ir.KindBytes {
				args = append(args, PackField("item", sf))
			} else {
				args = append(args, PackField("*item", sf))
			}
		} else {
			ident := FieldIdent(sf)
			args = append(args, PackField(varName+"."+ident, sf))
		}
	}
	for _, pkf := range msg.PrimaryKeyFields {
		ident := FieldIdent(pkf)
		args = append(args, PackField(varName+"."+ident, pkf))
	}
	tupleExpr := strings.Join(args, ", ")
	if isSet {
		g.P(indent, "tr.set(&dir.pack(&(", tupleExpr, ")), &[]);")
	} else {
		g.P(indent, "tr.clear(&dir.pack(&(", tupleExpr, ")));")
	}
}

// JoinFieldNamesSnake joins field names in snake_case with "_and_".
func JoinFieldNamesSnake(fields []ir.FieldSpec) string {
	names := make([]string, 0, len(fields))
	for _, f := range fields {
		names = append(names, FieldSnake(f))
	}
	return strings.Join(names, "_and_")
}

// SnakeCase converts a CamelCase or snake_case identifier into snake_case.
func SnakeCase(s string) string {
	if s == "" {
		return ""
	}
	var out strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if unicode.IsUpper(r) {
			if i > 0 && runes[i-1] != '_' && (unicode.IsLower(runes[i-1]) || (i+1 < len(runes) && unicode.IsLower(runes[i+1]))) {
				out.WriteByte('_')
			}
			out.WriteRune(unicode.ToLower(r))
		} else {
			out.WriteRune(r)
		}
	}
	return out.String()
}

var rustKeywords = map[string]bool{
	"as": true, "async": true, "await": true, "break": true, "const": true,
	"continue": true, "crate": true, "dyn": true, "else": true, "enum": true,
	"extern": true, "false": true, "fn": true, "for": true, "if": true,
	"impl": true, "in": true, "let": true, "loop": true, "match": true,
	"mod": true, "move": true, "mut": true, "pub": true, "ref": true,
	"return": true, "self": true, "Self": true, "static": true, "struct": true,
	"super": true, "trait": true, "true": true, "type": true, "unsafe": true,
	"use": true, "where": true, "while": true,
}

// RustIdent escapes Rust reserved words with `r#`.
func RustIdent(s string) string {
	if rustKeywords[s] {
		return "r#" + s
	}
	return s
}
