// Code generated by protoc-gen-fdb-go. DO NOT EDIT.
// Source: github.com/romannikov/fdb-layer/tests/go/store

package store

import (
	"bytes"
	"context"
	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	fdblayer "github.com/romannikov/fdb-layer/runtimes/go"
	"google.golang.org/protobuf/proto"
)

// OrderPaginationOptions represents options for paginated queries
type OrderPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// OrderPaginatedResult represents a paginated result set
type OrderPaginatedResult struct {
	Items   []*Order
	NextKey tuple.Tuple
	HasMore bool
}

// OrderPrimaryKey represents the compound primary key for Order.
type OrderPrimaryKey struct {
	TenantId string
	OrderSeq int32
}

// OrderRepository defines the repository interface for Order.
type OrderRepository interface {
	fdblayer.GenericRepository[*Order, OrderPrimaryKey]

	BatchGetOrder(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Order, error)
	ListOrder(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts OrderPaginationOptions) (*OrderPaginatedResult, error)
	GetOrderByStatusAndCreatedAt(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, Status OrderStatus, CreatedAt int64) ([]*Order, error)
	GetOrderByReceiptHash(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ReceiptHash []byte) ([]*Order, error)
	GetOrderByAttachmentHashes(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, AttachmentHashes []byte) ([]*Order, error)
}

type orderRepository struct {
	store *fdblayer.RecordStore
}

// NewOrderRepository creates a new OrderRepository instance.
func NewOrderRepository(store *fdblayer.RecordStore) OrderRepository {
	return &orderRepository{store: store}
}

// Create creates a new Order entity in the database.
func (r *orderRepository) Create(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *Order) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Order")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, entity.TenantId, int64(entity.OrderSeq)})
	if existing := tr.Get(key).MustGet(); existing != nil {
		return fmt.Errorf("order %w", fdblayer.ErrAlreadyExists)
	}

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	tr.Set(key, value)

	// Standard index
	tr.Set(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 1001, int64(entity.Status), int64(entity.CreatedAt), entity.TenantId, int64(entity.OrderSeq)}), []byte{})

	// Standard index
	tr.Set(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 4117767939, entity.ReceiptHash, entity.TenantId, int64(entity.OrderSeq)}), []byte{})

	// Fan-out index
	for _, item := range entity.AttachmentHashes {
		tr.Set(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 1605301564,
			item,
			entity.TenantId,
			int64(entity.OrderSeq),
		}), []byte{})
	}

	return nil
}

// Get retrieves a Order entity by its primary key.
func (r *orderRepository) Get(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, pk OrderPrimaryKey) (*Order, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Order")
	if err != nil {
		return nil, err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, pk.TenantId, int64(pk.OrderSeq)})
	valueFuture := tr.Get(key)
	value := valueFuture.MustGet()
	if value == nil {
		return nil, fmt.Errorf("order not found")
	}
	entity := &Order{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}

	return entity, nil
}

// Set updates an existing Order entity in the database.
func (r *orderRepository) Set(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *Order) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Order")
	if err != nil {
		return err
	}

	var old *Order

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, entity.TenantId, int64(entity.OrderSeq)})

	if oldValue := tr.Get(key).MustGet(); oldValue != nil {
		var unmarshaled Order
		if err := proto.Unmarshal(oldValue, &unmarshaled); err != nil {
			return fmt.Errorf("failed to unmarshal existing order: %w", err)
		}
		old = &unmarshaled
	}

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	tr.Set(key, value)

	// Standard index
	if old == nil || old.Status != entity.Status || old.CreatedAt != entity.CreatedAt {
		if old != nil {
			tr.Clear(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 1001, int64(old.Status), int64(old.CreatedAt), old.TenantId, int64(old.OrderSeq)}))
		}
		tr.Set(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 1001, int64(entity.Status), int64(entity.CreatedAt), entity.TenantId, int64(entity.OrderSeq)}), []byte{})
	}

	// Standard index
	if old == nil || !bytes.Equal(old.ReceiptHash, entity.ReceiptHash) {
		if old != nil {
			tr.Clear(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 4117767939, old.ReceiptHash, old.TenantId, int64(old.OrderSeq)}))
		}
		tr.Set(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 4117767939, entity.ReceiptHash, entity.TenantId, int64(entity.OrderSeq)}), []byte{})
	}

	// Fan-out index
	if old != nil {
		oldSet := make(map[string]struct{}, len(old.AttachmentHashes))
		for _, item := range old.AttachmentHashes {
			oldSet[string(item)] = struct{}{}
		}
		newSet := make(map[string]struct{}, len(entity.AttachmentHashes))
		for _, item := range entity.AttachmentHashes {
			newSet[string(item)] = struct{}{}
		}
		for _, item := range old.AttachmentHashes {
			if _, keep := newSet[string(item)]; !keep {
				tr.Clear(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 1605301564,
					item,
					old.TenantId,
					int64(old.OrderSeq),
				}))
			}
		}
		for _, item := range entity.AttachmentHashes {
			if _, existed := oldSet[string(item)]; !existed {
				tr.Set(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 1605301564,
					item,
					entity.TenantId,
					int64(entity.OrderSeq),
				}), []byte{})
			}
		}
	} else {
		for _, item := range entity.AttachmentHashes {
			tr.Set(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 1605301564,
				item,
				entity.TenantId,
				int64(entity.OrderSeq),
			}), []byte{})
		}
	}

	return nil
}

// Delete removes a Order entity from the database.
func (r *orderRepository) Delete(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, pk OrderPrimaryKey) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Order")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, pk.TenantId, int64(pk.OrderSeq)})
	value := tr.Get(key).MustGet()
	if value != nil {
		entity := &Order{}
		if err := proto.Unmarshal(value, entity); err != nil {
			return fmt.Errorf("failed to unmarshal existing order: %w", err)
		}
		// Standard index
		tr.Clear(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 1001, int64(entity.Status), int64(entity.CreatedAt), entity.TenantId, int64(entity.OrderSeq)}))
		// Standard index
		tr.Clear(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 4117767939, entity.ReceiptHash, entity.TenantId, int64(entity.OrderSeq)}))
		// Fan-out index
		for _, item := range entity.AttachmentHashes {
			tr.Clear(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 1605301564,
				item,
				entity.TenantId,
				int64(entity.OrderSeq),
			}))
		}
	}
	tr.Clear(key)

	return nil
}

// BatchGetOrder retrieves multiple Order entities by their primary keys.
func (r *orderRepository) BatchGetOrder(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Order, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Order")
	if err != nil {
		return nil, err
	}

	result := make(map[string]*Order)
	futures := make([]fdb.FutureByteSlice, len(ids))

	for i, id := range ids {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		keyTpl := make(tuple.Tuple, 2+len(id))
		keyTpl[0] = typeID
		keyTpl[1] = fdblayer.DataNamespace
		copy(keyTpl[2:], id)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}

	for i, future := range futures {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Order{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		result[ids[i].String()] = entity
	}

	return result, nil
}

// ListOrder retrieves a list of Order entities starting from the given key.
func (r *orderRepository) ListOrder(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts OrderPaginationOptions) (*OrderPaginatedResult, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Order")
	if err != nil {
		return nil, err
	}

	result := &OrderPaginatedResult{
		Items: make([]*Order, 0),
	}

	beginTpl := make(tuple.Tuple, 2+len(opts.Begin))
	beginTpl[0] = typeID
	beginTpl[1] = fdblayer.DataNamespace
	copy(beginTpl[2:], opts.Begin)
	begin := dir.Pack(beginTpl)

	// Scan only data keys under typeID namespace.
	dataPrefix := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace})
	dataPrefixRange, err := fdb.PrefixRange(dataPrefix)
	if err != nil {
		return nil, err
	}

	rangeOpts := fdb.RangeOptions{
		Reverse: false,
	}
	if opts.Limit > 0 {
		rangeOpts.Limit = opts.Limit + 1
	}

	kvs := fdblayer.GetRange(tr, fdb.KeyRange{
		Begin: begin,
		End:   dataPrefixRange.End,
	}, rangeOpts).GetSliceOrPanic()

	var nextKey fdb.Key
	for _, kv := range kvs {
		if err := ctx.Err(); err != nil {
			return nil, err
		}

		entity := &Order{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if opts.Limit > 0 && len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = opts.Limit > 0 && len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID and DataNamespace to return just the PK tuple
		result.NextKey = tpl[2:]
		result.Items = result.Items[:opts.Limit]
	}

	return result, nil
}

// GetOrderByStatusAndCreatedAt retrieves Order entities by their StatusAndCreatedAt index.
func (r *orderRepository) GetOrderByStatusAndCreatedAt(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, Status OrderStatus, CreatedAt int64) ([]*Order, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Order")
	if err != nil {
		return nil, err
	}

	entities := []*Order{}
	indexKeyPrefix := dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 1001, int64(Status), int64(CreatedAt)})
	indexRange, err := fdb.PrefixRange(indexKeyPrefix)
	if err != nil {
		return nil, err
	}
	kvs := fdblayer.GetRange(tr, indexRange, fdb.RangeOptions{}).GetSliceOrPanic()
	futures := make([]fdb.FutureByteSlice, len(kvs))
	for i, kv := range kvs {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, err
		}
		pkIndexStart := 3 + 2
		if len(tpl) <= pkIndexStart {
			continue
		}
		pkTuple := tpl[pkIndexStart:]
		keyTpl := make(tuple.Tuple, 2+len(pkTuple))
		keyTpl[0] = typeID
		keyTpl[1] = fdblayer.DataNamespace
		copy(keyTpl[2:], pkTuple)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}
	for _, future := range futures {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		if future == nil {
			continue
		}
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Order{}
		err = proto.Unmarshal(value, entity)
		if err != nil {
			return nil, err
		}
		entities = append(entities, entity)
	}
	return entities, nil
}

// GetOrderByReceiptHash retrieves Order entities by their ReceiptHash index.
func (r *orderRepository) GetOrderByReceiptHash(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ReceiptHash []byte) ([]*Order, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Order")
	if err != nil {
		return nil, err
	}

	entities := []*Order{}
	indexKeyPrefix := dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 4117767939, ReceiptHash})
	indexRange, err := fdb.PrefixRange(indexKeyPrefix)
	if err != nil {
		return nil, err
	}
	kvs := fdblayer.GetRange(tr, indexRange, fdb.RangeOptions{}).GetSliceOrPanic()
	futures := make([]fdb.FutureByteSlice, len(kvs))
	for i, kv := range kvs {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, err
		}
		pkIndexStart := 3 + 1
		if len(tpl) <= pkIndexStart {
			continue
		}
		pkTuple := tpl[pkIndexStart:]
		keyTpl := make(tuple.Tuple, 2+len(pkTuple))
		keyTpl[0] = typeID
		keyTpl[1] = fdblayer.DataNamespace
		copy(keyTpl[2:], pkTuple)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}
	for _, future := range futures {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		if future == nil {
			continue
		}
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Order{}
		err = proto.Unmarshal(value, entity)
		if err != nil {
			return nil, err
		}
		entities = append(entities, entity)
	}
	return entities, nil
}

// GetOrderByAttachmentHashes retrieves Order entities by their AttachmentHashes index.
func (r *orderRepository) GetOrderByAttachmentHashes(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, AttachmentHashes []byte) ([]*Order, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Order")
	if err != nil {
		return nil, err
	}

	entities := []*Order{}
	indexKeyPrefix := dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 1605301564, AttachmentHashes})
	indexRange, err := fdb.PrefixRange(indexKeyPrefix)
	if err != nil {
		return nil, err
	}
	kvs := fdblayer.GetRange(tr, indexRange, fdb.RangeOptions{}).GetSliceOrPanic()
	futures := make([]fdb.FutureByteSlice, len(kvs))
	for i, kv := range kvs {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, err
		}
		pkIndexStart := 3 + 1
		if len(tpl) <= pkIndexStart {
			continue
		}
		pkTuple := tpl[pkIndexStart:]
		keyTpl := make(tuple.Tuple, 2+len(pkTuple))
		keyTpl[0] = typeID
		keyTpl[1] = fdblayer.DataNamespace
		copy(keyTpl[2:], pkTuple)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}
	for _, future := range futures {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		if future == nil {
			continue
		}
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Order{}
		err = proto.Unmarshal(value, entity)
		if err != nil {
			return nil, err
		}
		entities = append(entities, entity)
	}
	return entities, nil
}
