// Code generated by protoc-gen-fdb-go. DO NOT EDIT.
// Source: github.com/romannikov/fdb-layer/tests/go/store

package store

import (
	"context"
	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	fdblayer "github.com/romannikov/fdb-layer/runtimes/go"
	"google.golang.org/protobuf/proto"
)

// AuditLogPaginationOptions represents options for paginated queries
type AuditLogPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// AuditLogPaginatedResult represents a paginated result set
type AuditLogPaginatedResult struct {
	Items   []*AuditLog
	NextKey tuple.Tuple
	HasMore bool
}

// AuditLogRepository defines the repository interface for AuditLog.
type AuditLogRepository interface {
	fdblayer.GenericRepository[*AuditLog, []byte]

	BatchGetAuditLog(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*AuditLog, error)
	ListAuditLog(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts AuditLogPaginationOptions) (*AuditLogPaginatedResult, error)
}

type auditlogRepository struct {
	store *fdblayer.RecordStore
}

// NewAuditLogRepository creates a new AuditLogRepository instance.
func NewAuditLogRepository(store *fdblayer.RecordStore) AuditLogRepository {
	return &auditlogRepository{store: store}
}

// Create creates a new AuditLog entity in the database.
func (r *auditlogRepository) Create(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *AuditLog) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("AuditLog")
	if err != nil {
		return err
	}

	key, err := dir.PackWithVersionstamp(tuple.Tuple{typeID, fdblayer.DataNamespace, tuple.IncompleteVersionstamp(r.store.NextUserVersion())})
	if err != nil {
		return err
	}

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	tr.SetVersionstampedKey(key, value)

	return nil
}

// Get retrieves a AuditLog entity by its primary key.
func (r *auditlogRepository) Get(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, pk []byte) (*AuditLog, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("AuditLog")
	if err != nil {
		return nil, err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, fdblayer.BytesToVersionstamp(pk)})
	valueFuture := tr.Get(key)
	value := valueFuture.MustGet()
	if value == nil {
		return nil, fmt.Errorf("auditlog not found")
	}
	entity := &AuditLog{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}

	if tpl, unpackErr := dir.Unpack(key); unpackErr == nil {
		if len(tpl) > 0+2 {
			if vs, ok := tpl[0+2].(tuple.Versionstamp); ok {
				entity.LogId = vs.Bytes()
			}
		}
	}
	return entity, nil
}

// Set updates an existing AuditLog entity in the database.
func (r *auditlogRepository) Set(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *AuditLog) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("AuditLog")
	if err != nil {
		return err
	}

	// If the entity already has a versionstamp, delete the old versionstamped record.
	// (Since the primary key contains the versionstamp, an update changes the key itself).
	hasOldVS := false
	for _, b := range entity.LogId {
		if b != 0 {
			hasOldVS = true
			break
		}
	}
	if hasOldVS {
		oldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, fdblayer.BytesToVersionstamp(entity.LogId)})
		tr.Clear(oldKey)
	}

	key, err := dir.PackWithVersionstamp(tuple.Tuple{typeID, fdblayer.DataNamespace, tuple.IncompleteVersionstamp(r.store.NextUserVersion())})
	if err != nil {
		return err
	}

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	tr.SetVersionstampedKey(key, value)

	return nil
}

// Delete removes a AuditLog entity from the database.
func (r *auditlogRepository) Delete(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, pk []byte) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("AuditLog")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, fdblayer.BytesToVersionstamp(pk)})
	tr.Clear(key)

	return nil
}

// BatchGetAuditLog retrieves multiple AuditLog entities by their primary keys.
func (r *auditlogRepository) BatchGetAuditLog(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*AuditLog, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("AuditLog")
	if err != nil {
		return nil, err
	}

	result := make(map[string]*AuditLog)
	futures := make([]fdb.FutureByteSlice, len(ids))

	for i, id := range ids {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		keyTpl := make(tuple.Tuple, 2+len(id))
		keyTpl[0] = typeID
		keyTpl[1] = fdblayer.DataNamespace
		copy(keyTpl[2:], id)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}

	for i, future := range futures {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &AuditLog{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		result[ids[i].String()] = entity
	}

	return result, nil
}

// ListAuditLog retrieves a list of AuditLog entities starting from the given key.
func (r *auditlogRepository) ListAuditLog(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts AuditLogPaginationOptions) (*AuditLogPaginatedResult, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("AuditLog")
	if err != nil {
		return nil, err
	}

	result := &AuditLogPaginatedResult{
		Items: make([]*AuditLog, 0),
	}

	beginTpl := make(tuple.Tuple, 2+len(opts.Begin))
	beginTpl[0] = typeID
	beginTpl[1] = fdblayer.DataNamespace
	copy(beginTpl[2:], opts.Begin)
	begin := dir.Pack(beginTpl)

	// Scan only data keys under typeID namespace.
	dataPrefix := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace})
	dataPrefixRange, err := fdb.PrefixRange(dataPrefix)
	if err != nil {
		return nil, err
	}

	rangeOpts := fdb.RangeOptions{
		Reverse: false,
	}
	if opts.Limit > 0 {
		rangeOpts.Limit = opts.Limit + 1
	}

	kvs := fdblayer.GetRange(tr, fdb.KeyRange{
		Begin: begin,
		End:   dataPrefixRange.End,
	}, rangeOpts).GetSliceOrPanic()

	var nextKey fdb.Key
	for _, kv := range kvs {
		if err := ctx.Err(); err != nil {
			return nil, err
		}

		entity := &AuditLog{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		if tpl, unpackErr := dir.Unpack(kv.Key); unpackErr == nil {
			if len(tpl) > 0+2 {
				if vs, ok := tpl[0+2].(tuple.Versionstamp); ok {
					entity.LogId = vs.Bytes()
				}
			}
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if opts.Limit > 0 && len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = opts.Limit > 0 && len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID and DataNamespace to return just the PK tuple
		result.NextKey = tpl[2:]
		result.Items = result.Items[:opts.Limit]
	}

	return result, nil
}
