// Code generated by protoc-gen-fdb-go. DO NOT EDIT.
// Source: github.com/romannikov/fdb-layer/tests/go/store

package store

import (
	"context"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	fdblayer "github.com/romannikov/fdb-layer/runtimes/go"
	"google.golang.org/protobuf/proto"
)

// TaskMessageRepository defines the repository interface for the TaskMessage queue.
type TaskMessageRepository interface {
	Enqueue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, msg *TaskMessage) error
	Dequeue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, queuename string) (*TaskMessage, error)
}

type taskmessageRepository struct {
	store *fdblayer.RecordStore
}

// NewTaskMessageRepository creates a new TaskMessageRepository instance.
func NewTaskMessageRepository(store *fdblayer.RecordStore) TaskMessageRepository {
	return &taskmessageRepository{store: store}
}

// Enqueue adds a TaskMessage to the queue.
func (r *taskmessageRepository) Enqueue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *TaskMessage) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("TaskMessage")
	if err != nil {
		return err
	}

	key, err := dir.PackWithVersionstamp(tuple.Tuple{typeID, fdblayer.DataNamespace, entity.QueueName, tuple.IncompleteVersionstamp(r.store.NextUserVersion()), uint64(entity.ShardId)})
	if err != nil {
		return err
	}

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	tr.SetVersionstampedKey(key, value)

	return nil
}

// Dequeue reads and removes the single oldest message from the queue.
func (r *taskmessageRepository) Dequeue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, queuename string) (*TaskMessage, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("TaskMessage")
	if err != nil {
		return nil, err
	}

	prefixTuple := tuple.Tuple{typeID, fdblayer.DataNamespace, queuename}
	prefixRange, err := fdb.PrefixRange(dir.Pack(prefixTuple))
	if err != nil {
		return nil, err
	}

	options := fdb.RangeOptions{Limit: 1}
	rows := fdblayer.GetRange(tr, prefixRange, options).GetSliceOrPanic()

	if len(rows) == 0 {
		return nil, nil
	}

	firstItem := rows[0]
	keyToDelete := firstItem.Key
	payload := firstItem.Value

	tr.Clear(keyToDelete)

	entity := &TaskMessage{}
	err = proto.Unmarshal(payload, entity)
	if err != nil {
		return nil, err
	}

	if tpl, unpackErr := dir.Unpack(keyToDelete); unpackErr == nil {
		if len(tpl) > 1+2 {
			if vs, ok := tpl[1+2].(tuple.Versionstamp); ok {
				entity.Versionstamp = vs.Bytes()
			}
		}
	}

	return entity, nil
}
