// Code generated by protoc-gen-fdb-go. DO NOT EDIT.
// Source: github.com/romannikov/fdb-layer/tests/go/atomic

package atomic

import (
	"context"
	"encoding/binary"
	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	fdblayer "github.com/romannikov/fdb-layer/runtimes/go"
	"google.golang.org/protobuf/proto"
)

// CounterPaginationOptions represents options for paginated queries
type CounterPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// CounterPaginatedResult represents a paginated result set
type CounterPaginatedResult struct {
	Items   []*Counter
	NextKey tuple.Tuple
	HasMore bool
}

// CounterRepository defines the repository interface for Counter.
type CounterRepository interface {
	fdblayer.GenericRepository[*Counter, string]

	BatchGetCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Counter, error)
	ListCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts CounterPaginationOptions) (*CounterPaginatedResult, error)
	AddCounterValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error
	MaxCounterMaxValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error
	MinCounterMinValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error
}

type counterRepository struct {
	store *fdblayer.RecordStore
}

// NewCounterRepository creates a new CounterRepository instance.
func NewCounterRepository(store *fdblayer.RecordStore) CounterRepository {
	return &counterRepository{store: store}
}

// Create creates a new Counter entity in the database.
func (r *counterRepository) Create(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *Counter) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, entity.Id})
	if existing := tr.Get(key).MustGet(); existing != nil {
		return fmt.Errorf("counter %w", fdblayer.ErrAlreadyExists)
	}

	// Save atomic fields and zero them out for marshaling
	atomic_Value := entity.Value
	entity.Value = 0
	atomic_MaxValue := entity.MaxValue
	entity.MaxValue = 0
	atomic_MinValue := entity.MinValue
	entity.MinValue = 0

	value, err := proto.Marshal(entity)
	// Restore atomic fields
	entity.Value = atomic_Value
	entity.MaxValue = atomic_MaxValue
	entity.MinValue = atomic_MinValue
	if err != nil {
		return err
	}

	tr.Set(key, value)

	// Store non-zero initial atomic fields in separate keys
	if atomic_Value != 0 {
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 2})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_Value))
		tr.Add(fieldKey, buf)
	}
	if atomic_MaxValue != 0 {
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 3})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MaxValue)^(1<<63))
		tr.Max(fieldKey, buf)
	}
	if atomic_MinValue != 0 {
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 4})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MinValue)^(1<<63))
		tr.Min(fieldKey, buf)
	}

	return nil
}

// Get retrieves a Counter entity by its primary key.
func (r *counterRepository) Get(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, pk string) (*Counter, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return nil, err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, pk})
	valueFuture := tr.Get(key)
	// Issue a single prefix range read for all atomic fields concurrently with the primary record read
	fieldPrefixRange, err := fdb.PrefixRange(dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, pk}))
	if err != nil {
		return nil, err
	}
	fieldFuture := fdblayer.GetRange(tr, fieldPrefixRange, fdb.RangeOptions{})
	value := valueFuture.MustGet()
	if value == nil {
		return nil, fmt.Errorf("counter not found")
	}
	entity := &Counter{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}

	for _, fkv := range fieldFuture.GetSliceOrPanic() {
		if len(fkv.Value) < 8 {
			continue
		}
		ftpl, err := dir.Unpack(fkv.Key)
		if err != nil || len(ftpl) == 0 {
			continue
		}
		fieldNum, ok := ftpl[len(ftpl)-1].(int64)
		if !ok {
			continue
		}
		switch fieldNum {
		case 2:
			entity.Value = int64(binary.LittleEndian.Uint64(fkv.Value))
		case 3:
			entity.MaxValue = int64(binary.LittleEndian.Uint64(fkv.Value) ^ (1 << 63))
		case 4:
			entity.MinValue = int64(binary.LittleEndian.Uint64(fkv.Value) ^ (1 << 63))
		}
	}
	return entity, nil
}

// Set updates an existing Counter entity in the database.
func (r *counterRepository) Set(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *Counter) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, entity.Id})

	// Save atomic fields and zero them out for marshaling
	atomic_Value := entity.Value
	entity.Value = 0
	atomic_MaxValue := entity.MaxValue
	entity.MaxValue = 0
	atomic_MinValue := entity.MinValue
	entity.MinValue = 0

	value, err := proto.Marshal(entity)
	// Restore atomic fields
	entity.Value = atomic_Value
	entity.MaxValue = atomic_MaxValue
	entity.MinValue = atomic_MinValue
	if err != nil {
		return err
	}

	tr.Set(key, value)

	return nil
}

// Delete removes a Counter entity from the database.
func (r *counterRepository) Delete(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, pk string) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, pk})
	tr.Clear(key)

	// Clear atomic fields
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, pk, 2})
		tr.Clear(fieldKey)
	}
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, pk, 3})
		tr.Clear(fieldKey)
	}
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, pk, 4})
		tr.Clear(fieldKey)
	}
	return nil
}

// BatchGetCounter retrieves multiple Counter entities by their primary keys.
func (r *counterRepository) BatchGetCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Counter, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return nil, err
	}

	result := make(map[string]*Counter)
	futures := make([]fdb.FutureByteSlice, len(ids))
	fieldFutures := make([]fdblayer.RangeFuture, len(ids))

	for i, id := range ids {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		keyTpl := make(tuple.Tuple, 2+len(id))
		keyTpl[0] = typeID
		keyTpl[1] = fdblayer.DataNamespace
		copy(keyTpl[2:], id)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
		fieldTpl := make(tuple.Tuple, 2+len(id))
		fieldTpl[0] = typeID
		fieldTpl[1] = fdblayer.FieldNamespace
		copy(fieldTpl[2:], id)
		fieldRange, err := fdb.PrefixRange(dir.Pack(fieldTpl))
		if err != nil {
			return nil, err
		}
		fieldFutures[i] = fdblayer.GetRange(tr, fieldRange, fdb.RangeOptions{})
	}

	for i, future := range futures {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Counter{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		for _, fkv := range fieldFutures[i].GetSliceOrPanic() {
			if len(fkv.Value) < 8 {
				continue
			}
			ftpl, err := dir.Unpack(fkv.Key)
			if err != nil || len(ftpl) == 0 {
				continue
			}
			fieldNum, ok := ftpl[len(ftpl)-1].(int64)
			if !ok {
				continue
			}
			switch fieldNum {
			case 2:
				entity.Value = int64(binary.LittleEndian.Uint64(fkv.Value))
			case 3:
				entity.MaxValue = int64(binary.LittleEndian.Uint64(fkv.Value) ^ (1 << 63))
			case 4:
				entity.MinValue = int64(binary.LittleEndian.Uint64(fkv.Value) ^ (1 << 63))
			}
		}
		result[ids[i].String()] = entity
	}

	return result, nil
}

// ListCounter retrieves a list of Counter entities starting from the given key.
func (r *counterRepository) ListCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts CounterPaginationOptions) (*CounterPaginatedResult, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return nil, err
	}

	result := &CounterPaginatedResult{
		Items: make([]*Counter, 0),
	}

	beginTpl := make(tuple.Tuple, 2+len(opts.Begin))
	beginTpl[0] = typeID
	beginTpl[1] = fdblayer.DataNamespace
	copy(beginTpl[2:], opts.Begin)
	begin := dir.Pack(beginTpl)

	// Scan only data keys under typeID namespace.
	dataPrefix := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace})
	dataPrefixRange, err := fdb.PrefixRange(dataPrefix)
	if err != nil {
		return nil, err
	}

	rangeOpts := fdb.RangeOptions{
		Reverse: false,
	}
	if opts.Limit > 0 {
		rangeOpts.Limit = opts.Limit + 1
	}

	iter := tr.GetRange(fdb.KeyRange{
		Begin: begin,
		End:   dataPrefixRange.End,
	}, rangeOpts).Iterator()

	var nextKey fdb.Key
	for iter.Advance() {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		kv := iter.MustGet()

		entity := &Counter{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if opts.Limit > 0 && len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = opts.Limit > 0 && len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID and DataNamespace to return just the PK tuple
		result.NextKey = tpl[2:]
		result.Items = result.Items[:opts.Limit]
	}

	// Populate atomic fields for all returned items in a single range read
	if len(result.Items) > 0 {
		first := result.Items[0]
		last := result.Items[len(result.Items)-1]
		fieldBegin := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, first.Id})
		fieldEndPrefix, err := fdb.PrefixRange(dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, last.Id}))
		if err != nil {
			return nil, err
		}
		itemByPK := make(map[string]*Counter, len(result.Items))
		for _, entity := range result.Items {
			pkKey := tuple.Tuple{entity.Id}.String()
			itemByPK[pkKey] = entity
		}
		fieldKVs := fdblayer.GetRange(tr, fdb.KeyRange{Begin: fieldBegin, End: fieldEndPrefix.End}, fdb.RangeOptions{}).GetSliceOrPanic()
		pkLen := 1
		for _, fkv := range fieldKVs {
			if len(fkv.Value) < 8 {
				continue
			}
			ftpl, err := dir.Unpack(fkv.Key)
			if err != nil || len(ftpl) < 3+pkLen {
				continue
			}
			entity, ok := itemByPK[ftpl[2:2+pkLen].String()]
			if !ok {
				continue
			}
			fieldNum, ok := ftpl[2+pkLen].(int64)
			if !ok {
				continue
			}
			switch fieldNum {
			case 2:
				entity.Value = int64(binary.LittleEndian.Uint64(fkv.Value))
			case 3:
				entity.MaxValue = int64(binary.LittleEndian.Uint64(fkv.Value) ^ (1 << 63))
			case 4:
				entity.MinValue = int64(binary.LittleEndian.Uint64(fkv.Value) ^ (1 << 63))
			}
		}
	}

	return result, nil
}

// AddCounterValue applies an atomic mutation to the Value field of Counter.
func (r *counterRepository) AddCounterValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, Id, 2})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val))

	tr.Add(key, buf)
	return nil
}

// MaxCounterMaxValue applies an atomic mutation to the MaxValue field of Counter.
func (r *counterRepository) MaxCounterMaxValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, Id, 3})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val)^(1<<63))

	tr.Max(key, buf)
	return nil
}

// MinCounterMinValue applies an atomic mutation to the MinValue field of Counter.
func (r *counterRepository) MinCounterMinValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, Id, 4})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val)^(1<<63))

	tr.Min(key, buf)
	return nil
}
