// Code generated by fdb-go-layer-plugin. DO NOT EDIT.
// Source: github.com/romannikov/fdb-go-layer-plugin/tests/atomic

package atomic

import (
	"encoding/binary"
	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	"google.golang.org/protobuf/proto"
)

var _ = binary.LittleEndian

// CounterPaginationOptions represents options for paginated queries
type CounterPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// CounterPaginatedResult represents a paginated result set
type CounterPaginatedResult struct {
	Items   []*Counter
	NextKey tuple.Tuple
	HasMore bool
}

func (s *RecordStore) getCounterTypeID() (int64, error) {
	if s.metadata == nil {
		return 0, fmt.Errorf("metadata not initialized, call SyncMetadata first")
	}
	typeID, ok := s.metadata["Counter"]
	if !ok {
		return 0, fmt.Errorf("type Counter not found in metadata")
	}
	return typeID, nil
}

type CounterRepository struct {
	store *RecordStore
}

func NewCounterRepository(store *RecordStore) *CounterRepository {
	return &CounterRepository{store: store}
}

// Create creates a new Counter entity in the database.
func (r *CounterRepository) Create(tr Transaction, dir directory.DirectorySubspace, entity *Counter) error {
	typeID, err := r.store.getCounterTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Save atomic fields and zero them out for marshaling

	atomic_Value := entity.Value
	entity.Value = 0

	atomic_MaxValue := entity.MaxValue
	entity.MaxValue = 0

	atomic_MinValue := entity.MinValue
	entity.MinValue = 0

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	entity.Value = atomic_Value

	entity.MaxValue = atomic_MaxValue

	entity.MinValue = atomic_MinValue

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 2})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_Value))
		tr.Set(fieldKey, buf)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 3})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MaxValue))
		tr.Set(fieldKey, buf)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 4})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MinValue))
		tr.Set(fieldKey, buf)
	}

	return nil
}

// Get retrieves a Counter entity by its primary key.
func (r *CounterRepository) Get(tr fdb.ReadTransaction, dir directory.DirectorySubspace, key tuple.Tuple) (*Counter, error) {
	typeID, err := r.store.getCounterTypeID()
	if err != nil {
		return nil, err
	}

	Id := key[0].(string)

	fdbKey := dir.Pack(tuple.Tuple{typeID, Id})
	value := tr.Get(fdbKey).MustGet()
	if value == nil {
		return nil, fmt.Errorf("counter not found")
	}
	entity := &Counter{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}

	// Read atomic fields

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, Id, "f", 2})
		fieldVal := tr.Get(fieldKey).MustGet()
		if fieldVal != nil {
			entity.Value = int64(binary.LittleEndian.Uint64(fieldVal))
		}
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, Id, "f", 3})
		fieldVal := tr.Get(fieldKey).MustGet()
		if fieldVal != nil {
			entity.MaxValue = int64(binary.LittleEndian.Uint64(fieldVal))
		}
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, Id, "f", 4})
		fieldVal := tr.Get(fieldKey).MustGet()
		if fieldVal != nil {
			entity.MinValue = int64(binary.LittleEndian.Uint64(fieldVal))
		}
	}

	return entity, nil
}

// Set updates an existing Counter entity in the database.
func (r *CounterRepository) Set(tr Transaction, dir directory.DirectorySubspace, entity *Counter) error {
	typeID, err := r.store.getCounterTypeID()
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Clear stale index entries from the old version of the entity
	oldValue := tr.Get(key).MustGet()
	if oldValue != nil {
		old := &Counter{}
		if unmarshalErr := proto.Unmarshal(oldValue, old); unmarshalErr == nil {

		}
	}

	// Save atomic fields and zero them out for marshaling

	atomic_Value := entity.Value
	entity.Value = 0

	atomic_MaxValue := entity.MaxValue
	entity.MaxValue = 0

	atomic_MinValue := entity.MinValue
	entity.MinValue = 0

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	entity.Value = atomic_Value

	entity.MaxValue = atomic_MaxValue

	entity.MinValue = atomic_MinValue

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 2})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_Value))
		tr.Set(fieldKey, buf)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 3})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MaxValue))
		tr.Set(fieldKey, buf)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 4})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MinValue))
		tr.Set(fieldKey, buf)
	}

	return nil
}

// Delete removes a Counter entity from the database.
func (r *CounterRepository) Delete(tr Transaction, dir directory.DirectorySubspace, key tuple.Tuple) error {
	typeID, err := r.store.getCounterTypeID()
	if err != nil {
		return err
	}

	Id := key[0].(string)

	fdbKey := dir.Pack(tuple.Tuple{typeID, Id})
	value := tr.Get(fdbKey).MustGet()
	if value != nil {
		entity := &Counter{}
		err := proto.Unmarshal(value, entity)
		if err == nil {

		}
	}
	tr.Clear(fdbKey)
	// Clear atomic fields

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, Id, "f", 2})
		tr.Clear(fieldKey)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, Id, "f", 3})
		tr.Clear(fieldKey)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, Id, "f", 4})
		tr.Clear(fieldKey)
	}

	return nil
}

// AddValue applies an atomic mutation to the Value field of Counter.
func (r *CounterRepository) AddValue(tr Transaction, dir directory.DirectorySubspace, id string, val int64) error {
	typeID, err := r.store.getCounterTypeID()
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, id, "f", 2})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val))

	tr.AtomicOp(key, 2, buf)
	return nil
}

// MaxMaxValue applies an atomic mutation to the MaxValue field of Counter.
func (r *CounterRepository) MaxMaxValue(tr Transaction, dir directory.DirectorySubspace, id string, val int64) error {
	typeID, err := r.store.getCounterTypeID()
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, id, "f", 3})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val))

	tr.AtomicOp(key, 12, buf)
	return nil
}

// MinMinValue applies an atomic mutation to the MinValue field of Counter.
func (r *CounterRepository) MinMinValue(tr Transaction, dir directory.DirectorySubspace, id string, val int64) error {
	typeID, err := r.store.getCounterTypeID()
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, id, "f", 4})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val))

	tr.AtomicOp(key, 13, buf)
	return nil
}

// BatchGet retrieves multiple Counter entities by their primary keys.
func (r *CounterRepository) BatchGet(tr fdb.ReadTransaction, dir directory.DirectorySubspace, keys []tuple.Tuple) (map[string]*Counter, error) {
	typeID, err := r.store.getCounterTypeID()
	if err != nil {
		return nil, err
	}

	result := make(map[string]*Counter)
	futures := make([]fdb.FutureByteSlice, len(keys))

	for i, id := range keys {
		keyTpl := append(tuple.Tuple{typeID}, id...)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}

	for i, future := range futures {
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Counter{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		result[keys[i].String()] = entity
	}

	return result, nil
}

// List retrieves a list of Counter entities starting from the given key.
func (r *CounterRepository) List(tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts PaginationOptions) (*PaginatedResult[Counter], error) {
	typeID, err := r.store.getCounterTypeID()
	if err != nil {
		return nil, err
	}

	result := &PaginatedResult[Counter]{
		Items: make([]*Counter, 0),
	}

	beginTpl := append(tuple.Tuple{typeID}, opts.Begin...)
	begin := dir.Pack(beginTpl)

	// Scan all keys under typeID. We request extra rows to account for
	// index entries that will be filtered out.
	typePrefix := dir.Pack(tuple.Tuple{typeID})
	typePrefixRange, err := fdb.PrefixRange(typePrefix)
	if err != nil {
		return nil, err
	}

	iter := tr.GetRange(fdb.KeyRange{
		Begin: begin,
		End:   typePrefixRange.End,
	}, fdb.RangeOptions{
		Reverse: false,
	}).Iterator()

	var nextKey fdb.Key
	for iter.Advance() {
		kv := iter.MustGet()

		// Skip index entries: their second tuple element is the string "index".
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack key: %w", err)
		}
		if len(tpl) >= 2 {
			if s, ok := tpl[1].(string); ok && s == "index" {
				continue
			}
		}

		entity := &Counter{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID to return just the PK tuple
		result.NextKey = tpl[1:]
		result.Items = result.Items[:opts.Limit]
	}

	return result, nil
}
