// Code generated by fdb-go-layer-plugin. DO NOT EDIT.
// Source: github.com/romannikov/fdb-go-layer-plugin/tests/atomic

package atomic

import (
	"context"
	"encoding/binary"
	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	fdblayer "github.com/romannikov/fdb-go-layer-plugin/fdb-layer"
	"google.golang.org/protobuf/proto"
)

// CounterPaginationOptions represents options for paginated queries
type CounterPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// CounterPaginatedResult represents a paginated result set
type CounterPaginatedResult struct {
	Items   []*Counter
	NextKey tuple.Tuple
	HasMore bool
}

// CounterRepository defines the repository interface for Counter.
type CounterRepository interface {
	fdblayer.GenericRepository[*Counter, string]

	BatchGetCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Counter, error)
	ListCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts CounterPaginationOptions) (*CounterPaginatedResult, error)

	AddCounterValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error

	MaxCounterMaxValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error

	MinCounterMinValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error
}

type counterRepository struct {
	store *fdblayer.RecordStore
}

// NewCounterRepository creates a new CounterRepository instance.
func NewCounterRepository(store *fdblayer.RecordStore) CounterRepository {
	return &counterRepository{store: store}
}

// Create creates a new Counter entity in the database.
func (r *counterRepository) Create(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *Counter) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Save atomic fields and zero them out for marshaling

	atomic_Value := entity.Value
	entity.Value = 0

	atomic_MaxValue := entity.MaxValue
	entity.MaxValue = 0

	atomic_MinValue := entity.MinValue
	entity.MinValue = 0

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	entity.Value = atomic_Value

	entity.MaxValue = atomic_MaxValue

	entity.MinValue = atomic_MinValue

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 2})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_Value))
		tr.Set(fieldKey, buf)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 3})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MaxValue))
		tr.Set(fieldKey, buf)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 4})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MinValue))
		tr.Set(fieldKey, buf)
	}

	return nil
}

// Get retrieves a Counter entity by its primary key.
func (r *counterRepository) Get(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, pk string) (*Counter, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return nil, err
	}

	key := dir.Pack(tuple.Tuple{typeID, pk})
	value := tr.Get(key).MustGet()
	if value == nil {
		return nil, fmt.Errorf("counter not found")
	}
	entity := &Counter{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}

	// Read atomic fields

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, pk, "f", 2})
		fieldVal := tr.Get(fieldKey).MustGet()
		if fieldVal != nil {
			entity.Value = int64(binary.LittleEndian.Uint64(fieldVal))
		}
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, pk, "f", 3})
		fieldVal := tr.Get(fieldKey).MustGet()
		if fieldVal != nil {
			entity.MaxValue = int64(binary.LittleEndian.Uint64(fieldVal))
		}
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, pk, "f", 4})
		fieldVal := tr.Get(fieldKey).MustGet()
		if fieldVal != nil {
			entity.MinValue = int64(binary.LittleEndian.Uint64(fieldVal))
		}
	}

	return entity, nil
}

// Set updates an existing Counter entity in the database.
func (r *counterRepository) Set(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *Counter) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Clear stale index entries from the old version of the entity
	oldValue := tr.Get(key).MustGet()
	if oldValue != nil {
		old := &Counter{}
		if unmarshalErr := proto.Unmarshal(oldValue, old); unmarshalErr == nil {

		}
	}

	// Save atomic fields and zero them out for marshaling

	atomic_Value := entity.Value
	entity.Value = 0

	atomic_MaxValue := entity.MaxValue
	entity.MaxValue = 0

	atomic_MinValue := entity.MinValue
	entity.MinValue = 0

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	entity.Value = atomic_Value

	entity.MaxValue = atomic_MaxValue

	entity.MinValue = atomic_MinValue

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 2})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_Value))
		tr.Set(fieldKey, buf)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 3})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MaxValue))
		tr.Set(fieldKey, buf)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, entity.Id, "f", 4})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MinValue))
		tr.Set(fieldKey, buf)
	}

	return nil
}

// Delete removes a Counter entity from the database.
func (r *counterRepository) Delete(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, pk string) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, pk})
	value := tr.Get(key).MustGet()
	if value != nil {
		entity := &Counter{}
		err := proto.Unmarshal(value, entity)
		if err == nil {

		}
	}
	tr.Clear(key)
	// Clear atomic fields

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, pk, "f", 2})
		tr.Clear(fieldKey)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, pk, "f", 3})
		tr.Clear(fieldKey)
	}

	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, pk, "f", 4})
		tr.Clear(fieldKey)
	}

	return nil
}

// BatchGetCounter retrieves multiple Counter entities by their primary keys.
func (r *counterRepository) BatchGetCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Counter, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return nil, err
	}

	result := make(map[string]*Counter)
	futures := make([]fdb.FutureByteSlice, len(ids))

	for i, id := range ids {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		keyTpl := append(tuple.Tuple{typeID}, id...)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}

	for i, future := range futures {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Counter{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		result[ids[i].String()] = entity
	}

	return result, nil
}

// ListCounter retrieves a list of Counter entities starting from the given key.
func (r *counterRepository) ListCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts CounterPaginationOptions) (*CounterPaginatedResult, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return nil, err
	}

	result := &CounterPaginatedResult{
		Items: make([]*Counter, 0),
	}

	beginTpl := append(tuple.Tuple{typeID}, opts.Begin...)
	begin := dir.Pack(beginTpl)

	// Scan all keys under typeID. We request extra rows to account for
	// index entries that will be filtered out.
	typePrefix := dir.Pack(tuple.Tuple{typeID})
	typePrefixRange, err := fdb.PrefixRange(typePrefix)
	if err != nil {
		return nil, err
	}

	iter := tr.GetRange(fdb.KeyRange{
		Begin: begin,
		End:   typePrefixRange.End,
	}, fdb.RangeOptions{
		Reverse: false,
	}).Iterator()

	var nextKey fdb.Key
	for iter.Advance() {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		kv := iter.MustGet()

		// Skip index entries: their second tuple element is the string "index".
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack key: %w", err)
		}
		if len(tpl) >= 2 {
			if s, ok := tpl[1].(string); ok && s == "index" {
				continue
			}
		}

		entity := &Counter{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID to return just the PK tuple
		result.NextKey = tpl[1:]
		result.Items = result.Items[:opts.Limit]
	}

	return result, nil
}

// AddCounterValue applies an atomic mutation to the Value field of Counter.
func (r *counterRepository) AddCounterValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, Id, "f", 2})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val))

	tr.Add(key, buf)
	return nil
}

// MaxCounterMaxValue applies an atomic mutation to the MaxValue field of Counter.
func (r *counterRepository) MaxCounterMaxValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, Id, "f", 3})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val))

	tr.Max(key, buf)
	return nil
}

// MinCounterMinValue applies an atomic mutation to the MinValue field of Counter.
func (r *counterRepository) MinCounterMinValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, Id, "f", 4})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val))

	tr.Min(key, buf)
	return nil
}
