// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: tests/atomic/atomic.proto

package atomic

import (
	_ "github.com/romannikov/fdb-go-layer-plugin/fdb-layer"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	MaxValue      int64                  `protobuf:"varint,3,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	MinValue      int64                  `protobuf:"varint,4,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counter) Reset() {
	*x = Counter{}
	mi := &file_tests_atomic_atomic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_tests_atomic_atomic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counter.ProtoReflect.Descriptor instead.
func (*Counter) Descriptor() ([]byte, []int) {
	return file_tests_atomic_atomic_proto_rawDescGZIP(), []int{0}
}

func (x *Counter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Counter) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Counter) GetMaxValue() int64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *Counter) GetMinValue() int64 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

var File_tests_atomic_atomic_proto protoreflect.FileDescriptor

const file_tests_atomic_atomic_proto_rawDesc = "" +
	"\n" +
	"\x19tests/atomic/atomic.proto\x12\ftests.atomic\x1a\x1bfdb-layer/annotations.proto\"\x83\x01\n" +
	"\aCounter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\x05value\x18\x02 \x01(\x03B\x04\x98\xb5\x18\x01R\x05value\x12!\n" +
	"\tmax_value\x18\x03 \x01(\x03B\x04\x98\xb5\x18\x02R\bmaxValue\x12!\n" +
	"\tmin_value\x18\x04 \x01(\x03B\x04\x98\xb5\x18\x03R\bminValue:\x06\x8a\xb5\x18\x02idB?Z=github.com/romannikov/fdb-go-layer-plugin/tests/atomic;atomicb\x06proto3"

var (
	file_tests_atomic_atomic_proto_rawDescOnce sync.Once
	file_tests_atomic_atomic_proto_rawDescData []byte
)

func file_tests_atomic_atomic_proto_rawDescGZIP() []byte {
	file_tests_atomic_atomic_proto_rawDescOnce.Do(func() {
		file_tests_atomic_atomic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_atomic_atomic_proto_rawDesc), len(file_tests_atomic_atomic_proto_rawDesc)))
	})
	return file_tests_atomic_atomic_proto_rawDescData
}

var file_tests_atomic_atomic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_atomic_atomic_proto_goTypes = []any{
	(*Counter)(nil), // 0: tests.atomic.Counter
}
var file_tests_atomic_atomic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_atomic_atomic_proto_init() }
func file_tests_atomic_atomic_proto_init() {
	if File_tests_atomic_atomic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_atomic_atomic_proto_rawDesc), len(file_tests_atomic_atomic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_atomic_atomic_proto_goTypes,
		DependencyIndexes: file_tests_atomic_atomic_proto_depIdxs,
		MessageInfos:      file_tests_atomic_atomic_proto_msgTypes,
	}.Build()
	File_tests_atomic_atomic_proto = out.File
	file_tests_atomic_atomic_proto_goTypes = nil
	file_tests_atomic_atomic_proto_depIdxs = nil
}
