// Code generated by fdb-go-layer-plugin. DO NOT EDIT.
// Source: github.com/romannikov/fdb-go-layer-plugin/tests/atomic

package atomic

import (
	"context"
	"encoding/binary"
	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	fdblayer "github.com/romannikov/fdb-go-layer-plugin/fdb-layer"
	"google.golang.org/protobuf/proto"
)

// CounterPaginationOptions represents options for paginated queries
type CounterPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// CounterPaginatedResult represents a paginated result set
type CounterPaginatedResult struct {
	Items   []*Counter
	NextKey tuple.Tuple
	HasMore bool
}

// CounterRepository defines the repository interface for Counter.
type CounterRepository interface {
	fdblayer.GenericRepository[*Counter, string]

	BatchGetCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Counter, error)
	ListCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts CounterPaginationOptions) (*CounterPaginatedResult, error)

	AddCounterValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error

	MaxCounterMaxValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error

	MinCounterMinValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error
}

type counterRepository struct {
	store *fdblayer.RecordStore
}

// NewCounterRepository creates a new CounterRepository instance.
func NewCounterRepository(store *fdblayer.RecordStore) CounterRepository {
	return &counterRepository{store: store}
}

// Create creates a new Counter entity in the database.
func (r *counterRepository) Create(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *Counter) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, entity.Id})

	// Save atomic fields and zero them out for marshaling
	atomic_Value := entity.Value
	entity.Value = 0
	atomic_MaxValue := entity.MaxValue
	entity.MaxValue = 0
	atomic_MinValue := entity.MinValue
	entity.MinValue = 0

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields
	entity.Value = atomic_Value
	entity.MaxValue = atomic_MaxValue
	entity.MinValue = atomic_MinValue

	tr.Set(key, value)

	// Store atomic fields in separate keys
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 2})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_Value))
		tr.Set(fieldKey, buf)
	}
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 3})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MaxValue))
		tr.Set(fieldKey, buf)
	}
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 4})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MinValue))
		tr.Set(fieldKey, buf)
	}

	return nil
}

// Get retrieves a Counter entity by its primary key.
func (r *counterRepository) Get(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, pk string) (*Counter, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return nil, err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, pk})
	valueFuture := tr.Get(key)
	// Issue atomic field reads concurrently with the primary record read
	fieldFuture_Value := tr.Get(dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, pk, 2}))
	fieldFuture_MaxValue := tr.Get(dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, pk, 3}))
	fieldFuture_MinValue := tr.Get(dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, pk, 4}))

	value := valueFuture.MustGet()
	if value == nil {
		return nil, fmt.Errorf("counter not found")
	}
	entity := &Counter{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}

	if fieldVal := fieldFuture_Value.MustGet(); fieldVal != nil {
		entity.Value = int64(binary.LittleEndian.Uint64(fieldVal))
	}
	if fieldVal := fieldFuture_MaxValue.MustGet(); fieldVal != nil {
		entity.MaxValue = int64(binary.LittleEndian.Uint64(fieldVal))
	}
	if fieldVal := fieldFuture_MinValue.MustGet(); fieldVal != nil {
		entity.MinValue = int64(binary.LittleEndian.Uint64(fieldVal))
	}

	return entity, nil
}

// Set updates an existing Counter entity in the database.
func (r *counterRepository) Set(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *Counter) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, entity.Id})

	// Save atomic fields and zero them out for marshaling
	atomic_Value := entity.Value
	entity.Value = 0
	atomic_MaxValue := entity.MaxValue
	entity.MaxValue = 0
	atomic_MinValue := entity.MinValue
	entity.MinValue = 0

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields
	entity.Value = atomic_Value
	entity.MaxValue = atomic_MaxValue
	entity.MinValue = atomic_MinValue

	tr.Set(key, value)

	// Store atomic fields in separate keys
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 2})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_Value))
		tr.Set(fieldKey, buf)
	}
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 3})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MaxValue))
		tr.Set(fieldKey, buf)
	}
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 4})
		buf := make([]byte, 8)
		binary.LittleEndian.PutUint64(buf, uint64(atomic_MinValue))
		tr.Set(fieldKey, buf)
	}

	return nil
}

// Delete removes a Counter entity from the database.
func (r *counterRepository) Delete(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, pk string) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, pk})

	tr.Clear(key)

	// Clear atomic fields
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, pk, 2})
		tr.Clear(fieldKey)
	}
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, pk, 3})
		tr.Clear(fieldKey)
	}
	{
		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, pk, 4})
		tr.Clear(fieldKey)
	}

	return nil
}

// BatchGetCounter retrieves multiple Counter entities by their primary keys.
func (r *counterRepository) BatchGetCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Counter, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return nil, err
	}

	result := make(map[string]*Counter)
	futures := make([]fdb.FutureByteSlice, len(ids))
	fieldFutures_Value := make([]fdb.FutureByteSlice, len(ids))
	fieldFutures_MaxValue := make([]fdb.FutureByteSlice, len(ids))
	fieldFutures_MinValue := make([]fdb.FutureByteSlice, len(ids))

	for i, id := range ids {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		keyTpl := make(tuple.Tuple, 2+len(id))
		keyTpl[0] = typeID
		keyTpl[1] = fdblayer.DataNamespace
		copy(keyTpl[2:], id)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
		{
			fieldTpl := make(tuple.Tuple, 3+len(id))
			fieldTpl[0] = typeID
			fieldTpl[1] = fdblayer.FieldNamespace
			copy(fieldTpl[2:], id)
			fieldTpl[2+len(id)] = 2
			fieldFutures_Value[i] = tr.Get(dir.Pack(fieldTpl))
		}
		{
			fieldTpl := make(tuple.Tuple, 3+len(id))
			fieldTpl[0] = typeID
			fieldTpl[1] = fdblayer.FieldNamespace
			copy(fieldTpl[2:], id)
			fieldTpl[2+len(id)] = 3
			fieldFutures_MaxValue[i] = tr.Get(dir.Pack(fieldTpl))
		}
		{
			fieldTpl := make(tuple.Tuple, 3+len(id))
			fieldTpl[0] = typeID
			fieldTpl[1] = fdblayer.FieldNamespace
			copy(fieldTpl[2:], id)
			fieldTpl[2+len(id)] = 4
			fieldFutures_MinValue[i] = tr.Get(dir.Pack(fieldTpl))
		}

	}

	for i, future := range futures {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Counter{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		if fieldVal := fieldFutures_Value[i].MustGet(); fieldVal != nil {
			entity.Value = int64(binary.LittleEndian.Uint64(fieldVal))
		}
		if fieldVal := fieldFutures_MaxValue[i].MustGet(); fieldVal != nil {
			entity.MaxValue = int64(binary.LittleEndian.Uint64(fieldVal))
		}
		if fieldVal := fieldFutures_MinValue[i].MustGet(); fieldVal != nil {
			entity.MinValue = int64(binary.LittleEndian.Uint64(fieldVal))
		}

		result[ids[i].String()] = entity
	}

	return result, nil
}

// ListCounter retrieves a list of Counter entities starting from the given key.
func (r *counterRepository) ListCounter(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts CounterPaginationOptions) (*CounterPaginatedResult, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return nil, err
	}

	result := &CounterPaginatedResult{
		Items: make([]*Counter, 0),
	}

	beginTpl := make(tuple.Tuple, 2+len(opts.Begin))
	beginTpl[0] = typeID
	beginTpl[1] = fdblayer.DataNamespace
	copy(beginTpl[2:], opts.Begin)
	begin := dir.Pack(beginTpl)

	// Scan only data keys under typeID namespace.
	dataPrefix := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace})
	dataPrefixRange, err := fdb.PrefixRange(dataPrefix)
	if err != nil {
		return nil, err
	}

	rangeOpts := fdb.RangeOptions{
		Reverse: false,
	}
	if opts.Limit > 0 {
		rangeOpts.Limit = opts.Limit + 1
	}

	iter := tr.GetRange(fdb.KeyRange{
		Begin: begin,
		End:   dataPrefixRange.End,
	}, rangeOpts).Iterator()

	var nextKey fdb.Key
	for iter.Advance() {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		kv := iter.MustGet()

		entity := &Counter{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if opts.Limit > 0 && len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = opts.Limit > 0 && len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID and DataNamespace to return just the PK tuple
		result.NextKey = tpl[2:]
		result.Items = result.Items[:opts.Limit]
	}

	// Populate atomic fields for returned items (pipelined)
	fieldFutures_Value := make([]fdb.FutureByteSlice, len(result.Items))
	fieldFutures_MaxValue := make([]fdb.FutureByteSlice, len(result.Items))
	fieldFutures_MinValue := make([]fdb.FutureByteSlice, len(result.Items))
	for i, entity := range result.Items {
		fieldFutures_Value[i] = tr.Get(dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 2}))
		fieldFutures_MaxValue[i] = tr.Get(dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 3}))
		fieldFutures_MinValue[i] = tr.Get(dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, entity.Id, 4}))
	}
	for i, entity := range result.Items {
		if fieldVal := fieldFutures_Value[i].MustGet(); fieldVal != nil {
			entity.Value = int64(binary.LittleEndian.Uint64(fieldVal))
		}
		if fieldVal := fieldFutures_MaxValue[i].MustGet(); fieldVal != nil {
			entity.MaxValue = int64(binary.LittleEndian.Uint64(fieldVal))
		}
		if fieldVal := fieldFutures_MinValue[i].MustGet(); fieldVal != nil {
			entity.MinValue = int64(binary.LittleEndian.Uint64(fieldVal))
		}
	}

	return result, nil
}

// AddCounterValue applies an atomic mutation to the Value field of Counter.
func (r *counterRepository) AddCounterValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, Id, 2})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val))

	tr.Add(key, buf)
	return nil
}

// MaxCounterMaxValue applies an atomic mutation to the MaxValue field of Counter.
func (r *counterRepository) MaxCounterMaxValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, Id, 3})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val))

	tr.Max(key, buf)
	return nil
}

// MinCounterMinValue applies an atomic mutation to the MinValue field of Counter.
func (r *counterRepository) MinCounterMinValue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, Id string, val int64) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Counter")
	if err != nil {
		return err
	}
	key := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, Id, 4})

	buf := make([]byte, 8)
	binary.LittleEndian.PutUint64(buf, uint64(val))

	tr.Min(key, buf)
	return nil
}
