package golang

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/romannikov/fdb-layer/compiler/ir"
)

// GenerateMessage emits the complete Go repository code for a single Protobuf message
// using protogen.GeneratedFile.P().
func GenerateMessage(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	generateHeader(g, msg)
	if msg.IsQueue {
		generateQueueRepository(g, msg)
	} else {
		generateEntityRepository(g, msg)
	}
}

func generateHeader(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	g.P("// Code generated by protoc-gen-fdb-go. DO NOT EDIT.")
	g.P("// Source: ", msg.GoPackagePath)
	g.P()
	g.P("package ", msg.GoPackageName)
	g.P()
	g.P("import (")
	if !msg.IsQueue && HasBytesImports(msg) {
		g.P(`	"bytes"`)
	}
	g.P(`	"context"`)
	if !msg.IsQueue && HasBinaryImports(msg) {
		g.P(`	"encoding/binary"`)
	}
	if !msg.IsQueue {
		g.P(`	"fmt"`)
	}
	g.P()
	g.P(`	"github.com/apple/foundationdb/bindings/go/src/fdb"`)
	g.P(`	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"`)
	g.P(`	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"`)
	g.P(`	fdblayer "github.com/romannikov/fdb-layer/runtimes/go"`)
	g.P(`	"google.golang.org/protobuf/proto"`)
	g.P(")")
	g.P()
}

func generateQueueRepository(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	firstPK := msg.PrimaryKeyFields[0]
	firstPKLower := strings.ToLower(firstPK.GoName)

	g.P("// ", msg.Name, "Repository defines the repository interface for the ", msg.Name, " queue.")
	g.P("type ", msg.Name, "Repository interface {")
	g.P("	Enqueue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, msg *", msg.Name, ") error")
	g.P("	Dequeue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, ", firstPKLower, " ", FieldGoType(firstPK), ") (*", msg.Name, ", error)")
	g.P("}")
	g.P()
	g.P("type ", lowerName, "Repository struct {")
	g.P("	store *fdblayer.RecordStore")
	g.P("}")
	g.P()
	g.P("// New", msg.Name, "Repository creates a new ", msg.Name, "Repository instance.")
	g.P("func New", msg.Name, "Repository(store *fdblayer.RecordStore) ", msg.Name, "Repository {")
	g.P("	return &", lowerName, "Repository{store: store}")
	g.P("}")
	g.P()

	generateEnqueue(g, msg)
	generateDequeue(g, msg)
}

func generateEnqueue(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	hasVS := ir.MsgHasVersionstampPK(msg)

	g.P("// Enqueue adds a ", msg.Name, " to the queue.")
	g.P("func (r *", lowerName, "Repository) Enqueue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *", msg.Name, ") error {")
	g.P("	if err := ctx.Err(); err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P(`	typeID, err := r.store.GetTypeID("`, msg.Name, `")`)
	g.P("	if err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P()
	if hasVS {
		g.P("	key, err := dir.PackWithVersionstamp(tuple.Tuple{typeID, fdblayer.DataNamespace, ", versionstampedPKTupleArgs(msg), "})")
		g.P("	if err != nil {")
		g.P("		return err")
		g.P("	}")
	} else {
		g.P("	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, ", pkTupleArgsFromEntity(msg, "entity"), "})")
	}
	g.P()
	g.P("	value, err := proto.Marshal(entity)")
	g.P("	if err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P()
	if hasVS {
		g.P("	tr.SetVersionstampedKey(key, value)")
	} else {
		g.P("	tr.Set(key, value)")
	}
	g.P()
	g.P("	return nil")
	g.P("}")
	g.P()
}

func generateDequeue(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	firstPK := msg.PrimaryKeyFields[0]
	firstPKLower := strings.ToLower(firstPK.GoName)

	g.P("// Dequeue reads and removes the single oldest message from the queue.")
	g.P("func (r *", lowerName, "Repository) Dequeue(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, ", firstPKLower, " ", FieldGoType(firstPK), ") (*", msg.Name, ", error) {")
	g.P("	if err := ctx.Err(); err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P(`	typeID, err := r.store.GetTypeID("`, msg.Name, `")`)
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	g.P("	prefixTuple := tuple.Tuple{typeID, fdblayer.DataNamespace, ", PackField(firstPKLower, firstPK), "}")
	g.P("	prefixRange, err := fdb.PrefixRange(dir.Pack(prefixTuple))")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	g.P("	options := fdb.RangeOptions{Limit: 1}")
	g.P("	rows := tr.GetRange(prefixRange, options).GetSliceOrPanic()")
	g.P()
	g.P("	if len(rows) == 0 {")
	g.P("		return nil, nil")
	g.P("	}")
	g.P()
	g.P("	firstItem := rows[0]")
	g.P("	keyToDelete := firstItem.Key")
	g.P("	payload := firstItem.Value")
	g.P()
	g.P("	tr.Clear(keyToDelete)")
	g.P()
	g.P("	entity := &", msg.Name, "{}")
	g.P("	err = proto.Unmarshal(payload, entity)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	if ir.MsgHasVersionstampPK(msg) {
		g.P("	if tpl, unpackErr := dir.Unpack(keyToDelete); unpackErr == nil {")
		for i, f := range msg.PrimaryKeyFields {
			if f.IsVersionstamp {
				g.P("		if len(tpl) > ", i, "+2 {")
				g.P("			if vs, ok := tpl[", i, "+2].(tuple.Versionstamp); ok {")
				g.P("				entity.", f.GoName, " = vs.Bytes()")
				g.P("			}")
				g.P("		}")
			}
		}
		g.P("	}")
		g.P()
	}
	g.P("	return entity, nil")
	g.P("}")
}

func generateEntityRepository(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	generateTypesAndInterface(g, msg)
	generateCreate(g, msg)
	generateGet(g, msg)
	generateSet(g, msg)
	generateDelete(g, msg)
	generateBatchGet(g, msg)
	generateList(g, msg)
	for _, idx := range msg.SecondaryIndexes {
		generateGetByIndex(g, msg, idx)
	}
	generateAtomicMutators(g, msg)
}

func generateTypesAndInterface(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	pkType := pkTypeExpr(msg)

	g.P("// ", msg.Name, "PaginationOptions represents options for paginated queries")
	g.P("type ", msg.Name, "PaginationOptions struct {")
	g.P("	Begin tuple.Tuple")
	g.P("	Limit int")
	g.P("}")
	g.P()
	g.P("// ", msg.Name, "PaginatedResult represents a paginated result set")
	g.P("type ", msg.Name, "PaginatedResult struct {")
	g.P("	Items   []*", msg.Name)
	g.P("	NextKey tuple.Tuple")
	g.P("	HasMore bool")
	g.P("}")
	g.P()

	if len(msg.PrimaryKeyFields) > 1 {
		g.P("// ", msg.Name, "PrimaryKey represents the compound primary key for ", msg.Name, ".")
		g.P("type ", msg.Name, "PrimaryKey struct {")
		for _, f := range msg.PrimaryKeyFields {
			g.P("	", f.GoName, " ", FieldGoType(f))
		}
		g.P("}")
		g.P()
	}

	g.P("// ", msg.Name, "Repository defines the repository interface for ", msg.Name, ".")
	g.P("type ", msg.Name, "Repository interface {")
	g.P("	fdblayer.GenericRepository[*", msg.Name, ", ", pkType, "]")
	g.P()
	g.P("	BatchGet", msg.Name, "(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*", msg.Name, ", error)")
	g.P("	List", msg.Name, "(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts ", msg.Name, "PaginationOptions) (*", msg.Name, "PaginatedResult, error)")
	for _, idx := range msg.SecondaryIndexes {
		g.P("	Get", msg.Name, "By", JoinFieldNames(idx.Fields), "(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ", fieldParamDecls(idx.Fields), ") ([]*", msg.Name, ", error)")
	}
	for _, f := range msg.Fields {
		if f.Mutation != ir.MutationNone {
			g.P("	", MutationVerb(f.Mutation), msg.Name, f.GoName, "(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, ", fieldParamDecls(msg.PrimaryKeyFields), ", val ", FieldGoType(f), ") error")
		}
	}
	g.P("}")
	g.P()
	g.P("type ", lowerName, "Repository struct {")
	g.P("	store *fdblayer.RecordStore")
	g.P("}")
	g.P()
	g.P("// New", msg.Name, "Repository creates a new ", msg.Name, "Repository instance.")
	g.P("func New", msg.Name, "Repository(store *fdblayer.RecordStore) ", msg.Name, "Repository {")
	g.P("	return &", lowerName, "Repository{store: store}")
	g.P("}")
	g.P()
}

func generateCreate(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	hasVS := ir.MsgHasVersionstampPK(msg)
	hasMut := ir.HasMutationFields(msg)

	g.P("// Create creates a new ", msg.Name, " entity in the database.")
	g.P("func (r *", lowerName, "Repository) Create(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *", msg.Name, ") error {")
	g.P("	if err := ctx.Err(); err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P(`	typeID, err := r.store.GetTypeID("`, msg.Name, `")`)
	g.P("	if err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P()
	if hasVS {
		g.P("	key, err := dir.PackWithVersionstamp(tuple.Tuple{typeID, fdblayer.DataNamespace, ", versionstampedPKTupleArgs(msg), "})")
		g.P("	if err != nil {")
		g.P("		return err")
		g.P("	}")
	} else {
		g.P("	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, ", pkTupleArgsFromEntity(msg, "entity"), "})")
		g.P("	if existing := tr.Get(key).MustGet(); existing != nil {")
		g.P(`		return fmt.Errorf("`, lowerName, ` %w", fdblayer.ErrAlreadyExists)`)
		g.P("	}")
	}
	g.P()

	generateMarshalWithZeroedAtomics(g, msg)

	if hasVS {
		g.P("	tr.SetVersionstampedKey(key, value)")
	} else {
		g.P("	tr.Set(key, value)")
	}
	g.P()

	if hasMut {
		g.P("	// Store non-zero initial atomic fields in separate keys")
		pkArgs := pkTupleArgsFromEntity(msg, "entity")
		for _, f := range msg.Fields {
			if f.Mutation != ir.MutationNone {
				g.P("	if entity.", f.GoName, " != 0 {")
				g.P("		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, ", pkArgs, ", ", f.Number, "})")
				g.P("		buf := make([]byte, 8)")
				g.P("		binary.LittleEndian.PutUint64(buf, ", encodeAtomicUint64Expr("entity."+f.GoName, f), ")")
				g.P("		tr.", MutationVerb(f.Mutation), "(fieldKey, buf)")
				g.P("	}")
			}
		}
		g.P()
	}

	pkArgs := pkTupleArgsFromEntity(msg, "entity")
	for _, idx := range msg.SecondaryIndexes {
		if idx.IsFanOut {
			g.P("	// Fan-out index")
			for i, f := range idx.Fields {
				if f.IsRepeated {
					g.P("	for _, item := range entity.", f.GoName, " {")
					emitFanOutIndexWrite(g, msg, idx, i, "entity", true, "\t\t")
					g.P("	}")
				}
			}
		} else {
			g.P("	// Standard index")
			g.P("	tr.Set(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, ", idx.IndexID, ", ", indexFieldTupleArgs(idx.Fields, "entity"), ", ", pkArgs, "}), []byte{})")
		}
		g.P()
	}

	g.P("	return nil")
	g.P("}")
	g.P()
}

func generateGet(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	pkType := pkTypeExpr(msg)
	pkArgs := pkTupleArgsFromParam(msg)
	hasMut := ir.HasMutationFields(msg)

	g.P("// Get retrieves a ", msg.Name, " entity by its primary key.")
	g.P("func (r *", lowerName, "Repository) Get(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, pk ", pkType, ") (*", msg.Name, ", error) {")
	g.P("	if err := ctx.Err(); err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P(`	typeID, err := r.store.GetTypeID("`, msg.Name, `")`)
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	g.P("	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, ", pkArgs, "})")
	g.P("	valueFuture := tr.Get(key)")
	if hasMut {
		g.P("	// Issue a single prefix range read for all atomic fields concurrently with the primary record read")
		g.P("	fieldPrefixRange, err := fdb.PrefixRange(dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, ", pkArgs, "}))")
		g.P("	if err != nil {")
		g.P("		return nil, err")
		g.P("	}")
		g.P("	fieldFuture := fdblayer.GetRange(tr, fieldPrefixRange, fdb.RangeOptions{})")
	}
	g.P("	value := valueFuture.MustGet()")
	g.P("	if value == nil {")
	g.P(`		return nil, fmt.Errorf("`, lowerName, ` not found")`)
	g.P("	}")
	g.P("	entity := &", msg.Name, "{}")
	g.P("	err = proto.Unmarshal(value, entity)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	if hasMut {
		generateUnmarshalAtomicFields(g, msg, "fieldFuture.GetSliceOrPanic()", "\t")
	}
	g.P("	return entity, nil")
	g.P("}")
	g.P()
}

func generateSet(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	hasVS := ir.MsgHasVersionstampPK(msg)
	pkArgsEntity := pkTupleArgsFromEntity(msg, "entity")
	pkArgsOld := pkTupleArgsFromEntity(msg, "old")

	g.P("// Set updates an existing ", msg.Name, " entity in the database.")
	g.P("func (r *", lowerName, "Repository) Set(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *", msg.Name, ") error {")
	g.P("	if err := ctx.Err(); err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P(`	typeID, err := r.store.GetTypeID("`, msg.Name, `")`)
	g.P("	if err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P()

	if len(msg.SecondaryIndexes) > 0 {
		g.P("	var old *", msg.Name)
		g.P()
	}

	if hasVS {
		var vsFieldName string
		for _, f := range msg.PrimaryKeyFields {
			if f.IsVersionstamp {
				vsFieldName = f.GoName
				break
			}
		}
		g.P("	// If the entity already has a versionstamp, delete the old versionstamped record.")
		g.P("	// (Since the primary key contains the versionstamp, an update changes the key itself).")
		g.P("	hasOldVS := false")
		g.P("	for _, b := range entity.", vsFieldName, " {")
		g.P("		if b != 0 {")
		g.P("			hasOldVS = true")
		g.P("			break")
		g.P("		}")
		g.P("	}")
		g.P("	if hasOldVS {")
		g.P("		oldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, ", pkArgsEntity, "})")
		g.P("		tr.Clear(oldKey)")
		g.P("	}")
		g.P()
		g.P("	key, err := dir.PackWithVersionstamp(tuple.Tuple{typeID, fdblayer.DataNamespace, ", versionstampedPKTupleArgs(msg), "})")
		g.P("	if err != nil {")
		g.P("		return err")
		g.P("	}")
	} else {
		g.P("	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, ", pkArgsEntity, "})")
		if len(msg.SecondaryIndexes) > 0 {
			g.P()
			g.P("	if oldValue := tr.Get(key).MustGet(); oldValue != nil {")
			g.P("		var unmarshaled ", msg.Name)
			g.P("		if err := proto.Unmarshal(oldValue, &unmarshaled); err != nil {")
			g.P(`			return fmt.Errorf("failed to unmarshal existing `, lowerName, `: %w", err)`)
			g.P("		}")
			g.P("		old = &unmarshaled")
			g.P("	}")
		}
	}
	g.P()

	generateMarshalWithZeroedAtomics(g, msg)

	if hasVS {
		g.P("	tr.SetVersionstampedKey(key, value)")
	} else {
		g.P("	tr.Set(key, value)")
	}
	g.P()

	for _, idx := range msg.SecondaryIndexes {
		if idx.IsFanOut {
			g.P("	// Fan-out index")
			for i, f := range idx.Fields {
				if f.IsRepeated {
					cond := "old != nil"
					if HasNonRepeatedFields(idx.Fields) {
						cond += " && " + NonRepeatedFieldsEqual(idx.Fields)
					}
					mapType := MapKeyType(f)
					mapExpr := MapKeyExpr("item", f)

					g.P("	if ", cond, " {")
					g.P("		oldSet := make(map[", mapType, "]struct{}, len(old.", f.GoName, "))")
					g.P("		for _, item := range old.", f.GoName, " {")
					g.P("			oldSet[", mapExpr, "] = struct{}{}")
					g.P("		}")
					g.P("		newSet := make(map[", mapType, "]struct{}, len(entity.", f.GoName, "))")
					g.P("		for _, item := range entity.", f.GoName, " {")
					g.P("			newSet[", mapExpr, "] = struct{}{}")
					g.P("		}")
					g.P("		for _, item := range old.", f.GoName, " {")
					g.P("			if _, keep := newSet[", mapExpr, "]; !keep {")
					emitFanOutIndexWrite(g, msg, idx, i, "old", false, "\t\t\t\t")
					g.P("			}")
					g.P("		}")
					g.P("		for _, item := range entity.", f.GoName, " {")
					g.P("			if _, existed := oldSet[", mapExpr, "]; !existed {")
					emitFanOutIndexWrite(g, msg, idx, i, "entity", true, "\t\t\t\t")
					g.P("			}")
					g.P("		}")
					g.P("	} else {")
					if HasNonRepeatedFields(idx.Fields) {
						g.P("		if old != nil {")
						g.P("			for _, item := range old.", f.GoName, " {")
						emitFanOutIndexWrite(g, msg, idx, i, "old", false, "\t\t\t\t")
						g.P("			}")
						g.P("		}")
					}
					g.P("		for _, item := range entity.", f.GoName, " {")
					emitFanOutIndexWrite(g, msg, idx, i, "entity", true, "\t\t\t")
					g.P("		}")
					g.P("	}")
				}
			}
		} else {
			var diffParts []string
			for _, f := range idx.Fields {
				diffParts = append(diffParts, FieldNotEqual("old."+f.GoName, "entity."+f.GoName, f))
			}
			g.P("	// Standard index")
			g.P("	if old == nil || ", strings.Join(diffParts, " || "), " {")
			g.P("		if old != nil {")
			g.P("			tr.Clear(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, ", idx.IndexID, ", ", indexFieldTupleArgs(idx.Fields, "old"), ", ", pkArgsOld, "}))")
			g.P("		}")
			g.P("		tr.Set(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, ", idx.IndexID, ", ", indexFieldTupleArgs(idx.Fields, "entity"), ", ", pkArgsEntity, "}), []byte{})")
			g.P("	}")
		}
		g.P()
	}

	g.P("	return nil")
	g.P("}")
	g.P()
}

func generateDelete(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	pkType := pkTypeExpr(msg)
	pkArgs := pkTupleArgsFromParam(msg)
	pkArgsEntity := pkTupleArgsFromEntity(msg, "entity")

	g.P("// Delete removes a ", msg.Name, " entity from the database.")
	g.P("func (r *", lowerName, "Repository) Delete(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, pk ", pkType, ") error {")
	g.P("	if err := ctx.Err(); err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P(`	typeID, err := r.store.GetTypeID("`, msg.Name, `")`)
	g.P("	if err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P()
	g.P("	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, ", pkArgs, "})")
	if len(msg.SecondaryIndexes) > 0 {
		g.P("	value := tr.Get(key).MustGet()")
		g.P("	if value != nil {")
		g.P("		entity := &", msg.Name, "{}")
		g.P("		if err := proto.Unmarshal(value, entity); err != nil {")
		g.P(`			return fmt.Errorf("failed to unmarshal existing `, lowerName, `: %w", err)`)
		g.P("		}")
		for _, idx := range msg.SecondaryIndexes {
			if idx.IsFanOut {
				g.P("		// Fan-out index")
				for i, f := range idx.Fields {
					if f.IsRepeated {
						g.P("		for _, item := range entity.", f.GoName, " {")
						emitFanOutIndexWrite(g, msg, idx, i, "entity", false, "\t\t\t")
						g.P("		}")
					}
				}
			} else {
				g.P("		// Standard index")
				g.P("		tr.Clear(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, ", idx.IndexID, ", ", indexFieldTupleArgs(idx.Fields, "entity"), ", ", pkArgsEntity, "}))")
			}
		}
		g.P("	}")
	}
	g.P("	tr.Clear(key)")
	g.P()
	if ir.HasMutationFields(msg) {
		g.P("	// Clear atomic fields")
		for _, f := range msg.Fields {
			if f.Mutation != ir.MutationNone {
				g.P("	{")
				g.P("		fieldKey := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, ", pkArgs, ", ", f.Number, "})")
				g.P("		tr.Clear(fieldKey)")
				g.P("	}")
			}
		}
	}
	g.P("	return nil")
	g.P("}")
	g.P()
}

func generateBatchGet(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	hasMut := ir.HasMutationFields(msg)

	g.P("// BatchGet", msg.Name, " retrieves multiple ", msg.Name, " entities by their primary keys.")
	g.P("func (r *", lowerName, "Repository) BatchGet", msg.Name, "(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*", msg.Name, ", error) {")
	g.P("	if err := ctx.Err(); err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P(`	typeID, err := r.store.GetTypeID("`, msg.Name, `")`)
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	g.P("	result := make(map[string]*", msg.Name, ")")
	g.P("	futures := make([]fdb.FutureByteSlice, len(ids))")
	if hasMut {
		g.P("	fieldFutures := make([]fdblayer.RangeFuture, len(ids))")
	}
	g.P()
	g.P("	for i, id := range ids {")
	g.P("		if err := ctx.Err(); err != nil {")
	g.P("			return nil, err")
	g.P("		}")
	g.P("		keyTpl := make(tuple.Tuple, 2+len(id))")
	g.P("		keyTpl[0] = typeID")
	g.P("		keyTpl[1] = fdblayer.DataNamespace")
	g.P("		copy(keyTpl[2:], id)")
	g.P("		key := dir.Pack(keyTpl)")
	g.P("		futures[i] = tr.Get(key)")
	if hasMut {
		g.P("		fieldTpl := make(tuple.Tuple, 2+len(id))")
		g.P("		fieldTpl[0] = typeID")
		g.P("		fieldTpl[1] = fdblayer.FieldNamespace")
		g.P("		copy(fieldTpl[2:], id)")
		g.P("		fieldRange, err := fdb.PrefixRange(dir.Pack(fieldTpl))")
		g.P("		if err != nil {")
		g.P("			return nil, err")
		g.P("		}")
		g.P("		fieldFutures[i] = fdblayer.GetRange(tr, fieldRange, fdb.RangeOptions{})")
	}
	g.P("	}")
	g.P()
	g.P("	for i, future := range futures {")
	g.P("		if err := ctx.Err(); err != nil {")
	g.P("			return nil, err")
	g.P("		}")
	g.P("		value := future.MustGet()")
	g.P("		if value == nil {")
	g.P("			continue")
	g.P("		}")
	g.P("		entity := &", msg.Name, "{}")
	g.P("		err := proto.Unmarshal(value, entity)")
	g.P("		if err != nil {")
	g.P(`			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)`)
	g.P("		}")
	if hasMut {
		generateUnmarshalAtomicFields(g, msg, "fieldFutures[i].GetSliceOrPanic()", "\t\t")
	}
	g.P("		result[ids[i].String()] = entity")
	g.P("	}")
	g.P()
	g.P("	return result, nil")
	g.P("}")
	g.P()
}

func generateList(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	hasMut := ir.HasMutationFields(msg)

	g.P("// List", msg.Name, " retrieves a list of ", msg.Name, " entities starting from the given key.")
	g.P("func (r *", lowerName, "Repository) List", msg.Name, "(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts ", msg.Name, "PaginationOptions) (*", msg.Name, "PaginatedResult, error) {")
	g.P("	if err := ctx.Err(); err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P(`	typeID, err := r.store.GetTypeID("`, msg.Name, `")`)
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	g.P("	result := &", msg.Name, "PaginatedResult{")
	g.P("		Items: make([]*", msg.Name, ", 0),")
	g.P("	}")
	g.P()
	g.P("	beginTpl := make(tuple.Tuple, 2+len(opts.Begin))")
	g.P("	beginTpl[0] = typeID")
	g.P("	beginTpl[1] = fdblayer.DataNamespace")
	g.P("	copy(beginTpl[2:], opts.Begin)")
	g.P("	begin := dir.Pack(beginTpl)")
	g.P()
	g.P("	// Scan only data keys under typeID namespace.")
	g.P("	dataPrefix := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace})")
	g.P("	dataPrefixRange, err := fdb.PrefixRange(dataPrefix)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	g.P("	rangeOpts := fdb.RangeOptions{")
	g.P("		Reverse: false,")
	g.P("	}")
	g.P("	if opts.Limit > 0 {")
	g.P("		rangeOpts.Limit = opts.Limit + 1")
	g.P("	}")
	g.P()
	g.P("	kvs := fdblayer.GetRange(tr, fdb.KeyRange{")
	g.P("		Begin: begin,")
	g.P("		End:   dataPrefixRange.End,")
	g.P("	}, rangeOpts).GetSliceOrPanic()")
	g.P()
	g.P("	var nextKey fdb.Key")
	g.P("	for _, kv := range kvs {")
	g.P("		if err := ctx.Err(); err != nil {")
	g.P("			return nil, err")
	g.P("		}")
	g.P()
	g.P("		entity := &", msg.Name, "{}")
	g.P("		err = proto.Unmarshal(kv.Value, entity)")
	g.P("		if err != nil {")
	g.P(`			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)`)
	g.P("		}")
	g.P("		result.Items = append(result.Items, entity)")
	g.P("		nextKey = kv.Key")
	g.P()
	g.P("		// Stop once we have enough items for pagination check")
	g.P("		if opts.Limit > 0 && len(result.Items) > opts.Limit {")
	g.P("			break")
	g.P("		}")
	g.P("	}")
	g.P()
	g.P("	result.HasMore = opts.Limit > 0 && len(result.Items) > opts.Limit")
	g.P("	if result.HasMore {")
	g.P("		tpl, err := dir.Unpack(nextKey)")
	g.P("		if err != nil {")
	g.P(`			return nil, fmt.Errorf("failed to unpack next key: %w", err)`)
	g.P("		}")
	g.P("		// Remove typeID and DataNamespace to return just the PK tuple")
	g.P("		result.NextKey = tpl[2:]")
	g.P("		result.Items = result.Items[:opts.Limit]")
	g.P("	}")
	g.P()
	if hasMut {
		firstPKArgs := pkTupleArgsFromEntity(msg, "first")
		lastPKArgs := pkTupleArgsFromEntity(msg, "last")
		entityPKArgs := pkTupleArgsFromEntity(msg, "entity")

		g.P("	// Populate atomic fields for all returned items in a single range read")
		g.P("	if len(result.Items) > 0 {")
		g.P("		first := result.Items[0]")
		g.P("		last := result.Items[len(result.Items)-1]")
		g.P("		fieldBegin := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, ", firstPKArgs, "})")
		g.P("		fieldEndPrefix, err := fdb.PrefixRange(dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, ", lastPKArgs, "}))")
		g.P("		if err != nil {")
		g.P("			return nil, err")
		g.P("		}")
		g.P("		itemByPK := make(map[string]*", msg.Name, ", len(result.Items))")
		g.P("		for _, entity := range result.Items {")
		for _, f := range msg.Fields {
			if f.Mutation != ir.MutationNone {
				g.P("			entity.", f.GoName, " = 0")
			}
		}
		g.P("			pkKey := tuple.Tuple{", entityPKArgs, "}.String()")
		g.P("			itemByPK[pkKey] = entity")
		g.P("		}")
		g.P("		fieldKVs := fdblayer.GetRange(tr, fdb.KeyRange{Begin: fieldBegin, End: fieldEndPrefix.End}, fdb.RangeOptions{}).GetSliceOrPanic()")
		g.P("		pkLen := ", len(msg.PrimaryKeyFields))
		g.P("		for _, fkv := range fieldKVs {")
		g.P("			if len(fkv.Value) < 8 {")
		g.P("				continue")
		g.P("			}")
		g.P("			ftpl, err := dir.Unpack(fkv.Key)")
		g.P("			if err != nil || len(ftpl) < 3+pkLen {")
		g.P("				continue")
		g.P("			}")
		g.P("			entity, ok := itemByPK[ftpl[2:2+pkLen].String()]")
		g.P("			if !ok {")
		g.P("				continue")
		g.P("			}")
		g.P("			fieldNum, ok := ftpl[2+pkLen].(int64)")
		g.P("			if !ok {")
		g.P("				continue")
		g.P("			}")
		g.P("			switch fieldNum {")
		for _, f := range msg.Fields {
			if f.Mutation != ir.MutationNone {
				g.P("			case ", f.Number, ":")
				g.P("				entity.", f.GoName, " = ", decodeAtomicGoExpr("fkv.Value", f))
			}
		}
		g.P("			}")
		g.P("		}")
		g.P("	}")
		g.P()
	}
	g.P("	return result, nil")
	g.P("}")
	g.P()
}

func generateGetByIndex(g *protogen.GeneratedFile, msg ir.MessageSpec, idx ir.SecondaryIndexSpec) {
	lowerName := strings.ToLower(msg.Name)
	joinedNames := JoinFieldNames(idx.Fields)
	hasMut := ir.HasMutationFields(msg)

	var idxPackArgs []string
	for _, f := range idx.Fields {
		idxPackArgs = append(idxPackArgs, PackField(f.GoName, f))
	}

	g.P("// Get", msg.Name, "By", joinedNames, " retrieves ", msg.Name, " entities by their ", joinedNames, " index.")
	g.P("func (r *", lowerName, "Repository) Get", msg.Name, "By", joinedNames, "(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ", fieldParamDecls(idx.Fields), ") ([]*", msg.Name, ", error) {")
	g.P("	if err := ctx.Err(); err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P(`	typeID, err := r.store.GetTypeID("`, msg.Name, `")`)
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	g.P("	entities := []*", msg.Name, "{}")
	g.P("	indexKeyPrefix := dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, ", idx.IndexID, ", ", strings.Join(idxPackArgs, ", "), "})")
	g.P("	indexRange, err := fdb.PrefixRange(indexKeyPrefix)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	kvs := tr.GetRange(indexRange, fdb.RangeOptions{}).GetSliceOrPanic()")
	g.P("	futures := make([]fdb.FutureByteSlice, len(kvs))")
	if hasMut {
		g.P("	fieldFutures := make([]fdblayer.RangeFuture, len(kvs))")
	}
	g.P("	for i, kv := range kvs {")
	g.P("		if err := ctx.Err(); err != nil {")
	g.P("			return nil, err")
	g.P("		}")
	g.P("		tpl, err := dir.Unpack(kv.Key)")
	g.P("		if err != nil {")
	g.P("			return nil, err")
	g.P("		}")
	g.P("		pkIndexStart := 3 + ", len(idx.Fields))
	g.P("		if len(tpl) <= pkIndexStart {")
	g.P("			continue")
	g.P("		}")
	g.P("		pkTuple := tpl[pkIndexStart:]")
	g.P("		keyTpl := make(tuple.Tuple, 2+len(pkTuple))")
	g.P("		keyTpl[0] = typeID")
	g.P("		keyTpl[1] = fdblayer.DataNamespace")
	g.P("		copy(keyTpl[2:], pkTuple)")
	g.P("		key := dir.Pack(keyTpl)")
	g.P("		futures[i] = tr.Get(key)")
	if hasMut {
		g.P("		fieldTpl := make(tuple.Tuple, 2+len(pkTuple))")
		g.P("		fieldTpl[0] = typeID")
		g.P("		fieldTpl[1] = fdblayer.FieldNamespace")
		g.P("		copy(fieldTpl[2:], pkTuple)")
		g.P("		fieldRange, err := fdb.PrefixRange(dir.Pack(fieldTpl))")
		g.P("		if err != nil {")
		g.P("			return nil, err")
		g.P("		}")
		g.P("		fieldFutures[i] = fdblayer.GetRange(tr, fieldRange, fdb.RangeOptions{})")
	}
	g.P("	}")
	iterVar := "_"
	if hasMut {
		iterVar = "i"
	}
	g.P("	for ", iterVar, ", future := range futures {")
	g.P("		if err := ctx.Err(); err != nil {")
	g.P("			return nil, err")
	g.P("		}")
	g.P("		if future == nil {")
	g.P("			continue")
	g.P("		}")
	g.P("		value := future.MustGet()")
	g.P("		if value == nil {")
	g.P("			continue")
	g.P("		}")
	g.P("		entity := &", msg.Name, "{}")
	g.P("		err = proto.Unmarshal(value, entity)")
	g.P("		if err != nil {")
	g.P("			return nil, err")
	g.P("		}")
	if hasMut {
		generateUnmarshalAtomicFields(g, msg, "fieldFutures[i].GetSliceOrPanic()", "\t\t")
	}
	g.P("		entities = append(entities, entity)")
	g.P("	}")
	g.P("	return entities, nil")
	g.P("}")
	g.P()
}

func generateAtomicMutators(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	lowerName := strings.ToLower(msg.Name)
	var pkPackArgs []string
	for _, f := range msg.PrimaryKeyFields {
		pkPackArgs = append(pkPackArgs, PackField(f.GoName, f))
	}
	pkArgsStr := strings.Join(pkPackArgs, ", ")

	for _, f := range msg.Fields {
		if f.Mutation == ir.MutationNone {
			continue
		}
		verb := MutationVerb(f.Mutation)
		g.P("// ", verb, msg.Name, f.GoName, " applies an atomic mutation to the ", f.GoName, " field of ", msg.Name, ".")
		g.P("func (r *", lowerName, "Repository) ", verb, msg.Name, f.GoName, "(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, ", fieldParamDecls(msg.PrimaryKeyFields), ", val ", FieldGoType(f), ") error {")
		g.P("	if err := ctx.Err(); err != nil {")
		g.P("		return err")
		g.P("	}")
		g.P(`	typeID, err := r.store.GetTypeID("`, msg.Name, `")`)
		g.P("	if err != nil {")
		g.P("		return err")
		g.P("	}")
		g.P("	key := dir.Pack(tuple.Tuple{typeID, fdblayer.FieldNamespace, ", pkArgsStr, ", ", f.Number, "})")
		g.P()
		g.P("	buf := make([]byte, 8)")
		g.P("	binary.LittleEndian.PutUint64(buf, ", encodeAtomicUint64Expr("val", f), ")")
		g.P()
		g.P("	tr.", verb, "(key, buf)")
		g.P("	return nil")
		g.P("}")
		g.P()
	}
}

func encodeAtomicUint64Expr(expr string, f ir.FieldSpec) string {
	if !f.IsUnsigned && (f.Mutation == ir.MutationMax || f.Mutation == ir.MutationMin) {
		if FieldGoType(f) == "int64" {
			return fmt.Sprintf("uint64(%s)^(1<<63)", expr)
		}
		return fmt.Sprintf("uint64(int64(%s))^(1<<63)", expr)
	}
	return fmt.Sprintf("uint64(%s)", expr)
}

func decodeAtomicGoExpr(sliceExpr string, f ir.FieldSpec) string {
	if !f.IsUnsigned && (f.Mutation == ir.MutationMax || f.Mutation == ir.MutationMin) {
		if FieldGoType(f) == "int64" {
			return fmt.Sprintf("int64(binary.LittleEndian.Uint64(%s) ^ (1 << 63))", sliceExpr)
		}
		return fmt.Sprintf("%s(int64(binary.LittleEndian.Uint64(%s) ^ (1 << 63)))", FieldGoType(f), sliceExpr)
	}
	return fmt.Sprintf("%s(binary.LittleEndian.Uint64(%s))", FieldGoType(f), sliceExpr)
}

func generateMarshalWithZeroedAtomics(g *protogen.GeneratedFile, msg ir.MessageSpec) {
	hasMut := ir.HasMutationFields(msg)
	if hasMut {
		var nonZeroChecks []string
		for _, f := range msg.Fields {
			if f.Mutation != ir.MutationNone {
				nonZeroChecks = append(nonZeroChecks, fmt.Sprintf("entity.%s != 0", f.GoName))
			}
		}
		g.P("	// Marshal without mutating the caller's struct in-place.")
		g.P("	marshalTarget := entity")
		g.P("	if ", strings.Join(nonZeroChecks, " || "), " {")
		g.P("		marshalTarget = &", msg.Name, "{")
		for _, f := range msg.Fields {
			if f.Mutation == ir.MutationNone {
				g.P("			", f.GoName, ": entity.", f.GoName, ",")
			}
		}
		g.P("		}")
		g.P("	}")
		g.P("	value, err := proto.Marshal(marshalTarget)")
	} else {
		g.P("	value, err := proto.Marshal(entity)")
	}
	g.P("	if err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P()
}

func generateUnmarshalAtomicFields(g *protogen.GeneratedFile, msg ir.MessageSpec, sliceExpr string, indent string) {
	for _, f := range msg.Fields {
		if f.Mutation != ir.MutationNone {
			g.P(indent, "entity.", f.GoName, " = 0")
		}
	}
	g.P(indent, "for _, fkv := range ", sliceExpr, " {")
	g.P(indent, "	if len(fkv.Value) < 8 {")
	g.P(indent, "		continue")
	g.P(indent, "	}")
	g.P(indent, "	ftpl, err := dir.Unpack(fkv.Key)")
	g.P(indent, "	if err != nil || len(ftpl) == 0 {")
	g.P(indent, "		continue")
	g.P(indent, "	}")
	g.P(indent, "	fieldNum, ok := ftpl[len(ftpl)-1].(int64)")
	g.P(indent, "	if !ok {")
	g.P(indent, "		continue")
	g.P(indent, "	}")
	g.P(indent, "	switch fieldNum {")
	for _, f := range msg.Fields {
		if f.Mutation != ir.MutationNone {
			g.P(indent, "	case ", f.Number, ":")
			g.P(indent, "		entity.", f.GoName, " = ", decodeAtomicGoExpr("fkv.Value", f))
		}
	}
	g.P(indent, "	}")
	g.P(indent, "}")
}

// FieldGoType returns the Go type string for an ir.FieldSpec.
func FieldGoType(f ir.FieldSpec) string {
	if f.Kind == ir.KindEnum && f.EnumGoName != "" {
		return f.EnumGoName
	}
	if f.Kind == ir.KindMessage && f.MessageGoName != "" {
		return "*" + f.MessageGoName
	}
	return GoType(f.Kind)
}

// GoType maps an ir.FieldKind to its scalar Go type string.
func GoType(kind ir.FieldKind) string {
	switch kind {
	case ir.KindInt32, ir.KindSint32, ir.KindSfixed32:
		return "int32"
	case ir.KindUint32, ir.KindFixed32:
		return "uint32"
	case ir.KindInt64, ir.KindSint64, ir.KindSfixed64:
		return "int64"
	case ir.KindUint64, ir.KindFixed64:
		return "uint64"
	case ir.KindFloat:
		return "float32"
	case ir.KindDouble:
		return "float64"
	case ir.KindString:
		return "string"
	case ir.KindBool:
		return "bool"
	case ir.KindBytes:
		return "[]byte"
	default:
		return "interface{}"
	}
}

// JoinFieldNames joins field GoNames with "And".
func JoinFieldNames(fields []ir.FieldSpec) string {
	names := make([]string, 0, len(fields))
	for _, f := range fields {
		names = append(names, f.GoName)
	}
	return strings.Join(names, "And")
}

// HasBinaryImports returns true if the message requires "encoding/binary".
func HasBinaryImports(msg ir.MessageSpec) bool {
	return ir.HasMutationFields(msg)
}

// HasBytesImports returns true if the message requires "bytes" for index comparisons.
func HasBytesImports(msg ir.MessageSpec) bool {
	for _, idx := range msg.SecondaryIndexes {
		for _, f := range idx.Fields {
			if f.Kind == ir.KindBytes && !f.IsRepeated {
				return true
			}
		}
	}
	return false
}

// PackField normalizes a Go expression for FDB tuple packing.
func PackField(name string, f ir.FieldSpec) string {
	goType := FieldGoType(f)
	if f.IsUnsigned || goType == "uint32" || goType == "uint64" {
		return "uint64(" + name + ")"
	}
	if f.IsEnum || goType == "int32" || goType == "int64" {
		return "int64(" + name + ")"
	}
	return name
}

// FieldNotEqual returns a Go inequality expression for a field.
func FieldNotEqual(lhs, rhs string, f ir.FieldSpec) string {
	if f.Kind == ir.KindBytes {
		return fmt.Sprintf("!bytes.Equal(%s, %s)", lhs, rhs)
	}
	return fmt.Sprintf("%s != %s", lhs, rhs)
}

// FieldEqual returns a Go equality expression for a field.
func FieldEqual(lhs, rhs string, f ir.FieldSpec) string {
	if f.Kind == ir.KindBytes {
		return fmt.Sprintf("bytes.Equal(%s, %s)", lhs, rhs)
	}
	return fmt.Sprintf("%s == %s", lhs, rhs)
}

// HasNonRepeatedFields returns true if any field in fields is non-repeated.
func HasNonRepeatedFields(fields []ir.FieldSpec) bool {
	for _, f := range fields {
		if !f.IsRepeated {
			return true
		}
	}
	return false
}

// NonRepeatedFieldsEqual returns a Go conjunction comparing all non-repeated fields between old and entity.
func NonRepeatedFieldsEqual(fields []ir.FieldSpec) string {
	var parts []string
	for _, f := range fields {
		if !f.IsRepeated {
			parts = append(parts, FieldEqual("old."+f.GoName, "entity."+f.GoName, f))
		}
	}
	return strings.Join(parts, " && ")
}

// MapKeyType returns a comparable Go map key type for fan-out index diffing.
func MapKeyType(f ir.FieldSpec) string {
	if f.Kind == ir.KindBytes {
		return "string"
	}
	return FieldGoType(f)
}

// MapKeyExpr converts an expression into a comparable Go map key.
func MapKeyExpr(expr string, f ir.FieldSpec) string {
	if f.Kind == ir.KindBytes {
		return "string(" + expr + ")"
	}
	return expr
}

// MutationVerb returns the Go method prefix ("Add", "Max", "Min") for an atomic mutation.
func MutationVerb(m ir.MutationType) string {
	switch m {
	case ir.MutationAdd:
		return "Add"
	case ir.MutationMax:
		return "Max"
	case ir.MutationMin:
		return "Min"
	default:
		return "Set"
	}
}

func pkTypeExpr(msg ir.MessageSpec) string {
	if len(msg.PrimaryKeyFields) == 1 {
		return FieldGoType(msg.PrimaryKeyFields[0])
	}
	if len(msg.PrimaryKeyFields) > 1 {
		return msg.Name + "PrimaryKey"
	}
	return "struct{}"
}

func pkTupleArgsFromEntity(msg ir.MessageSpec, varName string) string {
	parts := make([]string, 0, len(msg.PrimaryKeyFields))
	for _, f := range msg.PrimaryKeyFields {
		parts = append(parts, PackField(fmt.Sprintf("%s.%s", varName, f.GoName), f))
	}
	return strings.Join(parts, ", ")
}

func pkTupleArgsFromParam(msg ir.MessageSpec) string {
	if len(msg.PrimaryKeyFields) == 1 {
		return PackField("pk", msg.PrimaryKeyFields[0])
	}
	parts := make([]string, 0, len(msg.PrimaryKeyFields))
	for _, f := range msg.PrimaryKeyFields {
		parts = append(parts, PackField("pk."+f.GoName, f))
	}
	return strings.Join(parts, ", ")
}

func versionstampedPKTupleArgs(msg ir.MessageSpec) string {
	parts := make([]string, 0, len(msg.PrimaryKeyFields))
	for _, f := range msg.PrimaryKeyFields {
		if f.IsVersionstamp {
			parts = append(parts, "tuple.IncompleteVersionstamp(r.store.NextUserVersion())")
		} else {
			parts = append(parts, PackField("entity."+f.GoName, f))
		}
	}
	return strings.Join(parts, ", ")
}

func indexFieldTupleArgs(fields []ir.FieldSpec, varName string) string {
	parts := make([]string, 0, len(fields))
	for _, f := range fields {
		parts = append(parts, PackField(fmt.Sprintf("%s.%s", varName, f.GoName), f))
	}
	return strings.Join(parts, ", ")
}

func fieldParamDecls(fields []ir.FieldSpec) string {
	parts := make([]string, 0, len(fields))
	for _, f := range fields {
		parts = append(parts, f.GoName+" "+FieldGoType(f))
	}
	return strings.Join(parts, ", ")
}

func emitFanOutIndexWrite(g *protogen.GeneratedFile, msg ir.MessageSpec, idx ir.SecondaryIndexSpec, repeatedIdx int, varName string, isSet bool, indent string) {
	op := "Clear"
	if isSet {
		op = "Set"
	}
	g.P(indent, "tr.", op, "(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, ", idx.IndexID, ",")
	for j, sf := range idx.Fields {
		if j == repeatedIdx {
			g.P(indent, "\t", PackField("item", sf), ",")
		} else {
			g.P(indent, "\t", PackField(varName+"."+sf.GoName, sf), ",")
		}
	}
	for _, pkf := range msg.PrimaryKeyFields {
		g.P(indent, "\t", PackField(varName+"."+pkf.GoName, pkf), ",")
	}
	if isSet {
		g.P(indent, "}), []byte{})")
	} else {
		g.P(indent, "}))")
	}
}
