// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: fdb-layer/annotations.proto

package fdblayer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MutationType int32

const (
	MutationType_MUTATION_NONE MutationType = 0
	MutationType_MUTATION_ADD  MutationType = 1
	MutationType_MUTATION_MAX  MutationType = 2
	MutationType_MUTATION_MIN  MutationType = 3
)

// Enum value maps for MutationType.
var (
	MutationType_name = map[int32]string{
		0: "MUTATION_NONE",
		1: "MUTATION_ADD",
		2: "MUTATION_MAX",
		3: "MUTATION_MIN",
	}
	MutationType_value = map[string]int32{
		"MUTATION_NONE": 0,
		"MUTATION_ADD":  1,
		"MUTATION_MAX":  2,
		"MUTATION_MIN":  3,
	}
)

func (x MutationType) Enum() *MutationType {
	p := new(MutationType)
	*p = x
	return p
}

func (x MutationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationType) Descriptor() protoreflect.EnumDescriptor {
	return file_fdb_layer_annotations_proto_enumTypes[0].Descriptor()
}

func (MutationType) Type() protoreflect.EnumType {
	return &file_fdb_layer_annotations_proto_enumTypes[0]
}

func (x MutationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationType.Descriptor instead.
func (MutationType) EnumDescriptor() ([]byte, []int) {
	return file_fdb_layer_annotations_proto_rawDescGZIP(), []int{0}
}

type SecondaryIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecondaryIndex) Reset() {
	*x = SecondaryIndex{}
	mi := &file_fdb_layer_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecondaryIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecondaryIndex) ProtoMessage() {}

func (x *SecondaryIndex) ProtoReflect() protoreflect.Message {
	mi := &file_fdb_layer_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecondaryIndex.ProtoReflect.Descriptor instead.
func (*SecondaryIndex) Descriptor() ([]byte, []int) {
	return file_fdb_layer_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *SecondaryIndex) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var file_fdb_layer_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50001,
		Name:          "annotations.primary_key",
		Tag:           "bytes,50001,rep,name=primary_key",
		Filename:      "fdb-layer/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]*SecondaryIndex)(nil),
		Field:         50002,
		Name:          "annotations.secondary_index",
		Tag:           "bytes,50002,rep,name=secondary_index",
		Filename:      "fdb-layer/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*MutationType)(nil),
		Field:         50003,
		Name:          "annotations.mutation",
		Tag:           "varint,50003,opt,name=mutation,enum=annotations.MutationType",
		Filename:      "fdb-layer/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50004,
		Name:          "annotations.is_versionstamp",
		Tag:           "varint,50004,opt,name=is_versionstamp",
		Filename:      "fdb-layer/annotations.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// List of field names that constitute the primary key
	//
	// repeated string primary_key = 50001;
	E_PrimaryKey = &file_fdb_layer_annotations_proto_extTypes[0]
	// List of composite secondary indexes
	//
	// repeated annotations.SecondaryIndex secondary_index = 50002;
	E_SecondaryIndex = &file_fdb_layer_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional annotations.MutationType mutation = 50003;
	E_Mutation = &file_fdb_layer_annotations_proto_extTypes[2]
	// optional bool is_versionstamp = 50004;
	E_IsVersionstamp = &file_fdb_layer_annotations_proto_extTypes[3]
)

var File_fdb_layer_annotations_proto protoreflect.FileDescriptor

const file_fdb_layer_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1bfdb-layer/annotations.proto\x12\vannotations\x1a google/protobuf/descriptor.proto\"(\n" +
	"\x0eSecondaryIndex\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields*W\n" +
	"\fMutationType\x12\x11\n" +
	"\rMUTATION_NONE\x10\x00\x12\x10\n" +
	"\fMUTATION_ADD\x10\x01\x12\x10\n" +
	"\fMUTATION_MAX\x10\x02\x12\x10\n" +
	"\fMUTATION_MIN\x10\x03:B\n" +
	"\vprimary_key\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x03(\tR\n" +
	"primaryKey:g\n" +
	"\x0fsecondary_index\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x03(\v2\x1b.annotations.SecondaryIndexR\x0esecondaryIndex:V\n" +
	"\bmutation\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\x0e2\x19.annotations.MutationTypeR\bmutation:H\n" +
	"\x0fis_versionstamp\x12\x1d.google.protobuf.FieldOptions\x18Ԇ\x03 \x01(\bR\x0eisVersionstampB>Z<github.com/romannikov/fdb-go-layer-plugin/fdb-layer;fdblayerb\x06proto3"

var (
	file_fdb_layer_annotations_proto_rawDescOnce sync.Once
	file_fdb_layer_annotations_proto_rawDescData []byte
)

func file_fdb_layer_annotations_proto_rawDescGZIP() []byte {
	file_fdb_layer_annotations_proto_rawDescOnce.Do(func() {
		file_fdb_layer_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fdb_layer_annotations_proto_rawDesc), len(file_fdb_layer_annotations_proto_rawDesc)))
	})
	return file_fdb_layer_annotations_proto_rawDescData
}

var file_fdb_layer_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fdb_layer_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fdb_layer_annotations_proto_goTypes = []any{
	(MutationType)(0),                   // 0: annotations.MutationType
	(*SecondaryIndex)(nil),              // 1: annotations.SecondaryIndex
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
}
var file_fdb_layer_annotations_proto_depIdxs = []int32{
	2, // 0: annotations.primary_key:extendee -> google.protobuf.MessageOptions
	2, // 1: annotations.secondary_index:extendee -> google.protobuf.MessageOptions
	3, // 2: annotations.mutation:extendee -> google.protobuf.FieldOptions
	3, // 3: annotations.is_versionstamp:extendee -> google.protobuf.FieldOptions
	1, // 4: annotations.secondary_index:type_name -> annotations.SecondaryIndex
	0, // 5: annotations.mutation:type_name -> annotations.MutationType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fdb_layer_annotations_proto_init() }
func file_fdb_layer_annotations_proto_init() {
	if File_fdb_layer_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fdb_layer_annotations_proto_rawDesc), len(file_fdb_layer_annotations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_fdb_layer_annotations_proto_goTypes,
		DependencyIndexes: file_fdb_layer_annotations_proto_depIdxs,
		EnumInfos:         file_fdb_layer_annotations_proto_enumTypes,
		MessageInfos:      file_fdb_layer_annotations_proto_msgTypes,
		ExtensionInfos:    file_fdb_layer_annotations_proto_extTypes,
	}.Build()
	File_fdb_layer_annotations_proto = out.File
	file_fdb_layer_annotations_proto_goTypes = nil
	file_fdb_layer_annotations_proto_depIdxs = nil
}
