// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: fdb-layer/annotations.proto

package fdblayer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecondaryIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecondaryIndex) Reset() {
	*x = SecondaryIndex{}
	mi := &file_fdb_layer_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecondaryIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecondaryIndex) ProtoMessage() {}

func (x *SecondaryIndex) ProtoReflect() protoreflect.Message {
	mi := &file_fdb_layer_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecondaryIndex.ProtoReflect.Descriptor instead.
func (*SecondaryIndex) Descriptor() ([]byte, []int) {
	return file_fdb_layer_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *SecondaryIndex) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var file_fdb_layer_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50001,
		Name:          "annotations.primary_key",
		Tag:           "bytes,50001,rep,name=primary_key",
		Filename:      "fdb-layer/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]*SecondaryIndex)(nil),
		Field:         50002,
		Name:          "annotations.secondary_index",
		Tag:           "bytes,50002,rep,name=secondary_index",
		Filename:      "fdb-layer/annotations.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// List of field names that constitute the primary key
	//
	// repeated string primary_key = 50001;
	E_PrimaryKey = &file_fdb_layer_annotations_proto_extTypes[0]
	// List of composite secondary indexes
	//
	// repeated annotations.SecondaryIndex secondary_index = 50002;
	E_SecondaryIndex = &file_fdb_layer_annotations_proto_extTypes[1]
)

var File_fdb_layer_annotations_proto protoreflect.FileDescriptor

const file_fdb_layer_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1bfdb-layer/annotations.proto\x12\vannotations\x1a google/protobuf/descriptor.proto\"(\n" +
	"\x0eSecondaryIndex\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields:B\n" +
	"\vprimary_key\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x03(\tR\n" +
	"primaryKey:g\n" +
	"\x0fsecondary_index\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x03(\v2\x1b.annotations.SecondaryIndexR\x0esecondaryIndexB>Z<github.com/romannikov/fdb-go-layer-plugin/fdb-layer;fdblayerb\x06proto3"

var (
	file_fdb_layer_annotations_proto_rawDescOnce sync.Once
	file_fdb_layer_annotations_proto_rawDescData []byte
)

func file_fdb_layer_annotations_proto_rawDescGZIP() []byte {
	file_fdb_layer_annotations_proto_rawDescOnce.Do(func() {
		file_fdb_layer_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fdb_layer_annotations_proto_rawDesc), len(file_fdb_layer_annotations_proto_rawDesc)))
	})
	return file_fdb_layer_annotations_proto_rawDescData
}

var file_fdb_layer_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fdb_layer_annotations_proto_goTypes = []any{
	(*SecondaryIndex)(nil),              // 0: annotations.SecondaryIndex
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_fdb_layer_annotations_proto_depIdxs = []int32{
	1, // 0: annotations.primary_key:extendee -> google.protobuf.MessageOptions
	1, // 1: annotations.secondary_index:extendee -> google.protobuf.MessageOptions
	0, // 2: annotations.secondary_index:type_name -> annotations.SecondaryIndex
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fdb_layer_annotations_proto_init() }
func file_fdb_layer_annotations_proto_init() {
	if File_fdb_layer_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fdb_layer_annotations_proto_rawDesc), len(file_fdb_layer_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_fdb_layer_annotations_proto_goTypes,
		DependencyIndexes: file_fdb_layer_annotations_proto_depIdxs,
		MessageInfos:      file_fdb_layer_annotations_proto_msgTypes,
		ExtensionInfos:    file_fdb_layer_annotations_proto_extTypes,
	}.Build()
	File_fdb_layer_annotations_proto = out.File
	file_fdb_layer_annotations_proto_goTypes = nil
	file_fdb_layer_annotations_proto_depIdxs = nil
}
