// Code generated by fdb-go-layer-plugin. DO NOT EDIT.
// Source: github.com/romannikov/fdb-go-layer-plugin/tests/store

package store

import (
	"context"

	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	fdblayer "github.com/romannikov/fdb-go-layer-plugin/fdb-layer"
	"google.golang.org/protobuf/proto"
)

// ProductPaginationOptions represents options for paginated queries
type ProductPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// ProductPaginatedResult represents a paginated result set
type ProductPaginatedResult struct {
	Items   []*Product
	NextKey tuple.Tuple
	HasMore bool
}

// ProductRepository defines the repository interface for Product.
type ProductRepository interface {
	fdblayer.GenericRepository[*Product, string]

	BatchGetProduct(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Product, error)
	ListProduct(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts ProductPaginationOptions) (*ProductPaginatedResult, error)

	GetProductByCategory(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, Category string) ([]*Product, error)
}

type productRepository struct {
	store *fdblayer.RecordStore
}

// NewProductRepository creates a new ProductRepository instance.
func NewProductRepository(store *fdblayer.RecordStore) ProductRepository {
	return &productRepository{store: store}
}

// Create creates a new Product entity in the database.
func (r *productRepository) Create(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *Product) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Product")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Save atomic fields and zero them out for marshaling

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{

		// Standard index
		indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Category",
			entity.Category,
			entity.Id,
		})
		tr.Set(indexKey, []byte{})

	}

	return nil
}

// Get retrieves a Product entity by its primary key.
func (r *productRepository) Get(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, pk string) (*Product, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Product")
	if err != nil {
		return nil, err
	}

	key := dir.Pack(tuple.Tuple{typeID, pk})
	value := tr.Get(key).MustGet()
	if value == nil {
		return nil, fmt.Errorf("product not found")
	}
	entity := &Product{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}

	// Read atomic fields

	return entity, nil
}

// Set updates an existing Product entity in the database.
func (r *productRepository) Set(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *Product) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Product")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, entity.Id})

	// Clear stale index entries from the old version of the entity
	oldValue := tr.Get(key).MustGet()
	if oldValue != nil {
		old := &Product{}
		if unmarshalErr := proto.Unmarshal(oldValue, old); unmarshalErr == nil {

			{

				// Standard index
				oldIndexKey := dir.Pack(tuple.Tuple{typeID, "index", "Category",
					old.Category,
					old.Id,
				})
				tr.Clear(oldIndexKey)

			}

		}
	}

	// Save atomic fields and zero them out for marshaling

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	// Restore atomic fields

	tr.Set(key, value)

	// Store atomic fields in separate keys

	{

		// Standard index
		indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Category",
			entity.Category,
			entity.Id,
		})
		tr.Set(indexKey, []byte{})

	}

	return nil
}

// Delete removes a Product entity from the database.
func (r *productRepository) Delete(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, pk string) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("Product")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, pk})
	value := tr.Get(key).MustGet()
	if value != nil {
		entity := &Product{}
		err := proto.Unmarshal(value, entity)
		if err == nil {

			{

				// Standard index
				indexKey := dir.Pack(tuple.Tuple{typeID, "index", "Category",
					entity.Category,
					entity.Id,
				})
				tr.Clear(indexKey)

			}

		}
	}
	tr.Clear(key)
	// Clear atomic fields

	return nil
}

// BatchGetProduct retrieves multiple Product entities by their primary keys.
func (r *productRepository) BatchGetProduct(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*Product, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Product")
	if err != nil {
		return nil, err
	}

	result := make(map[string]*Product)
	futures := make([]fdb.FutureByteSlice, len(ids))

	for i, id := range ids {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		keyTpl := append(tuple.Tuple{typeID}, id...)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}

	for i, future := range futures {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &Product{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		result[ids[i].String()] = entity
	}

	return result, nil
}

// ListProduct retrieves a list of Product entities starting from the given key.
func (r *productRepository) ListProduct(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts ProductPaginationOptions) (*ProductPaginatedResult, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Product")
	if err != nil {
		return nil, err
	}

	result := &ProductPaginatedResult{
		Items: make([]*Product, 0),
	}

	beginTpl := append(tuple.Tuple{typeID}, opts.Begin...)
	begin := dir.Pack(beginTpl)

	// Scan all keys under typeID. We request extra rows to account for
	// index entries that will be filtered out.
	typePrefix := dir.Pack(tuple.Tuple{typeID})
	typePrefixRange, err := fdb.PrefixRange(typePrefix)
	if err != nil {
		return nil, err
	}

	iter := tr.GetRange(fdb.KeyRange{
		Begin: begin,
		End:   typePrefixRange.End,
	}, fdb.RangeOptions{
		Reverse: false,
	}).Iterator()

	var nextKey fdb.Key
	for iter.Advance() {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		kv := iter.MustGet()

		// Skip index entries: their second tuple element is the string "index".
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack key: %w", err)
		}
		if len(tpl) >= 2 {
			if s, ok := tpl[1].(string); ok && s == "index" {
				continue
			}
		}

		entity := &Product{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID to return just the PK tuple
		result.NextKey = tpl[1:]
		result.Items = result.Items[:opts.Limit]
	}

	return result, nil
}

// GetProductByCategory retrieves Product entities by their Category index.
func (r *productRepository) GetProductByCategory(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, Category string) ([]*Product, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("Product")
	if err != nil {
		return nil, err
	}

	entities := []*Product{}
	indexKeyPrefix := dir.Pack(tuple.Tuple{typeID, "index", "Category", Category})
	indexRange, err := fdb.PrefixRange(indexKeyPrefix)
	if err != nil {
		return nil, err
	}
	kvs := tr.GetRange(indexRange, fdb.RangeOptions{}).GetSliceOrPanic()
	for _, kv := range kvs {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, err
		}
		pkIndexStart := 3 + 1
		pkTuple := tpl[pkIndexStart:]
		keyTpl := append(tuple.Tuple{typeID}, pkTuple...)
		key := dir.Pack(keyTpl)
		value := tr.Get(key).MustGet()
		if value == nil {
			continue
		}
		entity := &Product{}
		err = proto.Unmarshal(value, entity)
		if err != nil {
			return nil, err
		}
		entities = append(entities, entity)
	}
	return entities, nil
}
