// Code generated by fdb-go-layer-plugin. DO NOT EDIT.
// Source: github.com/romannikov/fdb-go-layer-plugin/tests/store

package store

import (
	"context"
	"fmt"

	"github.com/apple/foundationdb/bindings/go/src/fdb"
	"github.com/apple/foundationdb/bindings/go/src/fdb/directory"
	"github.com/apple/foundationdb/bindings/go/src/fdb/tuple"
	fdblayer "github.com/romannikov/fdb-go-layer-plugin/fdb-layer"
	"google.golang.org/protobuf/proto"
)

// UserPaginationOptions represents options for paginated queries
type UserPaginationOptions struct {
	Begin tuple.Tuple
	Limit int
}

// UserPaginatedResult represents a paginated result set
type UserPaginatedResult struct {
	Items   []*User
	NextKey tuple.Tuple
	HasMore bool
}

// UserRepository defines the repository interface for User.
type UserRepository interface {
	fdblayer.GenericRepository[*User, string]

	BatchGetUser(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*User, error)
	ListUser(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts UserPaginationOptions) (*UserPaginatedResult, error)
	GetUserByEmail(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, Email string) ([]*User, error)
}

type userRepository struct {
	store *fdblayer.RecordStore
}

// NewUserRepository creates a new UserRepository instance.
func NewUserRepository(store *fdblayer.RecordStore) UserRepository {
	return &userRepository{store: store}
}

// Create creates a new User entity in the database.
func (r *userRepository) Create(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *User) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("User")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, entity.Id})
	if existing := tr.Get(key).MustGet(); existing != nil {
		return fmt.Errorf("user %w", fdblayer.ErrAlreadyExists)
	}

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	tr.Set(key, value)

	// Standard index
	tr.Set(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 2324124615, entity.Email, entity.Id}), []byte{})

	return nil
}

// Get retrieves a User entity by its primary key.
func (r *userRepository) Get(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, pk string) (*User, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("User")
	if err != nil {
		return nil, err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, pk})
	valueFuture := tr.Get(key)
	value := valueFuture.MustGet()
	if value == nil {
		return nil, fmt.Errorf("user not found")
	}
	entity := &User{}
	err = proto.Unmarshal(value, entity)
	if err != nil {
		return nil, err
	}

	return entity, nil
}

// Set updates an existing User entity in the database.
func (r *userRepository) Set(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, entity *User) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("User")
	if err != nil {
		return err
	}

	var old *User

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, entity.Id})

	if oldValue := tr.Get(key).MustGet(); oldValue != nil {
		var unmarshaled User
		if unmarshalErr := proto.Unmarshal(oldValue, &unmarshaled); unmarshalErr == nil {
			old = &unmarshaled
		}
	}

	value, err := proto.Marshal(entity)
	if err != nil {
		return err
	}

	tr.Set(key, value)

	// Standard index
	if old == nil || old.Email != entity.Email {
		if old != nil {
			tr.Clear(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 2324124615, old.Email, old.Id}))
		}
		tr.Set(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 2324124615, entity.Email, entity.Id}), []byte{})
	}

	return nil
}

// Delete removes a User entity from the database.
func (r *userRepository) Delete(ctx context.Context, tr fdblayer.Transaction, dir directory.DirectorySubspace, pk string) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	typeID, err := r.store.GetTypeID("User")
	if err != nil {
		return err
	}

	key := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace, pk})
	value := tr.Get(key).MustGet()
	if value != nil {
		entity := &User{}
		err := proto.Unmarshal(value, entity)
		if err == nil {
			// Standard index
			tr.Clear(dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 2324124615, entity.Email, entity.Id}))
		}
	}
	tr.Clear(key)

	return nil
}

// BatchGetUser retrieves multiple User entities by their primary keys.
func (r *userRepository) BatchGetUser(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, ids []tuple.Tuple) (map[string]*User, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("User")
	if err != nil {
		return nil, err
	}

	result := make(map[string]*User)
	futures := make([]fdb.FutureByteSlice, len(ids))

	for i, id := range ids {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		keyTpl := make(tuple.Tuple, 2+len(id))
		keyTpl[0] = typeID
		keyTpl[1] = fdblayer.DataNamespace
		copy(keyTpl[2:], id)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}

	for i, future := range futures {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &User{}
		err := proto.Unmarshal(value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity at index %d: %w", i, err)
		}
		result[ids[i].String()] = entity
	}

	return result, nil
}

// ListUser retrieves a list of User entities starting from the given key.
func (r *userRepository) ListUser(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, opts UserPaginationOptions) (*UserPaginatedResult, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("User")
	if err != nil {
		return nil, err
	}

	result := &UserPaginatedResult{
		Items: make([]*User, 0),
	}

	beginTpl := make(tuple.Tuple, 2+len(opts.Begin))
	beginTpl[0] = typeID
	beginTpl[1] = fdblayer.DataNamespace
	copy(beginTpl[2:], opts.Begin)
	begin := dir.Pack(beginTpl)

	// Scan only data keys under typeID namespace.
	dataPrefix := dir.Pack(tuple.Tuple{typeID, fdblayer.DataNamespace})
	dataPrefixRange, err := fdb.PrefixRange(dataPrefix)
	if err != nil {
		return nil, err
	}

	rangeOpts := fdb.RangeOptions{
		Reverse: false,
	}
	if opts.Limit > 0 {
		rangeOpts.Limit = opts.Limit + 1
	}

	iter := tr.GetRange(fdb.KeyRange{
		Begin: begin,
		End:   dataPrefixRange.End,
	}, rangeOpts).Iterator()

	var nextKey fdb.Key
	for iter.Advance() {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		kv := iter.MustGet()

		entity := &User{}
		err = proto.Unmarshal(kv.Value, entity)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal entity: %w", err)
		}
		result.Items = append(result.Items, entity)
		nextKey = kv.Key

		// Stop once we have enough items for pagination check
		if opts.Limit > 0 && len(result.Items) > opts.Limit {
			break
		}
	}

	result.HasMore = opts.Limit > 0 && len(result.Items) > opts.Limit
	if result.HasMore {
		tpl, err := dir.Unpack(nextKey)
		if err != nil {
			return nil, fmt.Errorf("failed to unpack next key: %w", err)
		}
		// Remove typeID and DataNamespace to return just the PK tuple
		result.NextKey = tpl[2:]
		result.Items = result.Items[:opts.Limit]
	}

	return result, nil
}

// GetUserByEmail retrieves User entities by their Email index.
func (r *userRepository) GetUserByEmail(ctx context.Context, tr fdb.ReadTransaction, dir directory.DirectorySubspace, Email string) ([]*User, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	typeID, err := r.store.GetTypeID("User")
	if err != nil {
		return nil, err
	}

	entities := []*User{}
	indexKeyPrefix := dir.Pack(tuple.Tuple{typeID, fdblayer.IndexNamespace, 2324124615, Email})
	indexRange, err := fdb.PrefixRange(indexKeyPrefix)
	if err != nil {
		return nil, err
	}
	kvs := tr.GetRange(indexRange, fdb.RangeOptions{}).GetSliceOrPanic()
	futures := make([]fdb.FutureByteSlice, len(kvs))
	for i, kv := range kvs {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		tpl, err := dir.Unpack(kv.Key)
		if err != nil {
			return nil, err
		}
		pkIndexStart := 3 + 1
		if len(tpl) <= pkIndexStart {
			continue
		}
		pkTuple := tpl[pkIndexStart:]
		keyTpl := make(tuple.Tuple, 2+len(pkTuple))
		keyTpl[0] = typeID
		keyTpl[1] = fdblayer.DataNamespace
		copy(keyTpl[2:], pkTuple)
		key := dir.Pack(keyTpl)
		futures[i] = tr.Get(key)
	}
	for _, future := range futures {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		if future == nil {
			continue
		}
		value := future.MustGet()
		if value == nil {
			continue
		}
		entity := &User{}
		err = proto.Unmarshal(value, entity)
		if err != nil {
			return nil, err
		}
		entities = append(entities, entity)
	}
	return entities, nil
}
